// Actual controller/SDK reader control on Linux tmpfs, with separate author/reader UIDs.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {createSkillValidationController,skillValidationRoot} from '/proof/controller.mjs';
fs.chownSync('/data',1000,0);process.setgroups([0,fs.statSync('/docker.sock').gid]);process.setgid(0);process.setuid(1000);process.umask(0o077);
const sha=x=>createHash('sha256').update(x).digest('hex');const config={dataDir:'/data',runtimeContainerBin:'/proof/docker-proxy.mjs',runtimeContainerImage:process.env.FIXTURE_IMAGE_ID,runtimeDataVolume:process.env.FIXTURE_VOLUME};
const ownerHash=sha('linux-validator-owner');const rootFor=mode=>{const reference={ownerHash,contentId:sha(mode),kind:'imports',expectedName:null};const root=skillValidationRoot(config,reference);fs.mkdirSync(root+'/bundle',{recursive:true,mode:0o700});const text=mode==='failure'?'---\nname: [invalid-native\n---\nbody':'---\nname: linux-review\ndescription: Evidence review\n---\nFixture evidence instructions.';fs.writeFileSync(root+'/bundle/SKILL.md',text,{mode:0o400});return{reference,root,text};};
function unchanged(source){const stat=fs.statSync(source.root+'/bundle/SKILL.md');assert.equal(stat.uid,1000);assert.equal(stat.mode&4095,0o400);assert.equal(fs.statSync(source.root+'/bundle').mode&4095,0o700);assert.equal(fs.readFileSync(source.root+'/bundle/SKILL.md','utf8'),source.text);}
function clean(){const owners='/data/.openscience/skill-validation-state/projections';const jobs=fs.existsSync(owners+'/'+ownerHash)?fs.readdirSync(owners+'/'+ownerHash):[];assert.deepEqual(jobs,[]);assert.equal(fs.existsSync('/data/.openscience/skill-validation-state/creation-uncertain.json'),false);const absent=spawnSync(config.runtimeContainerBin,['inspect','evimed-skill-validation'],{encoding:'utf8',timeout:5000});assert.notEqual(absent.status,0);}
const success=rootFor('success');
// Demonstrate the original source really is unreadable by the fixed native UID.
const mount='type=volume,src='+config.runtimeDataVolume+',dst=/input,volume-subpath='+path.relative('/data',success.root)+',readonly';const originalName='evimed-original-private-'+randomUUID();
const original=spawnSync(config.runtimeContainerBin,['create','--read-only','--network=none','--cap-drop=ALL','--security-opt=no-new-privileges','--pids-limit=32','--cpus=0.5','--memory=256m','--memory-swap=256m','--tmpfs','/tmp:rw,noexec,nosuid,nodev,size=16m','--tmpfs','/workspace:ro,noexec,nosuid,nodev,size=1m','--tmpfs','/runtime:ro,noexec,nosuid,nodev,size=1m','--name',originalName,'--label','fixture=true','--user','10001:10001','--mount',mount,'--entrypoint','node',config.runtimeContainerImage,'/opt/evimed/socket/scripts/validate-personal-skill.mjs',''],{encoding:'utf8',timeout:5000});assert.equal(original.status,0);const originalId=original.stdout.trim();try{const read=spawnSync(config.runtimeContainerBin,['start','--attach',originalId],{encoding:'utf8',timeout:5000});assert.notEqual(read.status,0);}finally{assert.equal(spawnSync(config.runtimeContainerBin,['rm','-f',originalId],{timeout:5000}).status,0);}
const controller=createSkillValidationController(config,{availableMemory:async()=>2*1024**3});try{const result=await controller.validate(success.reference);assert.equal(result.name,'linux-review');assert.equal(result.instructions,'Fixture evidence instructions.');unchanged(success);clean();}finally{await controller.close();}
const failure=rootFor('failure');const failed=createSkillValidationController(config,{availableMemory:async()=>2*1024**3});try{await assert.rejects(failed.validate(failure.reference));unchanged(failure);clean();}finally{await failed.close();}
for(const mode of ['timeout','cancel']){const source=rootFor(mode),abort=new AbortController();const current=createSkillValidationController(config,{availableMemory:async()=>2*1024**3,setTimer:callback=>setTimeout(mode==='timeout'?callback:()=>abort.abort(),1)});try{await assert.rejects(current.validate(source.reference,abort.signal));unchanged(source);clean();}finally{await current.close();}}
const replacedSource=rootFor('replacement'),cancel=new AbortController();let reused;
const replacementController=createSkillValidationController(config,{availableMemory:async()=>2*1024**3,setTimer:()=>{
 const result=spawnSync(config.runtimeContainerBin,['replace'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);reused=JSON.parse(result.stdout);cancel.abort();return setTimeout(()=>{},10000);
}});
try{await assert.rejects(replacementController.validate(replacedSource.reference,cancel.signal),{code:'product_state_unavailable'});const survivor=spawnSync(config.runtimeContainerBin,['inspect',reused.replacementId],{encoding:'utf8',timeout:5000});assert.equal(survivor.status,0);assert.equal(JSON.parse(survivor.stdout).Id,reused.replacementId);const marker=JSON.parse(fs.readFileSync('/data/.openscience/skill-validation-state/creation-uncertain.json','utf8'));assert.equal(marker.containerId,reused.originalId);unchanged(replacedSource);}
finally{for(const id of [reused?.replacementId,reused?.originalId])if(id)spawnSync(config.runtimeContainerBin,['rm','-f',id],{timeout:5000});await replacementController.close();clean();}
console.log(JSON.stringify({linux:true,authorUid:process.getuid(),nativeReaderUid:10001,originalPrivateReadDenied:true,projectedNativeParse:true,originalBytesAndModesUnchanged:true,joinedCleanup:['success','failure','timeout','cancel'],scratchAbsent:true,sameNameSameLabelsReplacementSurvived:true}));
