// @vitest-environment node
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { COLOR_ROLES, CONTAINERS, FONT_STACKS, RADII, TYPE_SCALE, TYPE_SIZES } from "@evimed/design-tokens";
import { contrastFailures } from "@evimed/design-tokens/contrast";
import { DESIGN_TOKENS_CSS_BEGIN, DESIGN_TOKENS_CSS_END, designTokensCss } from "@evimed/design-tokens/css";
import { kernelThemeTokens } from "@evimed/design-tokens/kernel";
import tailwindConfig from "../../tailwind.config.js";

/**
 * The design system has one source — `@evimed/design-tokens` — and consumers
 * that cannot import it as JavaScript, import it as a build input, or are
 * compiled somewhere else entirely (the Vue shell is a different repository).
 * This file is what makes "one source" a fact rather than a comment:
 *
 *  1. `src/index.css` carries a generated block. A generator nobody checks is
 *     how the shell and the kernel frame drifted into two hand-maintained
 *     tables in the first place, so the block is regenerated here and compared
 *     byte for byte.
 *  2. `tailwind.config.js` derives its scales from the module; the assertions
 *     below prove the derivation is live, not a copy that looks like one.
 *  3. A colour written as a literal anywhere in `src/` reaches no theme
 *     switch, contrast audit or brand change.
 */
const SRC = fileURLToPath(new URL("..", import.meta.url));
const INDEX_CSS = join(SRC, "index.css");

/**
 * Tailwind types every scale as `ResolvableTo<…>` — a value *or* a function of
 * the plugin utilities — so nothing in it is indexable until it is resolved.
 * Ours is a literal object, generated by the token package into the preset both
 * front ends extend, which is the whole point of the assertions below, so it is
 * read as one. Reading it through `presets[0]` rather than `theme.extend` is
 * deliberate: the config's own theme is empty, and a test that read the wrong
 * place would pass while the shell rendered from nothing.
 */
const preset = (tailwindConfig.presets?.[0] ?? {}) as { theme?: { extend?: unknown } };
const theme = (preset.theme?.extend ?? {}) as {
  colors?: Record<string, string | Record<string, string>>;
  fontFamily?: Record<string, string>;
  fontSize?: Record<string, [string, string]>;
  maxWidth?: Record<string, string>;
  borderRadius?: Record<string, string>;
};

const ALLOWED: Record<string, string> = {
  "index.css": "the token file itself",
  "components/inspector/OfficePreview.tsx": "styles for a rendered Office document inside its own shadow root",
  "components/inspector/AnomalyMapView.tsx": "a data map drawn on a fixed dark scientific canvas",
  "components/inspector/FitsView.tsx": "an astronomy image well, fixed dark",
  "components/inspector/MeshView.tsx": "WebGL scene background handed to the renderer",
  "components/inspector/QCodeView.tsx": "a label colour handed to the circuit renderer",
  "lib/xlsx.ts": "default cell border when a spreadsheet does not declare one",
};

// `&#123;` and `#anchor` are not colours; a colour is 3, 4, 6 or 8 hex digits
// — or a colour function, which reaches a theme no better than a hex does.
const HEX = /(?<![\w&])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{4}|[0-9a-fA-F]{3})\b|\b(?:rgba?|hsla?|oklch|oklab|lab|lch)\(/;

// Any serif face the chrome must not name. `serif` alone would match
// `sans-serif`, so the generic keyword is checked separately.
const SERIF_FACES = /source serif|songti|georgia|cambria|times new roman|noto serif|source han serif|simsun|宋体/i;

function sourceFiles(directory: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "test" || entry.name === "__fixtures__") continue;
      files.push(...sourceFiles(path));
    } else if (/\.(tsx?|css)$/.test(entry.name) && !/\.test\./.test(entry.name)) {
      files.push(path);
    }
  }
  return files;
}

describe("the token table has one source", () => {
  it("regenerates the block in index.css byte for byte", () => {
    const css = readFileSync(INDEX_CSS, "utf8");
    const start = css.indexOf(DESIGN_TOKENS_CSS_BEGIN);
    const end = css.indexOf(DESIGN_TOKENS_CSS_END);
    expect(start, "index.css lost its generated-token markers").toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    const checkedIn = css.slice(start, end + DESIGN_TOKENS_CSS_END.length);
    expect(checkedIn, "run `pnpm tokens:css` — index.css no longer matches @evimed/design-tokens").toEqual(
      designTokensCss(),
    );
  });

  it("defines every colour role in both themes, and nothing outside the block redefines one", () => {
    const css = readFileSync(INDEX_CSS, "utf8");
    const generated = designTokensCss();
    const outside = css.split(generated).join("");
    for (const role of Object.keys(COLOR_ROLES)) {
      expect(generated).toContain(`--${role}:`);
      // Two declarations, one per theme.
      expect(generated.split(`  --${role}:`).length - 1, `--${role} must be set in light and dark`).toBe(2);
      expect(outside, `--${role} is redefined outside the generated block`).not.toContain(`--${role}:`);
    }
  });

  it("derives the tailwind theme from the module rather than restating it", () => {
    expect(theme.fontFamily?.sans).toBe(FONT_STACKS.sans);
    expect(theme.borderRadius?.card).toBe(`${RADII.card}px`);
    expect(theme.borderRadius?.DEFAULT).toBe(`${RADII.control}px`);
    // Three columns now, not one: a reading page, a list page and a data page.
    expect(theme.maxWidth?.read).toBe(`${CONTAINERS.read}px`);
    expect(theme.maxWidth?.page).toBe(`${CONTAINERS.page}px`);
    expect(theme.maxWidth?.wide).toBe(`${CONTAINERS.wide}px`);
    expect(theme.maxWidth?.content).toBe(`${CONTAINERS.content}px`);
    // Retired names converge on the list column rather than breaking.
    expect(theme.maxWidth?.["content-wide"]).toBe(`${CONTAINERS.full}px`);
    // A blanket map of CONTAINERS would define `max-w-full` as a pixel width
    // and silently break every `max-w-full` in both code bases.
    expect(theme.maxWidth?.full).toBeUndefined();
    for (const [rung, { size, lineHeight }] of Object.entries(TYPE_SCALE)) {
      expect(theme.fontSize?.[rung], `the ${rung} rung`).toEqual([`${size}px`, lineHeight]);
    }
    // Every colour role is reachable as a class, and every colour Tailwind
    // knows is a `var()` — never a literal a theme switch cannot move.
    for (const role of Object.keys(COLOR_ROLES)) {
      expect(theme.colors?.[role], `the ${role} role`).toBe(`var(--${role})`);
    }
    // Every colour Tailwind knows is a `var()` — never a literal a theme
    // switch cannot move. `heat` and `severity` are nested maps of the same.
    const flat = Object.values(theme.colors ?? {}).flatMap((value) =>
      typeof value === "object" && value !== null ? Object.values(value as Record<string, string>) : [value],
    );
    expect(flat.length).toBeGreaterThan(Object.keys(theme.colors ?? {}).length);
    for (const value of flat) {
      expect(String(value)).toMatch(/^var\(--[\w-]+\)$/);
    }
  });

  it("feeds the kernel frame the same values", () => {
    const frame = kernelThemeTokens();
    // The shell's accent and the conversation's send button are one colour, or
    // the two halves of the window are visibly two products — and that colour
    // is EviMed's live brand blue, because the platform has users and a logo.
    expect(frame["--dsw-alias-button-info-fill"].light).toBe("#0a5dc1");
    expect(frame["--dsw-alias-bg-base"]).toEqual({ light: "#fafbfc", dark: "#0f1318" });
    expect(frame["--dsw-font-family"].light).toBe(FONT_STACKS.sans);
    // The conversation is never set in the serif: the frame takes the sans
    // stack and the serif never crosses into it.
    expect(frame["--dsw-font-family"].light).not.toMatch(SERIF_FACES);
    // The two sidebars are the same grey.
    expect(frame["--dsw-specific-sidebar-fill"].light).toBe("#f5f7f9");
    for (const [name, pair] of Object.entries(frame)) {
      expect(name, "a frame token must be a --dsw-* custom property").toMatch(/^--dsw-/);
      expect(typeof pair.light, `${name}.light`).toBe("string");
      expect(typeof pair.dark, `${name}.dark`).toBe("string");
    }
  });
});

describe("the type scale is closed, and the serif is confined", () => {
  // Nine sizes, up from five. The five-rung scale of 2026-09-23 cured a page
  // carrying eleven size x weight pairs and starved a dashboard: with 24 px as
  // the ceiling a KPI could not out-shout its own label. 13 returns for dense
  // controls, 32 and 40 for metrics, and 18 for a section heading.
  it("uses exactly the nine agreed sizes", () => {
    const used = [...new Set(Object.values(TYPE_SCALE).map((rung) => rung.size))].sort((a, b) => a - b);
    expect(TYPE_SIZES).toEqual([12, 13, 14, 16, 18, 20, 24, 32, 40]);
    for (const size of used) expect(TYPE_SIZES).toContain(size);
  });

  it("confines the serif to the three brand moments and keeps it out of the sans stack", () => {
    expect(FONT_STACKS.sans).not.toMatch(SERIF_FACES);
    expect(FONT_STACKS.sans.replace(/sans-serif/g, "")).not.toMatch(/\bserif\b/);
    expect(FONT_STACKS.serif).toMatch(SERIF_FACES);
    expect(theme.fontFamily?.serif).toBe(FONT_STACKS.serif);
    // Exactly three rungs may ask for it: the wordmark, the home headline and
    // a document title. A serif on a button reads as an old intranet.
    const serifRungs = Object.entries(TYPE_SCALE)
      .filter(([, rung]) => rung.family === "serif")
      .map(([name]) => name)
      .sort();
    expect(serifRungs).toEqual(["doc-title", "hero", "wordmark"]);
  });

  it("ships the latin serif only — a CJK serif webfont would be megabytes", () => {
    const pkg = JSON.parse(readFileSync(join(SRC, "../package.json"), "utf8")) as {
      dependencies: Record<string, string>;
    };
    const serifFonts = Object.keys(pkg.dependencies).filter((name) => /serif/i.test(name));
    expect(serifFonts).toEqual(["@fontsource/source-serif-4"]);
    const css = readFileSync(INDEX_CSS, "utf8");
    // Two cuts, no more, and nothing that pulls a CJK serif over the wire.
    expect(css.match(/@import "@fontsource\/source-serif-4\/\d+\.css";/g)).toHaveLength(2);
    expect(css).not.toMatch(/@import .*(han-serif|noto-serif|songti)/i);
  });
});

describe("the table keeps its own promises", () => {
  it("measures every contrast pair it claims, in both themes", () => {
    // The `note` fields used to be typed and went stale silently. They are
    // recomputed now, and a shortfall fails the build before it fails a reader.
    expect(contrastFailures()).toEqual([]);
  });
});

describe("colour lives in the token file", () => {
  it("finds no hex literal in a component outside the named exceptions", () => {
    const files = sourceFiles(SRC);
    // Prove the walk walked before trusting what it did not find: a broken
    // walk that scans nothing passes forever.
    expect(files.length).toBeGreaterThan(100);
    expect(files.map((file) => relative(SRC, file))).toContain("index.css");
    expect(HEX.test(readFileSync(INDEX_CSS, "utf8"))).toBe(true);

    const offenders: string[] = [];
    for (const file of files) {
      const name = relative(SRC, file).split("\\").join("/");
      if (ALLOWED[name]) continue;
      readFileSync(file, "utf8").split("\n").forEach((line, index) => {
        const trimmed = line.trim();
        // Comments may name a colour to explain a decision.
        if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) return;
        if (HEX.test(line)) offenders.push(`${name}:${index + 1}  ${trimmed.slice(0, 120)}`);
      });
    }
    expect(offenders, "move these colours into packages/design-tokens/src/index.mjs, or name the exception above with its reason").toEqual([]);
  });

  it("keeps every named exception honest", () => {
    // An exception for a file that no longer has a hex literal is a hole
    // waiting for the next one.
    for (const name of Object.keys(ALLOWED)) {
      expect(HEX.test(readFileSync(join(SRC, name), "utf8")), `${name} no longer needs its exception`).toBe(true);
    }
  });
});
