#!/usr/bin/env python3
"""One synthetic-document diagnostic; mounted into, never baked into, the image."""

from __future__ import annotations

import base64
import hashlib
from importlib.metadata import version
import json
import os
from pathlib import Path
import re
import signal
import subprocess
import sys
import threading
import time


FIXTURE_SHA256 = "89e69db05a932ffe52fa66801392bd1b1fc9cb8842af0199b145e32e00d61f78"
FIXTURE_TEXT = "Evidence parser ingestion fixture. Group-only handoff verified."
# Generated by parserSmokePdf() at 16396a18, not a second PDF implementation.
FIXTURE_BASE64 = (
    "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA1IDAgUiA+PiA+PiAvQ29udGVudHMgNCAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA5NSA+PgpzdHJlYW0KQlQgL0YxIDE0IFRmIDcyIDcyMCBUZCAoRXZpZGVuY2UgcGFyc2VyIGluZ2VzdGlvbiBmaXh0dXJlLiBHcm91cC1vbmx5IGhhbmRvZmYgdmVyaWZpZWQuKSBUaiBFVAplbmRzdHJlYW0KZW5kb2JqCjUgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iagp4cmVmCjAgNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMDA1OCAwMDAwMCBuIAowMDAwMDAwMTE1IDAwMDAwIG4gCjAwMDAwMDAyNDEgMDAwMDAgbiAKMDAwMDAwMDM4NSAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDYgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjQ1NQolJUVPRgo="
)
TIMEOUT_SECONDS = 165
CGROUP_FILES = (
    "memory.current", "memory.peak", "memory.max", "memory.swap.max",
    "memory.events", "memory.oom.group", "cpu.max", "pids.max",
)
DETAIL_PATTERN = re.compile(
    r"traceback|\bfile [\"']|error|exception|warning|permission|read.only|"
    r"not found|no such|cannot|failed|killed|out of memory|segmentation|abort",
    re.IGNORECASE,
)


def emit(stage: str, **details: object) -> None:
    print(json.dumps({"stage": stage, **details}, sort_keys=True), flush=True)


def redact(value: str) -> str:
    value = re.sub(r"\x1b\[[0-?]*[ -/]*[@-~]", "", value)
    value = re.sub(r"(?i)\b(?:https?|wss?|s3)://[^\s\"'<>]+", "[redacted-url]", value)
    value = re.sub(r"(?i)\bBearer\s+\S+", "Bearer [redacted]", value)
    value = re.sub(
        r"(?i)([\w-]{0,128}(?:token|password|secret|api[_-]?key|authorization)[\w-]{0,128}[\"']?\s*[:=]\s*)[^,;\n]+",
        r"\1[redacted]", value,
    )
    value = re.sub(r"\b(?:sk-[A-Za-z0-9_-]+|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)\b", "[redacted]", value)
    return "".join(char for char in value if char.isprintable() or char in "\n\t")


def stream_summary(value: bytes | None) -> dict[str, object]:
    data = value or b""
    # Only error/exception/stack lines from the bounded tail are published.
    lines = [redact(line)[:500] for line in data[-32768:].decode("utf-8", errors="replace").splitlines()
             if DETAIL_PATTERN.search(line)]
    details = "\n".join(lines[-24:])[-8192:]
    return {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(),
            "diagnosticLines": details, "tailBytesExamined": min(len(data), 32768)}


def parse_counter_text(value: str) -> int | str | dict[str, int]:
    value = value.strip()
    if value.isdecimal():
        return int(value)
    if "\n" in value:
        return {key: int(count) for key, count in (line.split() for line in value.splitlines())}
    return value


def resources() -> dict[str, object]:
    result: dict[str, object] = {}
    for name in CGROUP_FILES:
        try:
            result[name] = parse_counter_text((Path("/sys/fs/cgroup") / name).read_text())
        except (OSError, ValueError) as error:
            result[name] = {"unavailable": type(error).__name__}
    return result


def check_fixture(value: bytes) -> None:
    if len(value) != 638 or hashlib.sha256(value).hexdigest() != FIXTURE_SHA256:
        raise ValueError("Only the exact canonical synthetic PDF is permitted.")


def wall_deadline(_signum: int, _frame: object) -> None:
    raise TimeoutError("Diagnostic wall deadline reached.")


def main() -> int:
    if len(sys.argv) == 3 and sys.argv[1] == "--write-fixture":
        fixture = base64.b64decode(FIXTURE_BASE64, validate=True)
        check_fixture(fixture)
        destination = Path(sys.argv[2])
        with destination.open("xb") as stream:
            stream.write(fixture)
        destination.chmod(0o444)
        emit("fixture_written", bytes=len(fixture), sha256=FIXTURE_SHA256)
        return 0

    started = time.monotonic()
    signal.signal(signal.SIGALRM, wall_deadline)
    signal.alarm(170)
    stopped = threading.Event()
    before = resources()
    emit("diagnostic_start", sourceSha256=FIXTURE_SHA256, diagnosticTimeoutSeconds=TIMEOUT_SECONDS,
         wallDeadlineSeconds=170, resources=before)

    def sample_resources() -> None:
        while not stopped.wait(5):
            emit("resource_sample", elapsedSeconds=round(time.monotonic() - started, 2), resources=resources())

    sampler = threading.Thread(target=sample_resources, daemon=True)
    sampler.start()
    try:
        fixture = Path("/data/fixture.pdf")
        check_fixture(fixture.read_bytes())
        assert os.getuid() == 1000 and os.getgid() == 1000
        assert os.environ.get("MINERU_MODEL_SOURCE") == "local"
        assert os.environ.get("CUDA_VISIBLE_DEVICES") == ""
        assert os.statvfs("/").f_flag & os.ST_RDONLY
        assert before["memory.max"] == 6 * 1024 ** 3
        assert before["pids.max"] == 512
        quota, period = str(before["cpu.max"]).split()
        assert int(quota) == 4 * int(period)
        status = Path("/proc/self/status").read_text()
        assert re.search(r"CapEff:\s+0+\n", status) and re.search(r"CapBnd:\s+0+\n", status)
        assert re.search(r"NoNewPrivs:\s+1\n", status)

        sys.path.insert(0, "/app")
        import parser_service

        assert Path(parser_service.__file__).resolve() == Path("/app/parser_service.py")
        assert parser_service.MINERU_VERSION == "3.4.5"
        installed_version = version("mineru")
        assert installed_version == "3.4.5"
        emit("installed_parser", version=installed_version)
        original_run = parser_service.subprocess.run

        def observed_run(*args: object, **kwargs: object) -> subprocess.CompletedProcess:
            # Forward the exact production argv and kwargs, including its environment.
            began = time.monotonic()
            try:
                result = original_run(*args, **kwargs)
            except subprocess.TimeoutExpired as error:
                emit("mineru_subprocess", timeout=True, returnCode=None,
                     elapsedSeconds=round(time.monotonic() - began, 2),
                     stdout=stream_summary(error.stdout), stderr=stream_summary(error.stderr))
                raise
            emit("mineru_subprocess", timeout=False, returnCode=result.returncode,
                 elapsedSeconds=round(time.monotonic() - began, 2),
                 stdout=stream_summary(result.stdout), stderr=stream_summary(result.stderr))
            return result

        parser_service.subprocess.run = observed_run
        try:
            result = parser_service.parse_document(
                parser_service.ParseRequest(path=str(fixture), mimeType="application/pdf",
                                            sha256=FIXTURE_SHA256, sourceId=f"src_{FIXTURE_SHA256[:32]}"),
                data_root=Path("/data"), timeout=TIMEOUT_SECONDS,
            )
        finally:
            parser_service.subprocess.run = original_run
        text = result["text"].encode("utf-8")
        verified = (result["extractor"] == {"name": "mineru", "version": "3.4.5", "parser": "mineru"}
                    and FIXTURE_TEXT in " ".join(result["text"].split())
                    and len(result["units"]) == 1 and result["units"][0]["unitType"] == "page"
                    and result["units"][0]["status"] == "extracted" and bool(result["units"][0]["itemIds"]))
        emit("production_result", verified=verified, textBytes=len(text),
             textSha256=hashlib.sha256(text).hexdigest(), units=len(result["units"]), facts=len(result["facts"]))
        return 0 if verified else 1
    except Exception as error:
        emit("diagnostic_exception", exceptionType=type(error).__name__,
             details=stream_summary(str(error).encode("utf-8")))
        return 1
    finally:
        stopped.set()
        emit("diagnostic_finish", elapsedSeconds=round(time.monotonic() - started, 2), resources=resources())
        signal.alarm(0)


if __name__ == "__main__":
    raise SystemExit(main())
