import {render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router';
import {beforeEach,expect,it,vi} from 'vitest';
import userEvent from '@testing-library/user-event';
import {WeeklyView} from './WeeklyView';
const client=vi.hoisted(()=>({listFrontierWeeklies:vi.fn(),fetchFrontierWeekly:vi.fn()}));
vi.mock('@/lib/frontierClient',async original=>({...await original<typeof import('@/lib/frontierClient')>(),...client}));
beforeEach(()=>{vi.resetAllMocks();client.listFrontierWeeklies.mockResolvedValue([{weekStart:'2026-09-21',weekEnd:'2026-09-27',title:null,itemCount:0,generatedAt:null}]);client.fetchFrontierWeekly.mockResolvedValue({day:'2026-09-21',weekStart:'2026-09-21',weekEnd:'2026-09-27',lead:null,sections:[],safety:[],aiMinute:null,markdown:'Weekly',itemCount:0,readingMinutes:1,previousDay:'2026-09-14',nextDay:null});});
it('shows a calendar range, previous issue navigation and reload-selected week',async()=>{const onWeek=vi.fn();render(<MemoryRouter><WeeklyView week="2026-09-21" onWeek={onWeek}/></MemoryRouter>);await screen.findByText(/9月21日.*9月27日/);expect(client.fetchFrontierWeekly).toHaveBeenCalledWith('2026-09-21');await userEvent.click(screen.getByRole('button',{name:'‹ 前一期'}));expect(onWeek).toHaveBeenCalledWith('2026-09-14');});
it('empty archive is a calm weekly empty state',async()=>{client.listFrontierWeeklies.mockResolvedValue([]);render(<MemoryRouter><WeeklyView week={null} onWeek={()=>{}}/></MemoryRouter>);await waitFor(()=>expect(screen.getByText('暂无周报')).toBeInTheDocument());expect(client.fetchFrontierWeekly).not.toHaveBeenCalled();});
it('failed archive is retryable',async()=>{client.listFrontierWeeklies.mockRejectedValueOnce(new Error('offline'));render(<MemoryRouter><WeeklyView week={null} onWeek={()=>{}}/></MemoryRouter>);await userEvent.click(await screen.findByRole('button',{name:'重试'}));await screen.findByText(/9月21日.*9月27日/);});
