/**
 * The CSS artifacts: the block that lives inside `apps/web/src/index.css`, and
 * the standalone `dist/tokens.css` the Vue shell links.
 *
 * CSS cannot import a JavaScript module, so the token table reaches a
 * stylesheet as generated bytes. Deterministic on purpose: the same module
 * produces the same bytes, which is what lets a test compare them.
 *
 * Since 2.1 the block carries rules as well as custom properties, each one a
 * decision the table owns rather than a stylesheet's: the punctuation face
 * (`@font-face`), the serif bound to the three rungs that may wear it, the
 * English stack, the reduced-motion values, and the forced-colours and
 * more-contrast layer (spec §10.9). Both shells therefore get them by linking
 * one file.
 *
 * @module @evimed/design-tokens/css
 */
import {
  BREAKPOINTS,
  CHART_COLORS,
  CHART_SERIES,
  CHART_STROKES,
  CJK_PUNCT_FACES,
  CJK_PUNCT_RANGE,
  COLOR_RAMPS,
  COLOR_ROLES_MORE_CONTRAST,
  COLOR_ROLE_ALIASES,
  COLOR_ROLES,
  CONTAINERS,
  CONTROL_HEIGHTS,
  DESIGN_TOKENS_VERSION,
  ELEVATION,
  FOCUS_RING,
  FONT_STACKS,
  FONT_STACKS_EN,
  ICON_STROKE,
  MOTION,
  MOTION_DISTANCE,
  OPACITY,
  RADII,
  SPACE,
  STUDY_TYPE_BADGES,
  TOAST_DURATIONS,
  TOOLTIP_DELAYS,
  TYPE_SCALE,
  Z_INDEX,
  rem,
  remLineHeight,
  resolveColor,
} from './index.mjs'

/** The markers `apps/web/src/index.css` carries around the generated block. */
export const DESIGN_TOKENS_CSS_BEGIN = '/* >>> generated from @evimed/design-tokens — run `pnpm tokens:css` <<< */'
/** @see DESIGN_TOKENS_CSS_BEGIN */
export const DESIGN_TOKENS_CSS_END = '/* >>> end generated <<< */'

/**
 * @param {string} name
 * @param {string} value
 * @param {string} [note]
 * @returns {string}
 */
function declaration(name, value, note) {
  return `  --${name}: ${value};${note ? ` /* ${note} */` : ''}`
}

/**
 * A role's CSS value: a `var()` back at the primitive when it references one,
 * so the generated file still reads as a ladder rather than as 70 hex codes.
 * @param {string} reference
 * @returns {string}
 */
function cssColorValue(reference) {
  if (reference.startsWith('#') || reference.includes('(')) return reference
  resolveColor(reference) // throws on an unknown reference
  return `var(--${reference})`
}

/** Kebab-case for a camelCase key: `formPrimary` → `form-primary`. */
const kebab = (/** @type {string} */ name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)

/**
 * Theme-independent declarations: type, geometry, motion, layers, data colour.
 * Shared by both CSS artifacts.
 * @returns {string[]}
 */
function staticDeclarations() {
  /** @type {string[]} */
  const lines = []
  lines.push(declaration('font-sans', FONT_STACKS.sans))
  lines.push(declaration('font-serif', FONT_STACKS.serif))
  lines.push(declaration('font-mono', FONT_STACKS.mono))
  lines.push(declaration('font-sans-en', FONT_STACKS_EN.sans))
  lines.push(declaration('font-serif-en', FONT_STACKS_EN.serif))
  // rem, so the browser's default font size is honoured (spec §5.2, §10.6).
  for (const [rung, { size, lineHeight }] of Object.entries(TYPE_SCALE)) {
    lines.push(declaration(`text-${rung}`, rem(size)))
    lines.push(declaration(`leading-${rung}`, remLineHeight(lineHeight)))
  }
  for (const step of SPACE.scale) lines.push(declaration(`space-${step}`, `${step}px`))
  for (const [name, value] of Object.entries(RADII)) lines.push(declaration(`radius-${name}`, `${value}px`))
  // Names are kebab-case (spec §11.2). 2.0 wrote the camelCase keys as they
  // were (`--height-formPrimary`); a published name is never removed in a
  // minor version, so each survives as an alias of its kebab-case successor.
  for (const [prefix, table] of /** @type {const} */ ([['height', CONTROL_HEIGHTS], ['width', CONTAINERS]])) {
    for (const [name, value] of Object.entries(table)) {
      lines.push(declaration(`${prefix}-${kebab(name)}`, `${value}px`))
      if (kebab(name) !== name) {
        lines.push(declaration(`${prefix}-${name}`, `var(--${prefix}-${kebab(name)})`, `retired name of --${prefix}-${kebab(name)}`))
      }
    }
  }
  // Read by script, never by a media query (custom properties cannot be).
  for (const [name, value] of Object.entries(BREAKPOINTS)) lines.push(declaration(`breakpoint-${name}`, `${value}px`))
  lines.push(declaration('icon-stroke', String(ICON_STROKE)))
  lines.push(declaration('focus-ring-width', `${FOCUS_RING.width}px`))
  lines.push(declaration('focus-ring-offset', `${FOCUS_RING.offset}px`))
  for (const [name, value] of Object.entries(Z_INDEX)) lines.push(declaration(`z-${name}`, String(value)))
  for (const [name, value] of Object.entries(OPACITY)) lines.push(declaration(`opacity-${name}`, String(value)))
  for (const level of /** @type {const} */ (['e1', 'e2', 'e3'])) lines.push(declaration(`shadow-${level}`, ELEVATION[level]))
  lines.push(declaration('shadow-pop', ELEVATION.e2, 'retired name of --shadow-e2'))
  lines.push(declaration('shadow-modal', ELEVATION.e3, 'retired name of --shadow-e3'))
  lines.push(declaration('dur-fast', MOTION.fast))
  lines.push(declaration('dur-base', MOTION.base))
  lines.push(declaration('dur-slow', MOTION.slow))
  lines.push(declaration('ease-standard', MOTION.easeStandard))
  lines.push(declaration('ease-exit', MOTION.easeExit))
  for (const [name, value] of Object.entries(MOTION_DISTANCE)) lines.push(declaration(`motion-${name}`, `${value}px`))
  lines.push(declaration('tooltip-show-delay', `${TOOLTIP_DELAYS.show}ms`))
  lines.push(declaration('tooltip-hide-delay', `${TOOLTIP_DELAYS.hide}ms`))
  // An error has no duration: it stays until it is closed.
  lines.push(declaration('toast-success', `${TOAST_DURATIONS.success}ms`))
  lines.push(declaration('toast-action', `${TOAST_DURATIONS.action}ms`))
  lines.push(declaration('chart-own', CHART_COLORS.own))
  CHART_COLORS.rivals.forEach((value, index) => lines.push(declaration(`chart-rival-${index + 1}`, value)))
  lines.push(declaration('chart-line', `${CHART_STROKES.line}px`))
  lines.push(declaration('chart-line-own', `${CHART_STROKES.own}px`))
  lines.push(declaration('chart-line-other', `${CHART_STROKES.other}px`))
  lines.push(declaration('chart-marker', `${CHART_STROKES.marker}px`))
  CHART_COLORS.heat.forEach((value, index) => lines.push(declaration(`heat-${index}`, value)))
  CHART_COLORS.diverging.forEach((value, index) => lines.push(declaration(`diverging-${index}`, value)))
  lines.push(declaration('chart-missing', CHART_COLORS.missing))
  for (const [level, value] of Object.entries(CHART_COLORS.severity)) lines.push(declaration(`severity-${level}`, value))
  for (const [kind, { fg, bg }] of Object.entries(STUDY_TYPE_BADGES)) {
    lines.push(declaration(`study-${kind}-fg`, fg))
    lines.push(declaration(`study-${kind}-bg`, bg))
  }
  return lines
}

/**
 * The theme layers, both schemes.
 * @returns {string[]}
 */
function themeDeclarations() {
  /** @type {string[]} */
  const lines = []
  for (const scheme of /** @type {const} */ (['light', 'dark'])) {
    lines.push(scheme === 'light' ? ':root,\n[data-theme="light"] {' : '[data-theme="dark"] {')
    // Native controls — scrollbars, a select's list, date pickers — draw in
    // the same scheme as the tokens around them.
    lines.push(`  color-scheme: ${scheme};`)
    for (const [role, entry] of Object.entries(COLOR_ROLES)) {
      lines.push(declaration(role, cssColorValue(entry[scheme]), scheme === 'light' ? entry.note : undefined))
    }
    for (const [alias, role] of Object.entries(COLOR_ROLE_ALIASES)) {
      lines.push(declaration(alias, `var(--${role})`, scheme === 'light' ? `retired name of --${role}` : undefined))
    }
    CHART_SERIES[scheme].forEach((value, index) => lines.push(declaration(`series-${index + 1}`, value)))
    lines.push('}')
    lines.push('')
  }
  return lines
}

/**
 * The punctuation face, one `@font-face` per family and weight, from the
 * reader's own system fonts (see `CJK_PUNCT_FACES`).
 * @returns {string[]}
 */
function fontFaces() {
  /** @type {string[]} */
  const lines = []
  for (const face of CJK_PUNCT_FACES) {
    lines.push('@font-face {')
    lines.push(`  font-family: "${face.family}";`)
    lines.push(`  font-weight: ${face.weight};`)
    lines.push(`  src: ${face.local.map((name) => `local("${name}")`).join(', ')};`)
    lines.push(`  unicode-range: ${CJK_PUNCT_RANGE};`)
    lines.push('}')
  }
  return lines
}

/**
 * The punctuation face alone, as a stylesheet: for a document that takes the
 * font stack but not this file — the kernel frame, whose theme body injects it
 * so `--dsw-font-family`'s first name resolves there too.
 * @returns {string}
 */
export function cjkPunctFontFaceCss() {
  return `${fontFaces().join('\n')}\n`
}

/**
 * Rules the table owns: the serif bound to the rungs that may wear it, the
 * English stack, and the reduced-motion values.
 * @returns {string[]}
 */
function typeAndMotionRules() {
  const serifRungs = Object.entries(TYPE_SCALE)
    .filter(([, rung]) => rung.family === 'serif')
    .map(([name]) => `.text-${name}`)
  return [
    '/* The serif belongs to three rungs and nothing else (spec §3.4): the rung',
    '   carries its family, so a page never names the serif itself. */',
    `${serifRungs.join(',\n')} {`,
    '  font-family: var(--font-serif);',
    '}',
    '',
    '/* Text marked English keeps its Latin quotes and dashes: the stacks without',
    '   the punctuation face. Zero specificity, so a mono class still wins. */',
    ':where([lang|="en"]) {',
    '  font-family: var(--font-sans-en);',
    '}',
    `:where([lang|="en"]):where(${serifRungs.join(', ')}) {`,
    '  font-family: var(--font-serif-en);',
    '}',
    '',
    '/* Reduced motion (spec §9.5): no layer travels, and no fade is longer than',
    '   the fast step. Opacity and colour still change, so a change is still seen. */',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    '    --dur-base: var(--dur-fast);',
    '    --dur-slow: var(--dur-fast);',
    ...Object.keys(MOTION_DISTANCE).map((name) => `    --motion-${name}: 0px;`),
    '  }',
    '}',
  ]
}

/**
 * The accessibility layer (spec §10.9): what forced-colours mode takes away,
 * put back; and what `prefers-contrast: more` makes stronger.
 *
 * Forced colours remove every box-shadow and every background colour a page
 * sets. Three things in the two shells were drawn with exactly those: Element
 * Plus's input and select edges and focus (box-shadows), a floating layer's
 * edge (half of it a shadow), and "selected / current / pressed" (a fill). A
 * focus ring drawn as an outline survives, and becomes the system highlight.
 *
 * @returns {string[]}
 */
function accessibilityLayer() {
  /** @type {string[]} */
  const more = []
  for (const scheme of /** @type {const} */ (['light', 'dark'])) {
    // `html` and `:not()` lift these above the theme blocks' own specificity,
    // wherever in the cascade this block ends up.
    more.push(scheme === 'light' ? '  html:not([data-theme="dark"]) {' : '  html[data-theme="dark"] {')
    for (const [role, entry] of Object.entries(COLOR_ROLES_MORE_CONTRAST)) {
      more.push(`  ${declaration(role, cssColorValue(entry[scheme]))}`)
    }
    more.push('  }')
  }
  return [
    '/* Forced colours (Windows contrast themes): shadows and fills are removed, so',
    '   everything that was drawn with one gets a line (spec §10.9). */',
    '@media (forced-colors: active) {',
    '  :focus-visible {',
    `    outline: var(--focus-ring-width) solid Highlight;`,
    `    outline-offset: var(--focus-ring-offset);`,
    '  }',
    '  /* Element Plus draws an input\'s and a select\'s edge and focus as shadows. */',
    '  .el-input__wrapper,',
    '  .el-textarea__inner,',
    '  .el-select__wrapper {',
    '    border: 1px solid ButtonBorder;',
    '  }',
    '  .el-input__wrapper.is-focus,',
    '  .el-textarea__inner:focus,',
    '  .el-select__wrapper.is-focused {',
    '    outline: var(--focus-ring-width) solid Highlight;',
    '  }',
    '  /* A floating layer lost its shadow, which was half its edge. */',
    '  [role="dialog"],',
    '  [role="alertdialog"],',
    '  [role="menu"],',
    '  [role="listbox"],',
    '  [role="tooltip"],',
    '  .el-popper,',
    '  .el-dialog,',
    '  .el-drawer,',
    '  .el-message,',
    '  .el-message-box {',
    '    border: 1px solid CanvasText;',
    '  }',
    '  /* Selected, current and pressed lost their fill: say it with a line. */',
    '  [aria-current="page"],',
    '  [aria-current="true"],',
    '  [aria-pressed="true"],',
    '  [role="radio"][aria-checked="true"],',
    '  [role="option"][aria-selected="true"],',
    '  .el-menu-item.is-active,',
    '  .el-radio-button.is-active .el-radio-button__inner {',
    '    text-decoration: underline 2px;',
    '    text-underline-offset: 4px;',
    '  }',
    '  /* Colour that is the data (a legend swatch, a palette) keeps its colour. */',
    '  [data-forced-colors="preserve"] {',
    '    forced-color-adjust: none;',
    '  }',
    '}',
    '',
    '/* More contrast: secondary text and every rule one step towards the text',
    '   colour (COLOR_ROLES_MORE_CONTRAST, measured like the rest). */',
    '@media (prefers-contrast: more) {',
    ...more,
    '}',
  ]
}

/**
 * The block that lives in `apps/web/src/index.css`, markers included.
 * @returns {string}
 */
export function designTokensCss() {
  /** @type {string[]} */
  const lines = []
  lines.push(DESIGN_TOKENS_CSS_BEGIN)
  lines.push('/* The punctuation face: “quotes” and …… in the reader\'s own Chinese face,')
  lines.push('   ahead of Inter in the stack (spec §5.1). Local fonts only. */')
  lines.push(...fontFaces())
  lines.push('')
  lines.push('/* Primitive ramps. Theme-independent: a role below points at a step, and')
  lines.push('   the dark theme points the same role at a different step rather than')
  lines.push('   inverting a colour. See packages/design-tokens/src/index.mjs. */')
  lines.push(':root {')
  for (const [ramp, steps] of Object.entries(COLOR_RAMPS)) {
    for (const [step, value] of Object.entries(steps)) lines.push(declaration(`${ramp}-${step}`, value))
  }
  lines.push('}')
  lines.push('')
  lines.push('/* The semantic layer. Contrast notes are measured by')
  lines.push('   packages/design-tokens/src/contrast.mjs at build time, not estimated. */')
  lines.push(...themeDeclarations())
  lines.push('/* Type, geometry, layers, motion and data colour: theme-independent, and')
  lines.push("   readable from a stylesheet Tailwind does not compile (the kernel frame's own). */")
  lines.push(':root {')
  lines.push(...staticDeclarations())
  lines.push('}')
  lines.push('')
  lines.push(...typeAndMotionRules())
  lines.push('')
  lines.push(...accessibilityLayer())
  lines.push(DESIGN_TOKENS_CSS_END)
  return lines.join('\n')
}

/**
 * `dist/tokens.css` — the same table as a standalone stylesheet, for a front
 * end that is not this repository's (the Vue shell links this file directly).
 * @returns {string}
 */
export function standaloneTokensCss() {
  const body = designTokensCss()
    .replace(DESIGN_TOKENS_CSS_BEGIN, '')
    .replace(DESIGN_TOKENS_CSS_END, '')
    .trim()
  return [
    `/* EviMed 设计语言 ${DESIGN_TOKENS_VERSION} — generated by @evimed/design-tokens. Do not edit. */`,
    '/* Regenerate with `pnpm --filter @evimed/design-tokens build`. */',
    '',
    body,
    '',
  ].join('\n')
}
