/**
 * The CSS artifacts: the block that lives inside `apps/web/src/index.css`, and
 * the standalone `dist/tokens.css` the Vue shell links.
 *
 * CSS cannot import a JavaScript module, so the token table reaches a
 * stylesheet as generated bytes. Deterministic on purpose: the same module
 * produces the same bytes, which is what lets a test compare them.
 *
 * @module @evimed/design-tokens/css
 */
import {
  CHART_COLORS,
  CHART_SERIES,
  COLOR_RAMPS,
  COLOR_ROLE_ALIASES,
  COLOR_ROLES,
  CONTAINERS,
  CONTROL_HEIGHTS,
  DESIGN_TOKENS_VERSION,
  ELEVATION,
  FONT_STACKS,
  ICON_STROKE,
  MOTION,
  RADII,
  SPACE,
  STUDY_TYPE_BADGES,
  TYPE_SCALE,
  resolveColor,
} from './index.mjs'

/** The markers `apps/web/src/index.css` carries around the generated block. */
export const DESIGN_TOKENS_CSS_BEGIN = '/* >>> generated from @evimed/design-tokens — run `pnpm tokens:css` <<< */'
/** @see DESIGN_TOKENS_CSS_BEGIN */
export const DESIGN_TOKENS_CSS_END = '/* >>> end generated <<< */'

/**
 * @param {string} name
 * @param {string} value
 * @param {string} [note]
 * @returns {string}
 */
function declaration(name, value, note) {
  return `  --${name}: ${value};${note ? ` /* ${note} */` : ''}`
}

/**
 * A role's CSS value: a `var()` back at the primitive when it references one,
 * so the generated file still reads as a ladder rather than as 70 hex codes.
 * @param {string} reference
 * @returns {string}
 */
function cssColorValue(reference) {
  if (reference.startsWith('#') || reference.includes('(')) return reference
  resolveColor(reference) // throws on an unknown reference
  return `var(--${reference})`
}

/**
 * Theme-independent declarations: type, geometry, motion, data colour. Shared
 * by both CSS artifacts.
 * @returns {string[]}
 */
function staticDeclarations() {
  /** @type {string[]} */
  const lines = []
  lines.push(declaration('font-sans', FONT_STACKS.sans))
  lines.push(declaration('font-serif', FONT_STACKS.serif))
  lines.push(declaration('font-mono', FONT_STACKS.mono))
  for (const [rung, { size, lineHeight }] of Object.entries(TYPE_SCALE)) {
    lines.push(declaration(`text-${rung}`, `${size}px`))
    lines.push(declaration(`leading-${rung}`, lineHeight))
  }
  for (const step of SPACE.scale) lines.push(declaration(`space-${step}`, `${step}px`))
  for (const [name, value] of Object.entries(RADII)) lines.push(declaration(`radius-${name}`, `${value}px`))
  for (const [name, value] of Object.entries(CONTROL_HEIGHTS)) lines.push(declaration(`height-${name}`, `${value}px`))
  for (const [name, value] of Object.entries(CONTAINERS)) lines.push(declaration(`width-${name}`, `${value}px`))
  lines.push(declaration('icon-stroke', String(ICON_STROKE)))
  for (const level of /** @type {const} */ (['e1', 'e2', 'e3'])) lines.push(declaration(`shadow-${level}`, ELEVATION[level]))
  lines.push(declaration('shadow-pop', ELEVATION.e2, 'retired name of --shadow-e2'))
  lines.push(declaration('shadow-modal', ELEVATION.e3, 'retired name of --shadow-e3'))
  lines.push(declaration('dur-fast', MOTION.fast))
  lines.push(declaration('dur-base', MOTION.base))
  lines.push(declaration('dur-slow', MOTION.slow))
  lines.push(declaration('ease-standard', MOTION.easeStandard))
  lines.push(declaration('chart-own', CHART_COLORS.own))
  CHART_COLORS.rivals.forEach((value, index) => lines.push(declaration(`chart-rival-${index + 1}`, value)))
  CHART_COLORS.heat.forEach((value, index) => lines.push(declaration(`heat-${index}`, value)))
  for (const [level, value] of Object.entries(CHART_COLORS.severity)) lines.push(declaration(`severity-${level}`, value))
  for (const [kind, { fg, bg }] of Object.entries(STUDY_TYPE_BADGES)) {
    lines.push(declaration(`study-${kind}-fg`, fg))
    lines.push(declaration(`study-${kind}-bg`, bg))
  }
  return lines
}

/**
 * The theme layers, both schemes.
 * @returns {string[]}
 */
function themeDeclarations() {
  /** @type {string[]} */
  const lines = []
  for (const scheme of /** @type {const} */ (['light', 'dark'])) {
    lines.push(scheme === 'light' ? ':root,\n[data-theme="light"] {' : '[data-theme="dark"] {')
    // Native controls — scrollbars, a select's list, date pickers — draw in
    // the same scheme as the tokens around them.
    lines.push(`  color-scheme: ${scheme};`)
    for (const [role, entry] of Object.entries(COLOR_ROLES)) {
      lines.push(declaration(role, cssColorValue(entry[scheme]), scheme === 'light' ? entry.note : undefined))
    }
    for (const [alias, role] of Object.entries(COLOR_ROLE_ALIASES)) {
      lines.push(declaration(alias, `var(--${role})`, scheme === 'light' ? `retired name of --${role}` : undefined))
    }
    CHART_SERIES[scheme].forEach((value, index) => lines.push(declaration(`series-${index + 1}`, value)))
    lines.push('}')
    lines.push('')
  }
  return lines
}

/**
 * The block that lives in `apps/web/src/index.css`, markers included.
 * @returns {string}
 */
export function designTokensCss() {
  /** @type {string[]} */
  const lines = []
  lines.push(DESIGN_TOKENS_CSS_BEGIN)
  lines.push('/* Primitive ramps. Theme-independent: a role below points at a step, and')
  lines.push('   the dark theme points the same role at a different step rather than')
  lines.push('   inverting a colour. See packages/design-tokens/src/index.mjs. */')
  lines.push(':root {')
  for (const [ramp, steps] of Object.entries(COLOR_RAMPS)) {
    for (const [step, value] of Object.entries(steps)) lines.push(declaration(`${ramp}-${step}`, value))
  }
  lines.push('}')
  lines.push('')
  lines.push('/* The semantic layer. Contrast notes are measured by')
  lines.push('   packages/design-tokens/src/contrast.mjs at build time, not estimated. */')
  lines.push(...themeDeclarations())
  lines.push('/* Type, geometry, motion and data colour: theme-independent, and readable')
  lines.push("   from a stylesheet Tailwind does not compile (the kernel frame's own). */")
  lines.push(':root {')
  lines.push(...staticDeclarations())
  lines.push('}')
  lines.push(DESIGN_TOKENS_CSS_END)
  return lines.join('\n')
}

/**
 * `dist/tokens.css` — the same table as a standalone stylesheet, for a front
 * end that is not this repository's (the Vue shell links this file directly).
 * @returns {string}
 */
export function standaloneTokensCss() {
  const body = designTokensCss()
    .replace(DESIGN_TOKENS_CSS_BEGIN, '')
    .replace(DESIGN_TOKENS_CSS_END, '')
    .trim()
  return [
    `/* EviMed 设计语言 ${DESIGN_TOKENS_VERSION} — generated by @evimed/design-tokens. Do not edit. */`,
    '/* Regenerate with `pnpm --filter @evimed/design-tokens build`. */',
    '',
    body,
    '',
  ].join('\n')
}
