server:
  port: ${SERVER_PORT:2089}

spring:
  application:
    name: evaluation
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  data:
    mongodb:
      uri: ${TEST_MONGODB_URI:mongodb://localhost:27017/evimed_test}
  elasticsearch:
    rest:
      uris: ${TEST_ELASTICSEARCH_URL:http://localhost:9200}
      username: ${TEST_ELASTICSEARCH_USERNAME:}
      password: ${TEST_ELASTICSEARCH_PASSWORD:}
      connection-timeout: 10000
      read-timeout: 120000
      max-connections: 20
      max-connections-per-route: 20
  redis:
    host: ${TEST_REDIS_HOST:localhost}
    port: ${TEST_REDIS_PORT:6379}
    database: ${TEST_REDIS_DATABASE:1}
    timeout: 2000
    password: ${TEST_REDIS_PASSWORD:}

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        ConnectTimeOut: 60000
        ReadTimeOut: 60000

eureka:
  client:
    enabled: false
