// A capability's preflight exists in four trees. They have to be the same file.
//
// The run-side preflight is what a skill tells a run to satisfy before it
// delivers, and that instruction is only honest while the preflight and the
// gate agree. They disagreed three times in production, each time costing a
// finished package, which is why the clinical gate now exists exactly once
// (clinicalEvidenceSingleImplementation.test.mjs holds that line). The
// preflights that remain have the same exposure one level down: the same
// script is copied into `capabilities/` (the manifest source), `capability-skills/`
// (the skill bodies), `runtime/skills/evimed/` (what the container mounts), and
// `packages/socket/capability-skills/` (what prepack ships in the npm tarball).
// Nothing enforced that the four copies match, so an edit to one of them would
// have shipped a run checking itself against rules the gate no longer holds —
// and it would have looked exactly like nothing having happened.
//
// This is a walk assertion, so it also has to prove it walked. A tree that
// yields no preflight at all, or no capability with more than one copy, is a
// broken scan reporting a clean tree, and fails as loudly as real drift.
import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

/**
 * The four trees a capability's scripts are copied into.
 *
 * `packages/socket/capability-skills/` is generated by the socket's prepack
 * (`cpSync` from `capability-skills/`) and is gitignored, so it is absent in a
 * fresh clone until a pack runs. Absent is fine — a copy that does not exist
 * cannot drift. Present and different is not fine: that is a stale tarball.
 */
const roots = Object.freeze([
  { dir: "capabilities", regenerate: null },
  { dir: "capability-skills", regenerate: null },
  { dir: "runtime/skills/evimed", regenerate: null },
  { dir: "packages/socket/capability-skills", regenerate: "pnpm --filter @evimed/dsh-socket prepack" },
]);

/** @param {string} dir @returns {Promise<string[]>} */
async function capabilityNames(dir) {
  const absolute = path.join(repoRoot, dir);
  let entries;
  try {
    entries = await readdir(absolute, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
}

/**
 * Every preflight in the four trees, keyed by capability.
 * @returns {Promise<Map<string, { root: string, relative: string, digest: string, bytes: number }[]>>}
 */
async function preflightCopies() {
  /** @type {Map<string, { root: string, relative: string, digest: string, bytes: number }[]>} */
  const byCapability = new Map();
  for (const root of roots) {
    for (const capability of await capabilityNames(root.dir)) {
      const relative = path.join(root.dir, capability, "scripts", "preflight.py");
      const absolute = path.join(repoRoot, relative);
      let info;
      try {
        info = await stat(absolute);
      } catch {
        continue;
      }
      if (!info.isFile()) continue;
      const bytes = await readFile(absolute);
      const copies = byCapability.get(capability) ?? [];
      copies.push({
        root: root.dir,
        relative,
        digest: createHash("sha256").update(bytes).digest("hex"),
        bytes: bytes.length,
      });
      byCapability.set(capability, copies);
    }
  }
  return byCapability;
}

test("every copy of a capability's preflight is the same file", async () => {
  const byCapability = await preflightCopies();

  // The scan proves it scanned, twice over. A walk that finds nothing is the
  // failure this test exists to catch, not evidence of a clean tree: rename
  // `scripts/` or `preflight.py`, move the capability trees, or point `repoRoot`
  // one directory wrong, and without these two the file reports success forever.
  const scanned = [...byCapability.values()].flat();
  assert.ok(
    scanned.length > 0,
    `no scripts/preflight.py found under any of ${roots.map((root) => root.dir).join(", ")} `
    + `(searched from ${repoRoot}); the walk is broken, not the tree clean`,
  );
  const duplicated = [...byCapability].filter(([, copies]) => copies.length > 1);
  assert.ok(
    duplicated.length > 0,
    `found ${scanned.length} preflight file(s) but no capability with more than one copy `
    + `(${scanned.map((copy) => copy.relative).join(", ")}); there is nothing here to pin, `
    + "so either the copies moved or this test no longer looks where they live",
  );

  const drifted = [];
  for (const [capability, copies] of duplicated) {
    const digests = new Set(copies.map((copy) => copy.digest));
    if (digests.size === 1) continue;
    const regenerate = copies
      .map((copy) => roots.find((root) => root.dir === copy.root)?.regenerate)
      .filter(Boolean);
    drifted.push(
      `${capability}: `
      + copies.map((copy) => `${copy.relative} (${copy.digest.slice(0, 12)}, ${copy.bytes} bytes)`).join(" vs ")
      + (regenerate.length ? ` — if only the generated copy differs, run: ${regenerate[0]}` : ""),
    );
  }
  assert.deepEqual(
    drifted,
    [],
    "a capability's preflight differs between its copies. The run is told to satisfy the preflight before "
    + "delivering, so a copy that says something different is a run checking itself against rules nobody else "
    + `holds. Change every copy together.\n${drifted.join("\n")}`,
  );
});
