/** Real ordinary-auth HTTP/server composition; native inventory and browser transport are explicit synthetic controls. */
import assert from 'node:assert/strict';import test from 'node:test';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createWebApiApp}from'../src/server.mjs';
test('managed open uses current native project inventory without requiring research metadata; later owned actions do not list again',{timeout:15000},async()=>{
 const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'evimed-browser-admit-')));let opens=0,lists=0,unavailable=false,replaceDuringList=false;let app;
 const browser={enabled:true,open:async()=>{opens++;return{id:'captured'};},snapshot:async()=>({sequence:0,state:{url:'about:blank'},frame:null}),closePage:async()=>({closed:true}),releaseFrame:async()=>{},closeOwner:async()=>{},closeProject:async()=>{},close:async()=>{},pause:async()=>{},start:()=>{}};
 try{
 app=createWebApiApp({dataDir:root,port:0,host:'127.0.0.1',stateStore:'file',devAuth:false,authMode:'local',selfRegistrationEnabled:true,runtimeMode:'mock',runtimeUiProxyEnabled:true,runtimeUiPublicOrigin:'http://127.0.0.1:18443',publicUrl:'http://127.0.0.1:18787',managedBrowserEnabled:true,managedBrowserService:browser,modelGatewaySigningSecret:'synthetic-owned-frame-signing-key',learningEnabled:false,autopilotEnabled:false});
 const address=await app.listen(0,'127.0.0.1'),base='http://127.0.0.1:'+address.port;
 const registration=await fetch(base+'/api/auth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'browser-owned',password:'Disposable scoped browser fixture only!'})});assert.equal(registration.status,201);const login=(await registration.json()).data,cookie=registration.headers.getSetCookie().map(value=>value.split(';')[0]).join('; '),project=await app.store.requireProject(await app.store.userById(login.user.id),'default');
 const runtime={modelGatewayTokenJti:'current-native-generation'};app.runtimeManager.runtimes.set(app.runtimeManager.key(project),runtime);
 app.runtimeManager.callKernel=async(actualRuntime,actualProject,method,args)=>{assert.equal(actualRuntime,runtime);assert.equal(actualProject.id,project.id);assert.equal(method,'session/list');assert.deepEqual(args,{_request:{}});lists++;if(unavailable)throw Error('Native inventory unavailable');if(replaceDuringList)app.runtimeManager.runtimes.set(app.runtimeManager.key(project),{modelGatewayTokenJti:'replacement'});return{items:[{sessionId:'native-owned'}]};};
 const issued=await fetch(base+'/api/runtime-ui/frames',{method:'POST',headers:{cookie,'x-open-science-csrf':login.csrfToken,'content-type':'application/json'},body:JSON.stringify({projectId:project.id})});assert.equal(issued.status,201);const frame=(await issued.json()).data,prefix=new URL(frame.frameUrl).pathname,frameCookie=issued.headers.getSetCookie().map(value=>value.split(';')[0]).join('; '),ui='http://127.0.0.1:'+app.runtimeUi.address().port;
 const request=async(method,body)=>{const response=await fetch(ui+prefix+'__evimed_browser/'+method,{method:'POST',headers:{Origin:'http://127.0.0.1:18443',cookie:cookie+'; '+frameCookie,'content-type':'application/json',Connection:'close'},body:JSON.stringify(body)});return{status:response.status,value:await response.json()};};
 const body={sessionId:'native-owned',tabId:'owned',viewport:{width:640,height:480}};
 assert.equal((await request('open',body)).status,200);assert.equal(opens,1);assert.equal(lists,1);
 for(const sessionId of['foreign-project-session','unknown-session']){const response=await request('open',{...body,sessionId});assert.equal(response.status,404);assert.equal(response.value.code,'runtime_session_not_found');}assert.equal(opens,1);
 unavailable=true;assert.equal((await request('open',body)).status,503);assert.equal(opens,1);unavailable=false;replaceDuringList=true;assert.equal((await request('open',body)).status,503);assert.equal(opens,1);replaceDuringList=false;
 const before=lists;assert.equal((await request('snapshot',{id:'captured',sessionId:'native-owned',tabId:'owned'})).status,200);assert.equal(lists,before);
 await app.researchSessions.put(project,'native-owned',{mode:'specialist',agentId:'source-understanding',agentVersion:(await app.agentRegistry).get('source-understanding').version});const privateSession=await request('open',body);assert.equal(privateSession.status,403);assert.equal(privateSession.value.code,'agent_background_only');assert.equal(opens,1);
 for(const method of['snapshot','command']){const blocked=await request(method,{id:'captured',sessionId:'native-owned',tabId:'owned',...(method==='command'?{sequence:1,command:{type:'back'}}:{})});assert.equal(blocked.status,403);assert.equal(blocked.value.code,'agent_background_only');}
 app.runtimeManager.runtimes.clear();assert.equal((await request('close',{sessionId:'native-owned',tabId:'owned'})).status,200);assert.equal(lists,before);assert.equal((await request('open',{...body,sessionId:'native-unbound'})).status,503);assert.equal(opens,1);
 }finally{app?.runtimeManager.runtimes.clear();await app?.close();await fs.rm(root,{recursive:true,force:true});}
});
