// 「虚拟临床研究」's eligibility engine: the four states and the algebra over them,
// the evidence check that voids a fabricated fact, the as-of replay, and the
// evaluation report that describes reference agreement separately from clinical accuracy.
//
// The case numbers in the titles are the plan's: AC-14/15/36 are §12, and
// C2-15…C2-20 are attachment C2's matching cases. They are in the titles on
// purpose — the acceptance table is generated by grepping for them.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

import {
  SATISFIED, NOT_SATISFIED, UNKNOWN, PENDING_RECHECK, VCR_MATCHING_STATES,
  admissibleFacts, applicabilityConfusion, assessSubject, blockingExclusionUnknowns,
  criterionConfusion, criterionFunnel, dueRechecks, eligibilityCounts, errorLayer, evaluateCriterion,
  evaluateRequirement, evidenceGaps, factsVisibleAt, frozenAsOf, interRaterAgreement, kleeneAnd, kleeneNot, kleeneOr,
  labelClinicalPriority, matchingAssessmentDocument, matchingEvaluationReport, matchingReportDiff, patientMatchingMetrics,
  pendingReviewExclusions, requiresLanguageJudgment, runMatchingEvaluation, separateLedgers,
  summarizeEligibility, verifyFactEvidence, windowStart, withinWindow,
} from "../src/vcrMatching.mjs";
import { validateCapabilityManifest, vcrMatchingFindings } from "@evimed/domain";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const AS_OF = "2026-09-28T00:00:00Z";

/** A one-document chart with the spans computed from the text, the way the fixture generator does. */
function chart(text, id = "doc-1") {
  return {
    documents: { [id]: { id, text } },
    /** @param {string} surface @param {any} rest */
    fact(surface, rest = {}) {
      const start = text.indexOf(surface);
      assert.notEqual(start, -1, `fixture: ${surface} is not in the chart`);
      return {
        id: rest.id ?? `f-${start}`,
        polarity: "affirmed",
        extractedBy: "model",
        visibleAt: "2026-09-01T00:00:00Z",
        surface,
        ...rest,
        source: { documentId: id, start, end: start + surface.length, quote: surface },
      };
    },
  };
}

const CRITERION_MI = {
  id: "crt-mi", kind: "exclusion", criterionType: "time_window",
  sourceText: "近 6 个月内发生过心肌梗死者除外",
  requirement: { op: "absent", variable: "myocardial_infarction", window: { months: 6 } },
};

// --------------------------------------------------------------- C2-15

test("C2-15 AND, OR and NOT agree with Kleene's strong three-valued tables", () => {
  // AND
  assert.equal(kleeneAnd(SATISFIED, SATISFIED), SATISFIED);
  assert.equal(kleeneAnd(SATISFIED, NOT_SATISFIED), NOT_SATISFIED);
  assert.equal(kleeneAnd(SATISFIED, UNKNOWN), UNKNOWN);
  assert.equal(kleeneAnd(NOT_SATISFIED, NOT_SATISFIED), NOT_SATISFIED);
  assert.equal(kleeneAnd(NOT_SATISFIED, UNKNOWN), NOT_SATISFIED, "false absorbs unknown");
  assert.equal(kleeneAnd(UNKNOWN, UNKNOWN), UNKNOWN);
  // OR
  assert.equal(kleeneOr(SATISFIED, SATISFIED), SATISFIED);
  assert.equal(kleeneOr(SATISFIED, NOT_SATISFIED), SATISFIED);
  assert.equal(kleeneOr(SATISFIED, UNKNOWN), SATISFIED, "true absorbs unknown");
  assert.equal(kleeneOr(NOT_SATISFIED, NOT_SATISFIED), NOT_SATISFIED);
  assert.equal(kleeneOr(NOT_SATISFIED, UNKNOWN), UNKNOWN);
  assert.equal(kleeneOr(UNKNOWN, UNKNOWN), UNKNOWN);
  // NOT
  assert.equal(kleeneNot(SATISFIED), NOT_SATISFIED);
  assert.equal(kleeneNot(NOT_SATISFIED), SATISFIED);
  assert.equal(kleeneNot(UNKNOWN), UNKNOWN);
  // Commutative and associative, like the algebra they implement.
  for (const a of [SATISFIED, NOT_SATISFIED, UNKNOWN]) {
    for (const b of [SATISFIED, NOT_SATISFIED, UNKNOWN]) {
      assert.equal(kleeneAnd(a, b), kleeneAnd(b, a));
      assert.equal(kleeneOr(a, b), kleeneOr(b, a));
      for (const c of [SATISFIED, NOT_SATISFIED, UNKNOWN]) {
        assert.equal(kleeneAnd(kleeneAnd(a, b), c), kleeneAnd(a, kleeneAnd(b, c)));
        assert.equal(kleeneOr(kleeneOr(a, b), c), kleeneOr(a, kleeneOr(b, c)));
        // De Morgan holds in Kleene logic and is the cheapest proof the table is right.
        assert.equal(kleeneNot(kleeneAnd(a, b)), kleeneOr(kleeneNot(a), kleeneNot(b)));
      }
    }
  }
});

test("C2-15 a deferral behaves as unknown in the tables and survives only where the answer is indeterminate", () => {
  assert.equal(kleeneAnd(NOT_SATISFIED, PENDING_RECHECK), NOT_SATISFIED, "a definite no is not deferred");
  assert.equal(kleeneOr(SATISFIED, PENDING_RECHECK), SATISFIED, "a definite yes is not deferred");
  assert.equal(kleeneAnd(SATISFIED, PENDING_RECHECK), PENDING_RECHECK);
  assert.equal(kleeneOr(NOT_SATISFIED, PENDING_RECHECK), PENDING_RECHECK);
  assert.equal(kleeneNot(PENDING_RECHECK), PENDING_RECHECK);
  // And the thing the deferral exists to prevent: it is never rounded up.
  assert.notEqual(kleeneAnd(SATISFIED, PENDING_RECHECK), SATISFIED);
});

test("C2-15 AC-14 an unknown exclusion criterion never lets a subject read as eligible", () => {
  const judgments = [
    { criterionId: "a", kind: "inclusion", applicable: true, state: SATISFIED },
    { criterionId: "b", kind: "exclusion", applicable: true, state: UNKNOWN },
  ];
  assert.equal(summarizeEligibility(judgments), "insufficient_evidence");
  assert.deepEqual(blockingExclusionUnknowns(judgments), ["b"]);
  // Nor does it become a refusal: unknown is not "no".
  assert.notEqual(summarizeEligibility(judgments), "ineligible");
});

// --------------------------------------------------------------- C2-16

test("C2-16 AC-14 a missing treatment history leaves the washout unknown, never satisfied", () => {
  const washout = {
    id: "crt-washout", kind: "exclusion", criterionType: "prior_treatment",
    requirement: { op: "elapsed_since", variable: "docetaxel", days: 28, comparator: "gte" },
  };
  const bare = evaluateCriterion(washout, { facts: [], asOf: Date.parse(AS_OF) });
  assert.equal(bare.state, UNKNOWN);
  assert.notEqual(bare.state, SATISFIED);
  assert.notEqual(bare.state, NOT_SATISFIED);
  assert.deepEqual(bare.missing, [{ variable: "docetaxel", reason: "not_recorded" }]);

  // With the evidence, the same criterion is decided; deleting it puts it back.
  const source = chart("末次多西他赛：2026-01-10。");
  const fact = source.fact("末次多西他赛：2026-01-10", {
    variable: "docetaxel", surface: "末次多西他赛", dateSurface: "2026-01-10", occurredAt: "2026-01-10T00:00:00Z",
  });
  const withEvidence = evaluateCriterion(washout, { facts: [fact], asOf: Date.parse(AS_OF) });
  assert.equal(withEvidence.state, SATISFIED);
  assert.equal(evaluateCriterion(washout, { facts: [], asOf: Date.parse(AS_OF) }).state, UNKNOWN);
});

test("C2-16 AC-14 unknown is not folded into not-satisfied anywhere in the summary", () => {
  const onlyUnknown = [{ criterionId: "a", kind: "inclusion", applicable: true, state: UNKNOWN }];
  assert.equal(summarizeEligibility(onlyUnknown), "insufficient_evidence");
  const counts = eligibilityCounts([
    { applicable: true, state: SATISFIED }, { applicable: true, state: UNKNOWN },
    { applicable: true, state: PENDING_RECHECK }, { applicable: false, state: UNKNOWN },
  ]);
  assert.deepEqual(counts, { satisfied: 1, not_satisfied: 0, unknown: 1, pending_recheck: 1, notApplicable: 1, total: 4 });
});

test('latest lab ties cannot choose a passing or failing value by row order', () => {
  const criterion={id:'tie',kind:'inclusion',criterionType:'lab',requirement:{op:'compare',variable:'creatinine',comparator:'lte',value:1.5,unit:'mg/dL',aggregate:'latest'}};
  const a={id:'a',variable:'creatinine',value:1,unit:'mg/dL',polarity:'affirmed',occurredAt:'2026-01-01'};
  const b={...a,id:'b',value:2.4};
  for(const facts of [[a,b],[b,a]]) assert.equal(evaluateCriterion(criterion,{facts,asOf:Date.parse(AS_OF)}).state,UNKNOWN);
  assert.equal(evaluateCriterion(criterion,{facts:[a,{...b,value:88.4,unit:'µmol/L'}],asOf:Date.parse(AS_OF)}).state,SATISFIED);
});

test('current non-administration is not a lifetime denial of earlier exposure', () => {
  const criterion={id:'wash',kind:'exclusion',criterionType:'prior_treatment',requirement:{op:'elapsed_since',variable:'docetaxel',days:28,comparator:'gte'}};
  const context={schema:1,assertion:'negated',experiencer:'patient',temporality:'current',medication:{state:'planned',absenceScope:'current'}};
  const current={id:'no-current-dose',variable:'docetaxel',polarity:'negated',clinical:context};
  assert.equal(evaluateCriterion(criterion,{facts:[current],asOf:Date.parse(AS_OF)}).state,UNKNOWN);
  const never={...current,clinical:{...context,temporality:'historical',medication:{state:'unknown',absenceScope:'never'}}};
  assert.equal(evaluateCriterion(criterion,{facts:[never],asOf:Date.parse(AS_OF)}).state,SATISFIED);
});

test("AC-14 not-applicable is a field beside the state, not a fifth state and not an unknown", () => {
  const pregnancy = {
    id: "crt-preg", kind: "exclusion", criterionType: "pregnancy",
    requirement: { op: "absent", variable: "pregnancy" },
    applicability: { op: "compare", variable: "sex", comparator: "in", value: ["female"] },
  };
  const male = [{ id: "s", variable: "sex", value: "male", polarity: "affirmed", extractedBy: "structured" }];
  const judged = evaluateCriterion(pregnancy, { facts: male, asOf: Date.parse(AS_OF) });
  assert.equal(judged.applicable, false);
  assert.equal(judged.applicabilityState, NOT_SATISFIED);
  assert.ok(VCR_MATCHING_STATES.includes(judged.state), "the state stays one of the four");
  // And a criterion that does not apply cannot hold a subject out of 「符合」.
  assert.equal(summarizeEligibility([
    { criterionId: "ok", kind: "inclusion", applicable: true, state: SATISFIED }, judged,
  ]), "eligible");
  // Nor does it raise an evidence gap: nobody should be sent to look for it.
  assert.deepEqual(evidenceGaps([judged]), []);
});

// --------------------------------------------------------------- C2-17

test("C2-17 a value the source text does not contain voids the fact and the criterion reads unknown", () => {
  const source = chart("2026-09-06 血肌酐 2.4 mg/dL。");
  const fabricated = source.fact("血肌酐 2.4 mg/dL", {
    id: "f-creat", variable: "creatinine", value: 1.2, unit: "mg/dL",
    surface: "血肌酐", occurredAt: "2026-09-06T00:00:00Z",
  });
  assert.deepEqual(verifyFactEvidence(fabricated, { documents: source.documents, asOf: Date.parse(AS_OF) }),
    { ok: false, reason: "value_not_in_span" });

  const criterion = {
    id: "crt-creat", kind: "inclusion", criterionType: "lab",
    requirement: { op: "compare", variable: "creatinine", comparator: "lte", value: 1.5, unit: "mg/dL" },
  };
  const { facts, voided } = admissibleFacts([fabricated], { documents: source.documents, asOf: Date.parse(AS_OF) });
  assert.deepEqual(facts, []);
  assert.deepEqual(voided, [{ factId: "f-creat", variable: "creatinine", reason: "value_not_in_span" }]);
  assert.equal(evaluateCriterion(criterion, { facts, asOf: Date.parse(AS_OF) }).state, UNKNOWN);

  // The honest extraction of the same span passes and decides the criterion.
  const honest = { ...fabricated, value: 2.4 };
  assert.equal(verifyFactEvidence(honest, { documents: source.documents, asOf: Date.parse(AS_OF) }).ok, true);
  assert.equal(evaluateCriterion(criterion, { facts: [honest], asOf: Date.parse(AS_OF) }).state, NOT_SATISFIED);
});

test("C2-17 every other way a locator can lie is named, and none of them reads as satisfied", () => {
  const source = chart("否认心梗史，否认妊娠。");
  const good = source.fact("否认心梗史", { variable: "myocardial_infarction", polarity: "negated" });
  const context = { documents: source.documents, asOf: Date.parse(AS_OF) };
  assert.equal(verifyFactEvidence(good, context).ok, true);

  const cases = [
    ["locator_missing", { ...good, source: undefined }],
    ["document_unavailable", { ...good, source: { ...good.source, documentId: "doc-9" } }],
    ["span_out_of_range", { ...good, source: { ...good.source, end: 9_999 } }],
    ["quote_mismatch", { ...good, source: { ...good.source, quote: "确诊心梗" } }],
    ["surface_missing", { ...good, surface: undefined, surfaceForms: [] }],
    ["value_not_in_span", { ...good, surface: "否认糖尿病史" }],
    ["date_not_in_span", { ...good, dateSurface: "2026-01-01" }],
    ["not_yet_visible", { ...good, visibleAt: "2026-10-01T00:00:00Z" }],
    ["polarity_not_assertive", { ...good, polarity: "family" }],
  ];
  for (const [reason, fact] of cases) {
    assert.deepEqual(verifyFactEvidence(fact, context), { ok: false, reason }, reason);
    const judged = evaluateCriterion(CRITERION_MI, {
      facts: admissibleFacts([fact], context).facts, asOf: Date.parse(AS_OF),
    });
    assert.equal(judged.state, UNKNOWN, `${reason} must not decide the criterion`);
  }
});

// --------------------------------------------------------------- C2-18

test("C2-18 AC-15 a result that became visible after the assessment date is not in the replay", () => {
  const source = chart("2026-09-26 血肌酐 1.1 mg/dL。");
  const late = source.fact("血肌酐 1.1 mg/dL", {
    id: "f-late", variable: "creatinine", value: 1.1, unit: "mg/dL", surface: "血肌酐",
    occurredAt: "2026-09-26T00:00:00Z", recordedAt: "2026-09-27T00:00:00Z", visibleAt: "2026-09-30T00:00:00Z",
  });
  const criterion = {
    id: "crt-creat", kind: "inclusion", criterionType: "lab",
    requirement: { op: "compare", variable: "creatinine", comparator: "lte", value: 1.5, unit: "mg/dL" },
  };
  const replay = assessSubject({ subjectKey: "S", criteria: [criterion], facts: [late], documents: source.documents, asOf: AS_OF });
  assert.equal(replay.judgments[0].state, UNKNOWN, "it was not knowable on 2026-09-28");
  assert.equal(replay.factsWithheldAsFuture, 1);
  assert.deepEqual(factsVisibleAt([late], AS_OF), []);

  const later = assessSubject({ subjectKey: "S", criteria: [criterion], facts: [late], documents: source.documents, asOf: "2026-10-02T00:00:00Z" });
  assert.equal(later.judgments[0].state, SATISFIED, "the same fact decides it once it is visible");
  assert.equal(later.factsWithheldAsFuture, 0);
});

test("C2-18 AC-15 the three clocks are distinct: occurred and recorded do not admit a fact on their own", () => {
  const source = chart("2026-09-01 血肌酐 1.1 mg/dL。");
  const fact = source.fact("血肌酐 1.1 mg/dL", {
    variable: "creatinine", value: 1.1, unit: "mg/dL", surface: "血肌酐",
    occurredAt: "2026-09-01T00:00:00Z", recordedAt: "2026-09-02T00:00:00Z", visibleAt: "2026-09-30T00:00:00Z",
  });
  assert.deepEqual(factsVisibleAt([fact], AS_OF), [], "occurring before as-of is not being visible before it");
});

// --------------------------------------------------------------- C2-19

test("C2-19 近 6 个月无心梗: denial, an event inside the window and an event outside it read met / not met / met", () => {
  const rows = [
    ["否认心梗史。", "否认心梗史", "negated", null, SATISFIED],
    ["2026-06-28 因急性心梗入院。", "2026-06-28 因急性心梗入院", "affirmed", "2026-06-28T00:00:00Z", NOT_SATISFIED],
    ["2026-02-20 因急性心梗入院。", "2026-02-20 因急性心梗入院", "affirmed", "2026-02-20T00:00:00Z", SATISFIED],
  ];
  for (const [text, surface, polarity, occurredAt, expected] of rows) {
    const source = chart(text);
    const fact = source.fact(surface, { variable: "myocardial_infarction", polarity, occurredAt });
    const judged = evaluateCriterion(CRITERION_MI, {
      facts: admissibleFacts([fact], { documents: source.documents, asOf: Date.parse(AS_OF) }).facts,
      asOf: Date.parse(AS_OF),
    });
    assert.equal(judged.state, expected, `${surface} → ${expected}`);
    assert.equal(judged.decidedBy, "code");
    assert.ok(judged.evidence.length >= 1, "a decided criterion cites the sentence it was decided from");
  }
  // And the fourth reading, which is the one the other three exist to contrast:
  // the chart says nothing about the heart at all.
  assert.equal(evaluateCriterion(CRITERION_MI, { facts: [], asOf: Date.parse(AS_OF) }).state, UNKNOWN);
  // An event nobody dated cannot be placed in or out of the window.
  const undatedSource = chart("既往心梗。");
  const undated = undatedSource.fact("既往心梗", { variable: "myocardial_infarction", occurredAt: null });
  assert.equal(evaluateCriterion(CRITERION_MI, { facts: [undated], asOf: Date.parse(AS_OF) }).state, UNKNOWN);
});

test("C2-19 the window boundary is a calendar month, not thirty days", () => {
  const anchor = Date.parse(AS_OF);
  assert.equal(new Date(windowStart({ months: 6 }, anchor)).toISOString(), "2026-03-28T00:00:00.000Z");
  assert.equal(new Date(windowStart({ days: 180 }, anchor)).toISOString(), "2026-04-01T00:00:00.000Z");
  assert.equal(windowStart({}, anchor), null, "a criterion with no window has no boundary");
  const inside = { occurredAt: "2026-04-01T00:00:00Z" };
  const outside = { occurredAt: "2026-03-01T00:00:00Z" };
  assert.equal(withinWindow(inside, { months: 6 }, anchor), true);
  assert.equal(withinWindow(outside, { months: 6 }, anchor), false);
  assert.equal(withinWindow({ occurredAt: null }, { months: 6 }, anchor), null);
  assert.equal(withinWindow(outside, null, anchor), true, "no window means every date qualifies");
});

// ------------------------------------------------- deferral, gaps, priority

test("AC-14 a washout that ends on a known date is deferred, not satisfied early", () => {
  const source = chart("末次多西他赛：2026-09-20。");
  const fact = source.fact("末次多西他赛：2026-09-20", {
    variable: "docetaxel", surface: "末次多西他赛", dateSurface: "2026-09-20", occurredAt: "2026-09-20T00:00:00Z",
  });
  const criterion = {
    id: "crt-washout", kind: "exclusion", criterionType: "prior_treatment",
    requirement: { op: "elapsed_since", variable: "docetaxel", days: 28, comparator: "gte" },
  };
  const judged = evaluateCriterion(criterion, { facts: [fact], asOf: Date.parse(AS_OF) });
  assert.equal(judged.state, PENDING_RECHECK);
  assert.notEqual(judged.state, SATISFIED);
  assert.equal(judged.recheckAt, "2026-10-18T00:00:00.000Z");
  assert.deepEqual(dueRechecks([judged], "2026-10-01T00:00:00Z"), []);
  assert.deepEqual(dueRechecks([judged], "2026-10-18T00:00:00Z"), [{ criterionId: "crt-washout", recheckAt: "2026-10-18T00:00:00.000Z" }]);
  // On the day it comes due, the same code decides it.
  assert.equal(evaluateCriterion(criterion, { facts: [fact], asOf: Date.parse("2026-10-18T00:00:00Z") }).state, SATISFIED);
  // And the summary is 「待复评」, distinct from both 「符合」 and 「证据不足」.
  assert.equal(summarizeEligibility([judged]), "pending");
});

test("a unit nobody can convert is unknown, never a comparison on the raw number", () => {
  // Albumin has no built-in conversion: 42 g/L against a g/dL ceiling is not 42.
  const source = chart("白蛋白 42 g/L。");
  const fact = source.fact("白蛋白 42 g/L", { variable: "albumin", value: 42, unit: "g/L", surface: "白蛋白" });
  const node = { op: "compare", variable: "albumin", comparator: "gte", value: 3.5, unit: "g/dL" };
  const refused = evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF) });
  assert.equal(refused.state, UNKNOWN);
  assert.deepEqual(refused.missing, [{ variable: "albumin", reason: "unit_mismatch" }]);
  const converter = (value, from, to) => (from === "g/L" && to === "g/dL" ? value / 10 : null);
  assert.equal(evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF), unitConverter: converter }).state, SATISFIED);
});

test("creatinine in µmol/L is read as mg/dL by the built-in conversion, and never as the raw 106", () => {
  const source = chart("血肌酐 106 umol/L。");
  const fact = source.fact("血肌酐 106 umol/L", { variable: "creatinine", value: 106, unit: "umol/L", surface: "血肌酐" });
  const node = { op: "compare", variable: "creatinine", comparator: "lte", value: 1.5, unit: "mg/dL" };
  assert.equal(evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF) }).state, SATISFIED);
  const high = source.fact("血肌酐 106 umol/L", { variable: "creatinine", value: 190, unit: "µmol/L", surface: "血肌酐" });
  assert.equal(evaluateRequirement(node, { facts: [{ ...high, source: fact.source, value: 190 }], asOf: Date.parse(AS_OF) }).state, NOT_SATISFIED);
});

test("CS-33 a fact with no unit against a criterion that names one is unknown (unit_missing)", () => {
  const fact = { id: "f", variable: "creatinine", value: 1.2, extractedBy: "snapshot" };
  const node = { op: "compare", variable: "creatinine", comparator: "lte", value: 1.5, unit: "mg/dL" };
  const judged = evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF) });
  assert.equal(judged.state, UNKNOWN);
  assert.deepEqual(judged.missing, [{ variable: "creatinine", reason: "unit_missing" }]);
  // A criterion that names none compares the number as it stands.
  assert.equal(evaluateRequirement({ ...node, unit: undefined }, { facts: [fact], asOf: Date.parse(AS_OF) }).state, SATISFIED);
});

test("CS-33 a requirement outside the grammar is unknown (criterion_malformed), never a guess", () => {
  const facts = [{ id: "f", variable: "ecog", value: 1, extractedBy: "snapshot" }];
  for (const node of [
    { field: "ecog", op: "<=", value: 1 },
    { op: "compare", variable: "ecog", comparator: "lte", value: "1天" },
    { op: "compare", variable: "ECOG", comparator: "lte", value: 1 },
    { op: "elapsed_since", variable: "docetaxel", days: "28天" },
    { op: "language", key: "crt-x" },
    null, "ecog <= 1", { free_text: "ECOG 0–1" },
  ]) {
    const judged = evaluateRequirement(node, { facts, asOf: Date.parse(AS_OF) });
    assert.equal(judged.state, UNKNOWN, JSON.stringify(node));
    assert.equal(judged.missing[0].reason, "criterion_malformed", JSON.stringify(node));
  }
  // One malformed criterion does not stop the others.
  const assessment = assessSubject({
    subjectKey: "S", asOf: AS_OF, facts,
    criteria: [
      { id: "c1", kind: "inclusion", criterionType: "performance_status", requirement: { op: "elapsed_since", variable: "x", days: "28天" } },
      { id: "c2", kind: "inclusion", criterionType: "performance_status", requirement: { op: "compare", variable: "ecog", comparator: "lte", value: 1 } },
    ],
  });
  assert.deepEqual(assessment.judgments.map((judgment) => judgment.state), [UNKNOWN, SATISFIED]);
  assert.equal(assessment.summary, "insufficient_evidence");
});

test("CS-33 coded values go through a small vocabulary or are unknown (coding_unmapped)", () => {
  const node = { op: "compare", variable: "sex", comparator: "in", value: ["female"] };
  for (const code of ["female", "女", "F", "女性", "2"]) {
    const fact = { id: "s", variable: "sex", value: code, extractedBy: "snapshot" };
    assert.equal(evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF) }).state, SATISFIED, code);
  }
  for (const code of ["男", "M", "male"]) {
    const fact = { id: "s", variable: "sex", value: code, extractedBy: "snapshot" };
    assert.equal(evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF) }).state, NOT_SATISFIED, code);
  }
  const unread = evaluateRequirement(node, { facts: [{ id: "s", variable: "sex", value: "X", extractedBy: "snapshot" }], asOf: Date.parse(AS_OF) });
  assert.equal(unread.state, UNKNOWN);
  assert.equal(unread.missing[0].reason, "coding_unmapped");
  // A woman coded 「女」 gets the pregnancy criterion applied — the failure this pins.
  const pregnancy = { id: "p", kind: "exclusion", criterionType: "pregnancy", requirement: { op: "absent", variable: "pregnancy" }, applicability: node };
  const woman = assessSubject({ subjectKey: "W", asOf: AS_OF, criteria: [pregnancy], facts: [{ id: "s", variable: "sex", value: "女", extractedBy: "snapshot" }] });
  assert.equal(woman.judgments[0].applicable, true);
  assert.equal(woman.summary, "insufficient_evidence");
  const man = assessSubject({ subjectKey: "M", asOf: AS_OF, criteria: [pregnancy], facts: [{ id: "s", variable: "sex", value: "男", extractedBy: "snapshot" }] });
  assert.equal(man.judgments[0].applicable, false);
  // A non-vocabulary code is compared as its token, numbers as numbers.
  const stage = { op: "compare", variable: "stage", comparator: "in", value: ["IIIB", "IV"] };
  assert.equal(evaluateRequirement(stage, { facts: [{ id: "g", variable: "stage", value: "iiib", extractedBy: "snapshot" }], asOf: Date.parse(AS_OF) }).state, SATISFIED);
  assert.equal(evaluateRequirement({ op: "compare", variable: "ecog", comparator: "in", value: [0, 1] }, { facts: [{ id: "e", variable: "ecog", value: "1", extractedBy: "snapshot" }], asOf: Date.parse(AS_OF) }).state, SATISFIED);
  assert.equal(evaluateRequirement({ op: "compare", variable: "ecog", comparator: "in", value: [0, 1] }, { facts: [{ id: "e", variable: "ecog", value: 2, extractedBy: "snapshot" }], asOf: Date.parse(AS_OF) }).state, NOT_SATISFIED);
});

test("CS-33 an undated fact never decides a windowed comparison (undated)", () => {
  const undated = { id: "f", variable: "creatinine", value: 1.2, unit: "mg/dL", extractedBy: "snapshot" };
  const windowed = { op: "compare", variable: "creatinine", comparator: "lte", value: 1.5, unit: "mg/dL", window: { months: 3 } };
  const judged = evaluateRequirement(windowed, { facts: [undated], asOf: Date.parse(AS_OF) });
  assert.equal(judged.state, UNKNOWN);
  assert.equal(judged.missing[0].reason, "undated");
  // Without a window the same fact decides.
  assert.equal(evaluateRequirement({ ...windowed, window: undefined }, { facts: [undated], asOf: Date.parse(AS_OF) }).state, SATISFIED);
  // A dated fact inside the window decides even beside an undated one.
  const dated = { ...undated, id: "g", occurredAt: "2026-09-20T00:00:00Z" };
  assert.equal(evaluateRequirement(windowed, { facts: [undated, dated], asOf: Date.parse(AS_OF) }).state, SATISFIED);
  // A treatment recorded with no date is undated, not silence.
  const treated = evaluateRequirement({ op: "elapsed_since", variable: "docetaxel", days: 28 }, { facts: [{ id: "d", variable: "docetaxel", extractedBy: "snapshot" }], asOf: Date.parse(AS_OF) });
  assert.equal(treated.missing[0].reason, "undated");
});

test("M-9 an unknown next to a deferral keeps the gap: the AND is unknown, not pending", () => {
  assert.equal(kleeneAnd(UNKNOWN, PENDING_RECHECK), UNKNOWN);
  assert.equal(kleeneAnd(PENDING_RECHECK, UNKNOWN), UNKNOWN);
  assert.equal(kleeneOr(UNKNOWN, PENDING_RECHECK), UNKNOWN);
  assert.equal(kleeneAnd(PENDING_RECHECK, PENDING_RECHECK), PENDING_RECHECK);
  const compound = { id: "crt-x", kind: "exclusion", criterionType: "prior_treatment", requirement: { op: "all", operands: [
    { op: "elapsed_since", variable: "docetaxel", days: 28 }, { op: "absent", variable: "pregnancy" }] } };
  const facts = [{ id: "d", variable: "docetaxel", occurredAt: "2026-09-20T00:00:00Z", extractedBy: "snapshot" }];
  const judged = assessSubject({ subjectKey: "S", asOf: "2026-09-28T00:00:00Z", criteria: [compound], facts });
  assert.equal(judged.judgments[0].state, UNKNOWN);
  assert.deepEqual(judged.blockingExclusionUnknowns, ["crt-x"], "the pregnancy test is still owed");
  assert.equal(judged.summary, "insufficient_evidence");
});

test("CS-34 asOf is a valid ISO date or instant, refused by code otherwise", () => {
  assert.equal(frozenAsOf("2026-09-28"), "2026-09-28T00:00:00.000Z");
  assert.equal(frozenAsOf("2026-09-28T08:00:00+08:00"), "2026-09-28T00:00:00.000Z");
  for (const bad of ["28/09/2026", "", null, undefined, 20260928, "2026-13-45", "yesterday"]) {
    assert.throws(() => frozenAsOf(bad), (error) => /** @type {any} */ (error).code === "vcr_asof_invalid", String(bad));
  }
});

test("a criterion only language can decide is answered by the model, and only with an anchored quote", () => {
  const source = chart("患者本人可理解研究内容并签署知情同意。");
  const node = { op: "language", key: "crt-consent", text: "受试者能够理解研究内容并签署知情同意书" };
  assert.equal(requiresLanguageJudgment(node), true);
  assert.equal(requiresLanguageJudgment({ op: "all", operands: [node] }), true);
  assert.equal(requiresLanguageJudgment({ op: "present", variable: "x" }), false);

  const base = { facts: [], asOf: Date.parse(AS_OF), documents: source.documents, criterionId: "crt-consent" };
  const quote = "患者本人可理解研究内容并签署知情同意";
  const start = "患者本人可理解研究内容并签署知情同意。".indexOf(quote);
  const anchored = { state: SATISFIED, evidence: [{ documentId: "doc-1", start, end: start + quote.length, quote }] };
  assert.equal(evaluateRequirement(node, { ...base, modelJudgments: { "crt-consent": anchored } }).state, SATISFIED);
  // The same verdict with a quote the chart does not carry is refused.
  const invented = { state: SATISFIED, evidence: [{ documentId: "doc-1", start: 0, end: 4, quote: "无法理解" }] };
  assert.equal(evaluateRequirement(node, { ...base, modelJudgments: { "crt-consent": invented } }).state, UNKNOWN);
  assert.equal(evaluateRequirement(node, { ...base, modelJudgments: {} }).state, UNKNOWN);
  assert.equal(evaluateCriterion({ id: "crt-consent", requirement: node }, { ...base, modelJudgments: { "crt-consent": anchored } }).decidedBy, "model");
});

test("the model's clinical priority is carried, labelled, and never merged into the counts", () => {
  const priority = labelClinicalPriority({ score: 0.81, rationale: "病理分型与方案一致" });
  assert.equal(priority.isBenefitProbability, false);
  assert.equal(priority.decidedBy, "model");
  assert.match(priority.label, /不是获益概率/);
  assert.equal(labelClinicalPriority(null), null);
  const counts = eligibilityCounts([{ applicable: true, state: SATISFIED }]);
  assert.equal(Object.keys(counts).includes("score"), false, "the priority never enters the deterministic summary");
});

test("the five ledgers are five fields, and eligibility is not one of the other four", () => {
  const ledgers = separateLedgers({
    summary: "eligible",
    counts: { unknown: 2, pending_recheck: 1 },
    willingness: "interested",
    siteCapacity: { siteId: "ste-1", slotsAvailable: 0 },
    referralState: "contactable",
  });
  assert.deepEqual(Object.keys(ledgers).sort(), [
    "businessProgress", "clinicalEligibility", "evidenceSufficiency", "patientWillingness", "siteCapacity",
  ]);
  assert.equal(ledgers.clinicalEligibility, "eligible");
  assert.equal(ledgers.evidenceSufficiency.sufficient, false, "eligible on the criteria is not evidence-complete");
  assert.equal(ledgers.siteCapacity.slotsAvailable, 0, "and a full site does not change the eligibility");
});

// ----------------------------------------------------- the whole assessment

test("AC-14 a full assessment keeps the gaps, the void facts and the blocking exclusions on the record", () => {
  const text = "男，67 岁。否认心梗史。2026-09-06 血肌酐 2.4 mg/dL。";
  const source = chart(text);
  const criteria = [
    { id: "crt-age", kind: "inclusion", criterionType: "demographic", requirement: { op: "compare", variable: "age", comparator: "gte", value: 18 } },
    CRITERION_MI,
    { id: "crt-washout", kind: "exclusion", criterionType: "prior_treatment", requirement: { op: "elapsed_since", variable: "docetaxel", days: 28 } },
  ];
  const facts = [
    { id: "age", variable: "age", value: 67, polarity: "affirmed", extractedBy: "structured" },
    source.fact("否认心梗史", { id: "mi", variable: "myocardial_infarction", polarity: "negated" }),
    source.fact("血肌酐 2.4 mg/dL", { id: "creat", variable: "creatinine", value: 9.9, unit: "mg/dL", surface: "血肌酐" }),
  ];
  const assessment = assessSubject({ studyId: "std-1", subjectKey: "S5", criteria, facts, documents: source.documents, asOf: AS_OF });
  assert.equal(assessment.summary, "insufficient_evidence");
  assert.deepEqual(assessment.counts, { satisfied: 2, not_satisfied: 0, unknown: 1, pending_recheck: 0, notApplicable: 0, total: 3 });
  assert.deepEqual(assessment.voidedFacts, [{ factId: "creat", variable: "creatinine", reason: "value_not_in_span" }]);
  assert.deepEqual(assessment.evidenceGaps, [{ variable: "docetaxel", reason: "not_recorded", criterionIds: ["crt-washout"] }]);
  assert.deepEqual(assessment.blockingExclusionUnknowns, ["crt-washout"]);
  assert.equal(assessment.asOf, "2026-09-28T00:00:00.000Z");

  // The structured companion the deliverable ships passes the domain contract.
  const document = matchingAssessmentDocument(assessment);
  const findings = vcrMatchingFindings({ files: new Map([["matching.json", JSON.stringify(document)]]) });
  assert.deepEqual(findings.issues, [], "every decided judgment carries a quote and a locator");
  assert.equal(findings.metrics.vcrJudgments, 3);
  assert.equal(findings.metrics.vcrJudgmentsUnanchored, 0);
});

test("subjects ruled out on a model's word alone go to the review queue, not out of the list", () => {
  const modelOnly = {
    subjectKey: "S7", summary: "ineligible",
    judgments: [{ criterionId: "crt-consent", applicable: true, state: NOT_SATISFIED, decidedBy: "model" }],
  };
  const codeDecided = {
    subjectKey: "S2", summary: "ineligible",
    judgments: [{ criterionId: "crt-mi", applicable: true, state: NOT_SATISFIED, decidedBy: "code" }],
  };
  const eligible = { subjectKey: "S1", summary: "eligible", judgments: [] };
  const queue = pendingReviewExclusions([modelOnly, codeDecided, eligible]);
  assert.deepEqual(queue.map((item) => item.subjectKey), ["S7"]);
});

test("the criterion funnel says which single line is costing the trial its patients", () => {
  const make = (subjectKey, states) => ({
    subjectKey, summary: "ineligible",
    judgments: states.map(([criterionId, state]) => ({ criterionId, kind: "exclusion", criterionType: "lab", applicable: true, state, decidedBy: "code" })),
  });
  const funnel = criterionFunnel([
    make("a", [["crt-1", NOT_SATISFIED], ["crt-2", SATISFIED]]),
    make("b", [["crt-1", NOT_SATISFIED], ["crt-2", SATISFIED]]),
    make("c", [["crt-1", SATISFIED], ["crt-2", NOT_SATISFIED]]),
  ]);
  assert.equal(funnel[0].criterionId, "crt-1");
  assert.equal(funnel[0].soleReason, 2);
  assert.equal(funnel[1].soleReason, 1);
});

// --------------------------------------------------------------- C2-20, AC-36

test("AC-36 the criterion confusion matrix counts all sixteen cells and names the two that matter", () => {
  const pairs = [
    { criterionType: "lab", gold: UNKNOWN, predicted: SATISFIED },
    { criterionType: "lab", gold: SATISFIED, predicted: NOT_SATISFIED },
    { criterionType: "time_window", gold: SATISFIED, predicted: SATISFIED },
    { criterionType: "time_window", gold: NOT_SATISFIED, predicted: UNKNOWN },
    { criterionType: "prior_treatment", gold: PENDING_RECHECK, predicted: PENDING_RECHECK },
    { criterionType: "lab", gold: "nonsense", predicted: SATISFIED },
  ];
  const confusion = criterionConfusion(pairs);
  assert.equal(confusion.counted, 5, "a pair outside the vocabulary is not counted as agreement");
  assert.equal(confusion.unknownReadAsSatisfied, 1);
  assert.equal(confusion.satisfiedReadAsNotSatisfied, 1);
  assert.equal(confusion.matrix[NOT_SATISFIED][UNKNOWN], 1);
  assert.equal(confusion.agreement, 2 / 5);
  assert.equal(confusion.unknownRate, 1 / 5);
  assert.equal(confusion.byLayer.number.total, 2);
  assert.equal(confusion.byLayer.time.total, 2);
  assert.equal(errorLayer("time_window"), "time");
  assert.equal(errorLayer("pregnancy"), "applicability");
  assert.equal(errorLayer("something-else"), "other");
});

test("AC-36 「不适用」 confused with 「未知」 has a cell of its own", () => {
  const cells = applicabilityConfusion([
    { goldApplicable: true, predictedApplicable: true, gold: SATISFIED, predicted: SATISFIED },
    { goldApplicable: false, predictedApplicable: false, gold: UNKNOWN, predicted: UNKNOWN },
    { goldApplicable: false, predictedApplicable: true, gold: UNKNOWN, predicted: UNKNOWN },
    { goldApplicable: true, predictedApplicable: false, gold: UNKNOWN, predicted: SATISFIED },
  ]);
  assert.equal(cells.notApplicableReadAsUnknown, 1);
  assert.equal(cells.unknownReadAsNotApplicable, 1);
  assert.equal(cells.agreedApplicable, 1);
  assert.equal(cells.agreedNotApplicable, 1);
  assert.equal(cells.counted, 4);
});

test("AC-36 subject-level metrics report recall, false exclusion, PPV and the number needed to screen together", () => {
  const metrics = patientMatchingMetrics([
    { gold: "eligible", predicted: "eligible" },
    { gold: "eligible", predicted: "eligible" },
    { gold: "eligible", predicted: "ineligible" },
    { gold: "ineligible", predicted: "eligible" },
    { gold: "ineligible", predicted: "ineligible" },
    { gold: "ineligible", predicted: "insufficient_evidence" },
  ]);
  assert.equal(metrics.goldEligible, 3);
  assert.equal(metrics.eligibleRecall, 2 / 3);
  assert.equal(metrics.falseExclusionRate, 1 / 3);
  assert.equal(metrics.positivePredictiveValue, 2 / 3);
  assert.equal(metrics.numberNeededToScreen, 3 / 2);
  assert.equal(metrics.unresolvedRate, 1 / 6);
});

test("AC-36 the report describes inter-rater agreement without claiming an accuracy ceiling", () => {
  const agreement = interRaterAgreement([SATISFIED, SATISFIED, UNKNOWN, NOT_SATISFIED], [SATISFIED, UNKNOWN, UNKNOWN, NOT_SATISFIED]);
  assert.equal(agreement.pairs, 4);
  assert.equal(agreement.agreement, 3 / 4);
  assert.ok(agreement.kappa > 0 && agreement.kappa < 1);
  assert.deepEqual(interRaterAgreement([], []), { pairs: 0, agreement: null, kappa: null });

  const report = matchingEvaluationReport({
    label: "t", synthetic: true,
    criterionPairs: [{ criterionType: "lab", gold: SATISFIED, predicted: SATISFIED }],
    subjectPairs: [{ gold: "eligible", predicted: "eligible" }],
    raterA: [SATISFIED], raterB: [SATISFIED],
    reviewMinutesWithTool: 6, reviewMinutesWithoutTool: 11,
  });
  assert.equal(report.threshold, null, "there is no pass mark");
  assert.equal(Object.hasOwn(report, "passed"), false);
  assert.match(report.note, /不设统一准确率门槛/);
  assert.match(report.ceiling.note, /不代表临床准确率上限/);
  assert.equal(report.reviewMinutes.savedPerChart, 5);
  // Nothing in the report quotes another product's number.
  assert.equal(/87\.3|88\.7|0\.93|63%|TrialGPT|PRISM/.test(JSON.stringify(report)), false);
});

test("C2-20 AC-36 the shipped evaluation set runs end to end and its numbers are the ones on disk", async () => {
  const file = path.join(repoRoot, "evals", "vcr-matching", "matching-eval-sample.json");
  const dataset = JSON.parse(await readFile(file, "utf8"));
  assert.equal(dataset.synthetic, true, "the sample set says it is synthetic");
  assert.match(dataset.note, /synthetic/);
  assert.equal(dataset.cases.length, 7);
  assert.equal(dataset.criteria.length, 6);

  // The fixture is self-consistent: every located fact's span really is its quote.
  let located = 0;
  for (const item of dataset.cases) {
    for (const fact of item.facts) {
      if (!fact.source) continue;
      const text = item.documents[fact.source.documentId].text;
      assert.equal(text.slice(fact.source.start, fact.source.end), fact.source.quote, `${item.subjectKey}/${fact.id}`);
      located += 1;
    }
  }
  assert.ok(located >= 20, `only ${located} located facts — the fixture walk read nothing`);

  const report = runMatchingEvaluation(dataset);
  assert.equal(report.synthetic, true);
  assert.equal(report.criterion.counted, 42);
  // One real error of each direction that this set was built to contain, and
  // no fabricated satisfaction at all.
  assert.equal(report.criterion.satisfiedReadAsNotSatisfied, 1, "the model read hearing loss as incapacity");
  assert.equal(report.criterion.unknownReadAsSatisfied, 0, "nothing was rounded up to 满足");
  assert.equal(report.criterion.matrix[NOT_SATISFIED][UNKNOWN], 1, "the voided creatinine is safe but still wrong");
  assert.equal(report.criterion.agreement, 40 / 42);
  assert.equal(report.subject.subjects, 7);
  assert.equal(report.subject.goldEligible, 3);
  assert.equal(report.subject.eligibleRecall, 2 / 3);
  assert.equal(report.subject.falseExclusionRate, 1 / 3);
  assert.equal(report.subject.positivePredictiveValue, 1);
  assert.equal(report.applicability.agreedNotApplicable, 4);
  assert.equal(report.ceiling.pairs, 42);
  assert.equal(report.ceiling.agreement, 39 / 42);
  assert.equal(report.threshold, null);
});

test("C2-20 the evaluation runs the production evaluator, so a fixture case is reproducible one by one", async () => {
  const file = path.join(repoRoot, "evals", "vcr-matching", "matching-eval-sample.json");
  const dataset = JSON.parse(await readFile(file, "utf8"));
  const expected = {
    S1: "eligible", S2: "ineligible", S3: "insufficient_evidence", S4: "pending",
    S5: "insufficient_evidence", S6: "eligible", S7: "ineligible",
  };
  for (const item of dataset.cases) {
    const assessment = assessSubject({
      subjectKey: item.subjectKey, criteria: dataset.criteria, facts: item.facts,
      documents: item.documents, modelJudgments: item.modelJudgments, asOf: item.asOf,
    });
    assert.equal(assessment.summary, expected[item.subjectKey], item.subjectKey);
  }
});

test("C2-16 a recorded denial of ever having had the drug satisfies a washout; silence does not", () => {
  const source = chart("否认多西他赛用药史。");
  const denied = source.fact("否认多西他赛用药史", { variable: "docetaxel", polarity: "negated" });
  const criterion = {
    id: "crt-washout", kind: "exclusion", criterionType: "prior_treatment",
    requirement: { op: "elapsed_since", variable: "docetaxel", days: 28 },
  };
  assert.equal(evaluateCriterion(criterion, { facts: [denied], asOf: Date.parse(AS_OF) }).state, SATISFIED);
  assert.equal(evaluateCriterion(criterion, { facts: [], asOf: Date.parse(AS_OF) }).state, UNKNOWN);
  // And a protocol that does not accept 「从未用过」 as an answer can say so.
  const strict = { ...criterion, requirement: { ...criterion.requirement, deniedSatisfies: false } };
  assert.equal(evaluateCriterion(strict, { facts: [denied], asOf: Date.parse(AS_OF) }).state, UNKNOWN);
});

test("C2-20 the difference between two evaluation runs is reported and never gated", () => {
  const diff = matchingReportDiff(
    { provenance: { modelId: "m-1", promptVersion: "p-3" }, criterion: { agreement: 0.90, unknownRate: 0.2, unknownReadAsSatisfied: 0, satisfiedReadAsNotSatisfied: 2 }, subject: { eligibleRecall: 0.6, falseExclusionRate: 0.4, numberNeededToScreen: 2 } },
    { provenance: { modelId: "m-2", promptVersion: "p-4" }, criterion: { agreement: 0.95, unknownRate: 0.1, unknownReadAsSatisfied: 1, satisfiedReadAsNotSatisfied: 1 }, subject: { eligibleRecall: 0.8, falseExclusionRate: 0.2, numberNeededToScreen: null } },
  );
  assert.equal(diff.versions.previous.modelId, "m-1");
  assert.equal(diff.versions.current.promptVersion, "p-4");
  assert.ok(Math.abs(diff.criterionAgreement.change - 0.05) < 1e-9);
  assert.equal(diff.unknownReadAsSatisfied.change, 1, "a direction that got worse is shown, not hidden");
  assert.equal(diff.numberNeededToScreen.change, null, "a missing number is null, not zero");
  assert.equal(diff.gated, false);
  assert.match(diff.note, /不门控/);
});

test("an assessment carries which model and prompt produced its language judgments", () => {
  const assessment = assessSubject({
    subjectKey: "S1", asOf: AS_OF, criteria: [], facts: [],
    provenance: { modelId: "deepseek-v4", promptVersion: "vcr-matching@1.0.0", criteriaVersion: "prt-1@2" },
  });
  assert.equal(assessment.provenance.modelId, "deepseek-v4");
  assert.equal(matchingAssessmentDocument(assessment).provenance.criteriaVersion, "prt-1@2");
  assert.equal(assessSubject({ subjectKey: "S1", asOf: AS_OF, criteria: [], facts: [] }).provenance.vocabularyVersion, "evimed-internal-sex-1");
});

// ------------------------------------------------ the capability package

test("the capability declares itself the way the module needs it to", async () => {
  const yaml = await readFile(path.join(repoRoot, "capabilities", "vcr-matching", "capability.yaml"), "utf8");
  const manifest = YAML.parse(yaml);
  assert.equal(manifest.id, "vcr-matching");
  // Public, because a session is bound to it by the module; `internal` would
  // make that binding answer 403. Off the catalogue, because the entry point is
  // the study page, not 科研工具.
  assert.equal(manifest.visibility ?? "public", "public");
  assert.equal(manifest.display.listed, false);
  // Clinical because of what it writes — the questionnaire and the patient
  // explanation — not because of what it decides.
  assert.equal(manifest.safetyClass, "clinical");
  assert.deepEqual(manifest.produces.map((item) => item.contractKind), ["vcr-matching-assessment"]);
  const required = manifest.produces[0].outputs.filter((item) => item.required !== false).map((item) => item.path);
  assert.deepEqual(required, ["matching-assessment.md", "matching.json"]);
  const validated = validateCapabilityManifest(manifest);
  assert.deepEqual(validated.issues, []);
  assert.equal(validated.ok, true);
});

test("the skill says the two things a run must not get wrong, and names its required outputs", async () => {
  const authored = await readFile(path.join(repoRoot, "capabilities", "vcr-matching", "SKILL.md"), "utf8");
  const shipped = await readFile(path.join(repoRoot, "capability-skills", "vcr-matching", "SKILL.md"), "utf8");
  assert.equal(authored, shipped, "the authored skill and the shipped copy are one document");
  assert.match(authored, /你只抽证据，判定由代码做/);
  assert.match(authored, /联系患者之前必须有人确认/);
  assert.match(authored, /逐人确认，不是批量确认/);
  assert.match(authored, /「未知」永远不是「不满足」/u);
  assert.match(authored, /只要有一条适用的排除标准是「未知」，这个人就不能是「符合」/u);
  for (const name of ["matching-assessment.md", "matching.json"]) assert.ok(authored.includes(name), name);
});

test("AC-14 the contract refuses a package whose own judgments do not produce its summary", async () => {
  // This was a run-side `preflight.py` until the platform's rule caught up
  // with it: a checker that restates delivery rules is the copy that drifts
  // (clinicalEvidenceSingleImplementation.test.mjs). The same two properties
  // now live once, in `@evimed/domain`'s vcr contract, and the gate returns
  // them to the run — where a package built from this package's own evaluator
  // is the passing case, so it cannot drift from what the code produces.
  const { vcrMatchingFindings } = await import("@evimed/domain");
  const source = chart("男，67 岁。否认心梗史。");
  const assessment = assessSubject({
    subjectKey: "S1", asOf: AS_OF, documents: source.documents,
    criteria: [CRITERION_MI, {
      id: "crt-washout", kind: "exclusion", criterionType: "prior_treatment",
      requirement: { op: "elapsed_since", variable: "docetaxel", days: 28 },
    }],
    facts: [source.fact("否认心梗史", { variable: "myocardial_infarction", polarity: "negated" })],
  });
  const document = matchingAssessmentDocument(assessment);
  assert.equal(document.summary, "insufficient_evidence");

  const of = (/** @type {any} */ value) => vcrMatchingFindings({ files: new Map([["matching.json", JSON.stringify(value)]]) });
  const clean = of(document);
  assert.deepEqual(clean.issues.filter((issue) => issue.code === "vcr_summary_contradicted"), []);
  assert.equal(clean.metrics.vcrMatchingSummary, "insufficient_evidence");

  // The same package claiming 「符合」 over an unknown exclusion criterion.
  const contradicted = of({ ...document, summary: "eligible" });
  assert.ok(contradicted.issues.some((issue) => issue.code === "vcr_summary_contradicted"),
    "an unknown exclusion criterion never leaves a subject eligible");
  assert.ok(contradicted.issues.every((issue) => issue.severity === "advisory"),
    "the finding is returned to the run, never used to withhold the package");

  // And 「不适用」 written as a fifth state rather than as the field beside it.
  const fifthState = of({
    ...document, summary: "insufficient_evidence",
    judgments: [{ criterionId: "crt-x", state: "not_applicable", applicable: true, evidence: [] }],
  });
  assert.ok(fifthState.issues.some((issue) => issue.code === "vcr_judgment_state_unknown"));
  assert.equal(fifthState.metrics.vcrJudgmentsBadState, 1);
});

test("the eval pack carries real briefs, and every one of them names the input the manifest requires", async () => {
  const briefs = JSON.parse(await readFile(path.join(repoRoot, "evals", "vcr-matching", "briefs.json"), "utf8"));
  assert.equal(briefs.capability, "vcr-matching");
  assert.ok(briefs.briefs.length >= 3, `only ${briefs.briefs.length} briefs`);
  const ids = briefs.briefs.map((brief) => brief.id);
  assert.equal(new Set(ids).size, ids.length);
  for (const brief of briefs.briefs) {
    assert.ok(brief.inputs.studyId, brief.id);
    assert.ok(brief.mustDo.length >= 3 && brief.mustNotDo.length >= 3, brief.id);
  }
  // The two measurement briefs are the ones AC-36 and AC-37 are answered by.
  assert.ok(ids.some((id) => id.includes("historical-replay")), "AC-36 needs a replay brief");
  assert.ok(ids.some((id) => id.includes("accrual-forecast-backtest")), "AC-37 needs a backtest brief");
});

test('C2-25 declared code vocabulary versions cannot silently select the current mapping', () => {
  const node = { op: 'compare', variable: 'sex', comparator: 'eq', value: 'female' };
  const fact = { id: 'versioned', variable: 'sex', value: 'F', extractedBy: 'snapshot', source: { vocabularyVersion: 'unknown-vocabulary-2' } };
  const unknown = evaluateRequirement(node, { facts: [fact], asOf: Date.parse(AS_OF) });
  assert.equal(unknown.state, UNKNOWN);
  assert.equal(unknown.missing[0].reason, 'coding_version_unavailable');
  const assessed = assessSubject({ subjectKey: 'heldout', asOf: AS_OF, facts: [{ ...fact, visibleAt: AS_OF }], criteria: [{ id: 'sex', kind: 'inclusion', requirement: node }] });
  assert.equal(assessed.judgments[0].state, UNKNOWN);
  assert.ok(assessed.provenance.vocabularyVersion);
});


test('clinical context and medication states change eligibility without changing supported quotes', () => {
  const source = chart('父亲有心梗史。患者可能心梗。拟于2026-10-02使用多西他赛。');
  const metadata = { schema:1, assertion:'affirmed', experiencer:'family' };
  const assess = facts => assessSubject({ asOf:'2026-10-09', criteria:[{...CRITERION_MI,requirement:{op:'absent',variable:'myocardial_infarction'}}], facts,documents:source.documents });
  assert.equal(assess([source.fact('父亲有心梗史', {variable:'myocardial_infarction',clinical:metadata})]).summary,'insufficient_evidence');
  assert.equal(assess([source.fact('患者可能心梗', {variable:'myocardial_infarction',clinical:{...metadata,experiencer:'patient',assertion:'possible'}})]).summary,'insufficient_evidence');
  const washout={id:'washout',kind:'exclusion',requirement:{op:'elapsed_since',variable:'docetaxel',days:28}};
  for (const state of ['prescribed','planned','historical_list','unknown']) {
    const fact=source.fact('多西他赛',{variable:'docetaxel',occurredAt:'2026-08-01',clinical:{...metadata,experiencer:'patient',medication:{state}}});
    assert.equal(evaluateCriterion(washout,{facts:[fact],asOf:Date.parse('2026-10-09')}).state,UNKNOWN,state);
  }
  const copied=source.fact('多西他赛',{variable:'docetaxel',occurredAt:'2026-08-01',clinical:{...metadata,experiencer:'patient',copiedFrom:'original',medication:{state:'administered'}}});
  assert.equal(evaluateCriterion(washout,{facts:[copied],asOf:Date.parse('2026-10-09')}).state,UNKNOWN);
});

test('same-event conflicting lab results stay unknown; a visible sourced correction changes only the current view', () => {
  const source=chart('肌酐 1.2 mg/dL。复核肌酐 2.4 mg/dL。');
  const clinical={schema:1,assertion:'affirmed',experiencer:'patient',eventId:'sample_1'};
  const first=source.fact('肌酐 1.2 mg/dL',{id:'first',subjectKey:'p1',variable:'creatinine',value:1.2,unit:'mg/dL',clinical});
  const second=source.fact('复核肌酐 2.4 mg/dL',{id:'second',subjectKey:'p1',variable:'creatinine',value:2.4,unit:'mg/dL',clinical});
  const criteria=[{id:'lab',kind:'inclusion',requirement:{op:'compare',variable:'creatinine',comparator:'lte',value:1.5,unit:'mg/dL'}}];
  const assess=(facts,asOf='2026-10-09')=>assessSubject({criteria,facts,asOf,documents:source.documents});
  assert.equal(assess([first,second]).summary,'insufficient_evidence');
  const correction={...second,createdAt:'2026-10-02',clinical:{...clinical,correctionOf:'first',correctionReason:'Confirmed corrected report'}};
  assert.equal(assess([first,correction],'2026-10-01').summary,'eligible');
  assert.equal(assess([first,correction]).summary,'ineligible');
});

test('a model cannot attach a guessed unit to a quote that omits it, or bypass units with equality',()=>{
  const source=chart('2026-09-01患者血肌酐1.0，单位未记载。');
  const clinical={schema:1,assertion:'affirmed',experiencer:'patient',laboratory:{originalValue:1,originalUnit:'未给单位'}};
  const guessed=source.fact('血肌酐1.0',{variable:'creatinine',value:1,unit:'mg/dL',clinical});
  const verified=verifyFactEvidence(guessed,{documents:source.documents});
  assert.deepEqual(verified,{ok:false,reason:'unit_not_in_span'});
  const criterion={id:'lab',kind:'inclusion',requirement:{op:'compare',variable:'creatinine',comparator:'lte',value:1.5,unit:'mg/dL'}};
  assert.equal(assessSubject({criteria:[criterion],facts:[guessed],documents:source.documents,asOf:AS_OF}).summary,'insufficient_evidence');
  assert.equal(evaluateCriterion(criterion,{facts:[guessed],asOf:Date.parse(AS_OF)}).state,UNKNOWN);
  const equal={...criterion,requirement:{...criterion.requirement,comparator:'eq',value:88.4,unit:'umol/L'}};
  assert.equal(evaluateCriterion(equal,{facts:[{variable:'creatinine',value:1,unit:'mg/dL'}],asOf:Date.parse(AS_OF)}).state,SATISFIED);
  assert.equal(evaluateCriterion(equal,{facts:[{variable:'creatinine',value:88.4}],asOf:Date.parse(AS_OF)}).state,UNKNOWN);
});


test('a current medication denial does not establish absence throughout a lookback window',()=>{
  const criterion={id:'history',kind:'inclusion',requirement:{op:'absent',variable:'docetaxel',window:{days:30}}};
  const asOf=Date.parse('2026-10-09T00:00:00Z');
  const clinical={schema:1,assertion:'negated',experiencer:'patient',medication:{state:'unknown',absenceScope:'current'}};
  const fact={id:'denial',variable:'docetaxel',polarity:'negated',clinical};
  const evaluate=clinical=>evaluateCriterion(criterion,{facts:[{...fact,clinical}],asOf}).state;
  assert.equal(evaluate(clinical),UNKNOWN);
  assert.equal(evaluate({...clinical,medication:{state:'unknown',absenceScope:'never'}}),SATISFIED);
  const scoped={...clinical,medication:{state:'unknown',absenceScope:'interval'},occurredInterval:{start:'2026-09-09',end:'2026-10-09'}};
  assert.equal(evaluate(scoped),SATISFIED);
  assert.equal(evaluate({...scoped,occurredInterval:{start:'2026-09-10',end:'2026-10-09'}}),UNKNOWN);
  assert.equal(evaluate({...scoped,occurredInterval:{start:'2026-09-09',end:'2026-10-08'}}),UNKNOWN);
  assert.equal(evaluateCriterion(criterion,{facts:[{...fact,clinical:null}],asOf}).state,SATISFIED);
});
