// The recruitment side: the referral ledger and the contact gate in front of
// it, the site profile, the accrual forecast's inputs and its backtest, and
// follow-up episodes that keep an exit record an exit record.
//
// The case numbers are the plan's §12 acceptance ids; they are in the titles so
// the acceptance table can be generated by grepping for them.
import assert from "node:assert/strict";
import test from "node:test";

import {
  VCR_ACCRUAL_MEASURES, VCR_ACCRUAL_PRIOR_DEFAULT, VCR_EXIT_VERBATIM_FIELDS, VCR_PARTNER_DATA_USES, VCR_RECRUIT_REFUSALS,
  VCR_REFERRAL_TRANSITIONS, VCR_RISK_APPETITE_QUANTILES, VCR_SITE_VERIFICATION_STALE_DAYS,
  VCR_TRIAL_RESTRICTED_FIELDS, accrualBacktestSlices, accrualForecastScenario, accrualPosterior,
  backtestAccrualCoverage, candidateReferrals, decideContactApproval, decideReferralTransition,
  deriveFromExit, followupFidelityFindings, isSiteScopedRole, parseProbabilityByMonth, partnerDataUseAllowed, postExitEpisode, readAccrualForecast,
  referralFunnel, requestAccrualForecast, screenFailuresByCriterion, siteProfileStatus, trialPeriodEpisode,
  wilsonInterval,
} from "../src/vcrRecruit.mjs";
import { VCR_CONTACT_STATES, VCR_JOB_METHODS, VCR_REFERRAL_STATES, roleAllows, validateEngineJob } from "@evimed/domain";

const candidate = (over = {}) => ({ id: "ref-1", studyId: "std-1", subjectKey: "S1", state: "candidate", ...over });

// ------------------------------------------------------------- the ledger

test("the ledger's transitions are the plan's, and every state is reachable and accounted for", () => {
  assert.deepEqual(Object.keys(VCR_REFERRAL_TRANSITIONS).sort(), [...VCR_REFERRAL_STATES].sort(),
    "every referral state has a row, or a state exists that nobody can leave");
  const reachable = new Set(["candidate"]);
  let grew = true;
  while (grew) {
    grew = false;
    for (const [from, tos] of Object.entries(VCR_REFERRAL_TRANSITIONS)) {
      if (!reachable.has(from)) continue;
      for (const to of tos) if (!reachable.has(to)) { reachable.add(to); grew = true; }
    }
  }
  assert.deepEqual([...reachable].sort(), [...VCR_REFERRAL_STATES].sort(), "a state nothing reaches is a state nobody can record");
  assert.deepEqual(VCR_REFERRAL_TRANSITIONS.screen_failed, [], "a screen failure is terminal; a retry is a new referral");
});

test("a transition the ledger does not allow is refused by name, not silently ignored", () => {
  const skipped = decideReferralTransition({ referral: candidate(), to: "enrolled", role: "recruiter" });
  assert.equal(skipped.ok, false);
  assert.equal(skipped.code, "vcr_referral_transition_invalid");
  assert.match(skipped.message, /候选|candidate/);
  const nonsense = decideReferralTransition({ referral: candidate(), to: "teleported", role: "recruiter" });
  assert.equal(nonsense.code, "vcr_referral_state_unknown");
  for (const code of [skipped.code, nonsense.code]) assert.ok(VCR_RECRUIT_REFUSALS.includes(code), code);
});

// ------------------------------------------------------------- AC-18

test("AC-18 no referral may enter a contact state without a named per-person confirmation", () => {
  // The walk is over the vocabulary, not over a list written here: a fourth
  // contact state added to the domain is gated the day it is added.
  assert.ok(VCR_CONTACT_STATES.length >= 3);
  for (const to of VCR_CONTACT_STATES) {
    const from = Object.entries(VCR_REFERRAL_TRANSITIONS).find(([, tos]) => tos.includes(to))?.[0];
    assert.ok(from, `nothing reaches ${to}`);
    const refused = decideReferralTransition({ referral: candidate({ state: from }), to, role: "recruiter" });
    assert.equal(refused.ok, false, `${from} → ${to} must stop`);
    assert.equal(refused.code, "vcr_contact_not_approved");
    assert.match(refused.message, /逐人确认/);
    const allowed = decideReferralTransition({
      referral: candidate({ state: from, contactApprovedBy: "coordinator-li" }), to, role: "recruiter",
    });
    assert.equal(allowed.ok, true, `${from} → ${to} with a confirmation`);
  }
});

test("AC-18 a role that may not contact patients is refused before the approval is even looked at", () => {
  assert.equal(roleAllows("site", "contact_patients"), false);
  assert.equal(roleAllows("site", "write_referrals"), true);
  // A site on its own referral: the site scope passes, the contact stop does not.
  const refused = decideReferralTransition({
    referral: candidate({ state: "contactable", contactApprovedBy: "coordinator-li", siteId: "ste-1" }), to: "contacted",
    role: "site", actorSiteId: "ste-1",
  });
  assert.equal(refused.code, "vcr_contact_role_forbidden");
  const viewer = decideReferralTransition({ referral: candidate(), to: "contactable", role: "viewer" });
  assert.equal(viewer.code, "vcr_referral_role_forbidden");
  for (const role of ["recruiter", "lead"]) {
    assert.equal(roleAllows(role, "contact_patients"), true, role);
  }
});

test("CS-29 a request cannot name the person who approved: the stop reads the stored row and only the stored row", () => {
  // The whole of the old hole: a patch carrying `contactApprovedBy` satisfied
  // the check, so anyone could pass the stop as anybody.
  const forged = decideReferralTransition({
    referral: candidate({ state: "contactable" }), to: "contacted", role: "recruiter", patch: { contactApprovedBy: "coordinator-li" },
  });
  assert.equal(forged.ok, false);
  assert.equal(forged.code, "vcr_contact_not_approved");
  // And where a move is allowed, the approver is not carried into what the store writes.
  const allowed = decideReferralTransition({
    referral: candidate({ state: "contactable", contactApprovedBy: "coordinator-li" }), to: "contacted", role: "recruiter",
    patch: { contactApprovedBy: "someone-else", screenFailReason: "kept" },
  });
  assert.equal(allowed.ok, true);
  assert.deepEqual(allowed.patch, { screenFailReason: "kept" });
});

test("CS-30 the study lead moves the ledger through the contact states; a site moves only its own site's referrals", () => {
  assert.equal(roleAllows("lead", "write_referrals"), false, "the lead holds no write_referrals: contact_patients is what carries it");
  for (const to of ["contactable", "contacted"]) {
    const from = to === "contactable" ? "candidate" : "contactable";
    const decision = decideReferralTransition({
      referral: candidate({ state: from, contactApprovedBy: "lead-1" }), to, role: "lead",
    });
    assert.equal(decision.ok, true, `lead: ${from} → ${to}`);
  }
  assert.equal(isSiteScopedRole("site"), true);
  for (const role of ["lead", "recruiter", "viewer", "data_manager", "clinical_reviewer"]) assert.equal(isSiteScopedRole(role), false, role);

  const own = candidate({ state: "site_responded", siteId: "ste-1" });
  assert.equal(decideReferralTransition({ referral: own, to: "screening", role: "site", actorSiteId: "ste-1" }).ok, true);
  for (const [label, input] of /** @type {[string, any][]} */ ([
    ["another site's referral", { referral: candidate({ state: "site_responded", siteId: "ste-2" }), actorSiteId: "ste-1" }],
    ["a referral with no site", { referral: candidate({ state: "site_responded" }), actorSiteId: "ste-1" }],
    ["a site account with no site of its own", { referral: own, actorSiteId: null }],
    ["moving a referral to another site", { referral: own, actorSiteId: "ste-1", patch: { siteId: "ste-2" } }],
  ])) {
    const refused = decideReferralTransition({ to: "screening", role: "site", ...input });
    assert.equal(refused.code, "vcr_referral_role_forbidden", label);
    assert.match(refused.message, /本中心/, label);
  }
});

test("AC-18 contact confirmation is per person: a list is refused and an anonymous confirmation is refused", () => {
  assert.equal(decideContactApproval({ referralId: ["ref-1", "ref-2"], approvedBy: "coordinator-li", role: "recruiter" }).code,
    "vcr_contact_approval_not_per_person");
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "  ", role: "recruiter" }).code, "vcr_contact_not_approved");
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "coordinator-li", role: "site" }).code, "vcr_contact_role_forbidden");
  const ok = decideContactApproval({ referralId: "ref-1", approvedBy: " coordinator-li ", role: "recruiter" });
  assert.deepEqual(ok, { ok: true, referralId: "ref-1", approvedBy: "coordinator-li" });
  // A person holding several roles is judged on the union: the role that
  // carries the ability decides, whichever order they are listed in.
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "li", role: ["site", "viewer"] }).code, "vcr_contact_role_forbidden");
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "li", role: ["viewer", "lead"] }).ok, true);
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "li", role: [] }).code, "vcr_contact_role_forbidden");
});

test("AC-18 candidates are generated as candidates: nothing that runs unattended enters a contact state", () => {
  const referrals = candidateReferrals({
    studyId: "std-1",
    assessments: [
      { id: "mas-1", subjectKey: "S1", summary: "eligible" },
      { id: "mas-2", subjectKey: "S2", summary: "insufficient_evidence" },
      { id: "mas-3", subjectKey: "S3", summary: "ineligible" },
      { id: "mas-4", subjectKey: "S4", summary: "pending" },
    ],
  });
  assert.deepEqual(referrals.map((item) => item.subjectKey), ["S1", "S2", "S4"]);
  for (const referral of referrals) {
    assert.equal(VCR_CONTACT_STATES.includes(referral.state), false, referral.subjectKey);
  }
  assert.equal(referrals.find((item) => item.subjectKey === "S2").state, "needs_evidence");
});

test("a candidate with unknown criteria may still be contacted, but the coordinator is told what is missing", () => {
  const decision = decideReferralTransition({
    referral: candidate({ eligibilitySummary: "insufficient_evidence" }), to: "contactable", role: "recruiter",
  });
  assert.equal(decision.ok, true, "an advisory is not a gate (principle 4)");
  assert.equal(decision.notices.length, 1);
  assert.match(decision.notices[0], /未知的入排条件/);
});

// ------------------------------------------------- screening and the funnel

test("a screen failure must name the criterion it failed, and an enrolment must carry its date", () => {
  const screening = candidate({ state: "screening" });
  assert.equal(decideReferralTransition({ referral: screening, to: "screen_failed", role: "recruiter" }).code,
    "vcr_screen_failure_needs_criterion");
  assert.equal(decideReferralTransition({
    referral: screening, to: "screen_failed", role: "recruiter", patch: { screenFailCriterionId: "crt-mi" },
  }).ok, true);
  assert.equal(decideReferralTransition({ referral: screening, to: "enrolled", role: "recruiter" }).code, "vcr_enrollment_needs_date");
  assert.equal(decideReferralTransition({
    referral: screening, to: "enrolled", role: "recruiter", patch: { enrolledOn: "2026-09-20" },
  }).ok, true);
});

test("screen failures hang on the criterion, and the ones that do not are counted rather than dropped", () => {
  const criteria = [
    { id: "crt-mi", ordinal: 2, kind: "exclusion", criterionType: "time_window", sourceText: "近 6 个月内心梗者除外" },
    { id: "crt-creat", ordinal: 4, kind: "inclusion", criterionType: "lab", sourceText: "血肌酐 ≤ 1.5 mg/dL" },
  ];
  const referrals = [
    { subjectKey: "S1", state: "screen_failed", screenFailCriterionId: "crt-mi" },
    { subjectKey: "S2", state: "screen_failed", screenFailCriterionId: "crt-mi" },
    { subjectKey: "S3", state: "screen_failed", screenFailCriterionId: "crt-creat" },
    { subjectKey: "S4", state: "screen_failed", screenFailCriterionId: null },
    { subjectKey: "S5", state: "enrolled" },
  ];
  const { rows, unattributed } = screenFailuresByCriterion(referrals, criteria);
  assert.equal(rows[0].criterionId, "crt-mi");
  assert.equal(rows[0].failures, 2);
  assert.equal(rows[0].sourceText, "近 6 个月内心梗者除外");
  assert.deepEqual(rows[0].subjectKeys, ["S1", "S2"]);
  assert.equal(rows[1].failures, 1);
  assert.equal(unattributed, 1, "a free-text screen failure is visible as a gap, not folded in");
});

test("the funnel shows every rate with the denominator it was divided by", () => {
  const funnel = referralFunnel([
    { state: "candidate" }, { state: "candidate" }, { state: "contactable" },
    { state: "contacted" }, { state: "referred" }, { state: "screening" },
    { state: "enrolled" }, { state: "screen_failed" },
  ]);
  assert.equal(funnel.total, 8);
  assert.equal(funnel.counts.candidate, 2);
  assert.equal(funnel.contactRate, 5 / 8);
  assert.equal(funnel.screenRate, 3 / 5);
  assert.equal(funnel.enrollmentRate, 1 / 3);
  assert.equal(funnel.screenFailureRate, 1 / 3);
  assert.equal(referralFunnel([]).contactRate, null, "an empty ledger has no rate, not a zero");
});

// --------------------------------------------------------- the site profile

test("a site claims a capacity only with a verification date behind it", () => {
  const now = Date.parse("2026-09-28T00:00:00Z");
  const fresh = siteProfileStatus({
    id: "ste-1", name: "某三甲医院", capacity: { slots: 12, used: 4 },
    competing: ["NCT0000001"], verifiedAt: "2026-09-01T00:00:00Z",
    capability: { unmet: ["中心药房 -20℃ 冰箱"] },
  }, now);
  assert.equal(fresh.slotsAvailable, 8);
  assert.equal(fresh.stale, false);
  assert.equal(fresh.capacityClaimable, true);
  assert.deepEqual(fresh.unmetRequirements, ["中心药房 -20℃ 冰箱"]);

  const old = siteProfileStatus({ id: "ste-2", capacity: { slots: 30 }, verifiedAt: "2026-01-01T00:00:00Z" }, now);
  assert.equal(old.stale, true);
  assert.equal(old.capacityClaimable, false, "a number nobody rechecked is not a claim");
  assert.ok(old.verificationAgeDays > VCR_SITE_VERIFICATION_STALE_DAYS);

  const never = siteProfileStatus({ id: "ste-3", capacity: { slots: 30 } }, now);
  assert.equal(never.verificationAgeDays, null);
  assert.equal(never.capacityClaimable, false);
});

// ------------------------------------------------------------- AC-37

test("AC-37 the Poisson–Gamma prior is updated from the site's own open months, not the study clock", () => {
  const fitted = accrualPosterior({ enrolled: 7, monthsOpen: 9 }, { alpha: 1, beta: 1 });
  assert.equal(fitted.alpha, 8);
  assert.equal(fitted.beta, 10);
  assert.equal(fitted.meanRatePerMonth, 0.8);
  assert.equal(fitted.source, "site_history");

  const unopened = accrualPosterior({ enrolled: 0, monthsOpen: 0 });
  assert.deepEqual(
    { alpha: unopened.alpha, beta: unopened.beta, source: unopened.source },
    { alpha: VCR_ACCRUAL_PRIOR_DEFAULT.alpha, beta: VCR_ACCRUAL_PRIOR_DEFAULT.beta, source: "prior_only" },
  );
  // A late site with two months open and two patients is fast, not slow: using
  // the study's own elapsed months would have made it look like 0.2/month.
  const late = accrualPosterior({ enrolled: 2, monthsOpen: 2 });
  assert.equal(late.meanRatePerMonth, 1);
});

test("AC-37 the forecast is exactly the engine's contract: one posterior per site, months from now, the target and nothing else", () => {
  const { scenario, notes } = accrualForecastScenario({
    target: 120, asOf: "2026-09-28T00:00:00Z", screenFailure: { failed: 6, passed: 14 }, eventTarget: 80, eventHazard: 0.05, byTimes: [6, 12, 18],
    sites: [
      { id: "ste-1", name: "A", activatedOn: "2026-05-01", capacity: { slots: 40, activationPlannedOn: "2026-04-15" } },
      { id: "ste-2", name: "B", activatedOn: null, capacity: { slots: 20, activationPlannedOn: "2026-11-28" },
        accrualPrior: { alpha: 2, beta: 4 } },
      { id: "ste-3", name: "C", capacity: {} },
    ],
    siteHistories: { "ste-1": { enrolled: 12, monthsOpen: 4 } },
  });
  // The keys are the schema's, so the job validates against the domain's own scenario schema.
  assert.deepEqual(Object.keys(scenario).sort(), ["byTimes", "eventHazard", "eventTarget", "screenFailure", "sites", "target"]);
  assert.deepEqual(scenario.sites[0], { id: "ste-1", alpha: 13, beta: 5, startTime: 0, enrolled: 12, exposureTime: 4 },
    "an open site contributes from now; its posterior is the prior plus what it enrolled and the months it was open");
  assert.equal(scenario.sites[1].alpha, 2);
  assert.equal(scenario.sites[1].beta, 4);
  assert.ok(Math.abs(scenario.sites[1].startTime - 2) < 0.01, "activation planned two months ahead");
  assert.equal(Object.hasOwn(scenario.sites[1], "enrolled"), false, "the engine takes enrolled and exposureTime together or neither");
  assert.deepEqual(scenario.screenFailure, { alpha: 7, beta: 15 }, "Beta(failed + 1, passed + 1)");
  assert.deepEqual(notes.defaultedSites, ["ste-3"], "a site with no prior and no history runs on the weak default, and the request says so");
  assert.equal(notes.screenFailureUnavailable, false);

  const bare = accrualForecastScenario({ target: 60, asOf: "2026-09-28T00:00:00Z", sites: [{ id: "s" }] });
  assert.equal(Object.hasOwn(bare.scenario, "screenFailure"), false, "no screening history, no screenFailure: never Beta(1, 1) passed off as data");
  assert.equal(bare.notes.screenFailureUnavailable, true);
  assert.deepEqual(validateEngineJob({
    jobId: "job_1", studyId: "std_1", kind: "accrual_forecast", method: "accrual.poisson_gamma", methodVersion: "1.0.0",
    protocolVersion: 1, seed: 7, cpuSecondsLimit: 60, inputs: [], scenario,
  }), []);
});

test("AC-37 the forecast is queued on the deterministic engine through the injected job port", async () => {
  /** @type {any[]} */
  const queued = [];
  const jobs = { enqueue: async (job) => { queued.push(job); return { job: { id: "job-1", state: "queued" } }; } };
  const { scenario } = accrualForecastScenario({ target: 60, asOf: "2026-09-28T00:00:00Z", sites: [{ id: "s1" }] });
  const handle = await requestAccrualForecast({ jobs, studyId: "std-1", userId: "u-1", scenario, requestedBy: "matching" });
  assert.equal(handle.job.id, "job-1");
  assert.equal(queued.length, 1);
  assert.equal(queued[0].kind, "accrual_forecast");
  assert.equal(queued[0].studyId, "std-1");
  assert.equal(queued[0].userId, "u-1", "the queue needs the account the job is for");
  assert.equal(queued[0].scenario.target, 60);
  assert.deepEqual(queued[0].detail.keepTables, ["probability_by_month"], "the table a page draws the probability curve from is kept");
  assert.equal(VCR_JOB_METHODS.accrual_forecast, "accrual.poisson_gamma", "the engine method this kind maps to");
  await assert.rejects(() => requestAccrualForecast({ jobs, studyId: "std-1", userId: "u-1", scenario: { kind: "design" } }), /accrual scenario/);
  await assert.rejects(() => requestAccrualForecast({ jobs: null, studyId: "std-1", userId: "u-1", scenario }), /jobs port/);
});

test("AC-37 the forecast reads the engine's own measures, and an interval that does not name its kind is dropped rather than relabelled", () => {
  const read = readAccrualForecast({
    status: "succeeded",
    measures: [
      { name: "last_patient_in_months", value: 18.4, interval: { kind: "prediction", low: 15.1, high: 23.9 } },
      { name: "target_events_months", value: 26.0, interval: { low: 22, high: 31 } },
    ],
    diagnostics: { quantiles: { p20: 15.8, p50: 18.4, p80: 21.7 } },
  }, { probabilityByMonth: parseProbabilityByMonth("month,probability,mcse\n6,0.05,0.01\n12,0.4,0.01\n18,0.8,NA\n") });
  assert.equal(read.lastPatientIn.value, 18.4);
  assert.equal(read.targetEventsReached, null, "an unnamed interval is not a prediction interval");
  assert.deepEqual(read.droppedUnnamedIntervals, ["target_events_months"]);
  assert.deepEqual(read.probabilityByMonth, [{ month: 6, probability: 0.05 }, { month: 12, probability: 0.4 }, { month: 18, probability: 0.8 }]);
  assert.deepEqual(Object.keys(read.commitments).sort(), ["aggressive", "balanced", "conservative"]);
  assert.equal(read.commitments.conservative.quantile, VCR_RISK_APPETITE_QUANTILES.conservative);
  assert.match(read.commitments.balanced.note, /不是预测更准/);
  assert.deepEqual(VCR_ACCRUAL_MEASURES, { lastPatientIn: "last_patient_in_months", targetEvents: "target_events_months" });
});

test("AC-37 the backtest reports the measured coverage of the 80% prediction intervals, with no pass mark", () => {
  const slice = (low, high, actual, kind = "prediction") => ({ asOf: "2026-01-01T00:00:00Z", interval: { kind, low, high }, actual });
  const report = backtestAccrualCoverage({
    slices: [
      slice(10, 20, 15), slice(10, 20, 19), slice(10, 20, 25), slice(30, 40, 35), slice(30, 40, 29),
      slice(1, 2, 1.5, "confidence"), { asOf: "2026-02-01T00:00:00Z", interval: null, actual: 3 },
    ],
  });
  assert.equal(report.slices, 7);
  assert.equal(report.usable, 5);
  assert.equal(report.unusable, 2, "a confidence interval and an incomplete slice are named, not counted");
  assert.equal(report.covered, 3);
  assert.equal(report.coverage, 3 / 5);
  assert.equal(report.level, 0.8);
  assert.equal(report.calibration, "over_confident");
  assert.ok(report.coverageInterval.low < 0.6 && report.coverageInterval.high > 0.6,
    "five slices settle almost nothing, and the interval says so");
  assert.match(report.note, /不是「准确度」/);
  assert.equal(Object.hasOwn(report, "passed"), false);
  assert.equal(backtestAccrualCoverage({ slices: [] }).coverage, null);
  const wide = backtestAccrualCoverage({ slices: [slice(0, 100, 5), slice(0, 100, 5), slice(0, 100, 5)] });
  assert.equal(wide.calibration, "conservative");
});

test("AC-37 Wilson bounds, not a bare fraction", () => {
  const perfect = wilsonInterval(10, 10);
  assert.ok(perfect.low > 0.7 && perfect.low < 0.75);
  assert.ok(perfect.high > 0.999, "ten out of ten still admits the top of the range");
  const half = wilsonInterval(5, 10);
  assert.ok(half.low < 0.5 && half.high > 0.5);
  assert.deepEqual(wilsonInterval(0, 0), { low: null, high: null });
});

test("AC-37 a backtest slice is the months from the forecast to the day enrolment reached its target, and a target not yet reached is a miss only when the interval has already passed", () => {
  const slices = accrualBacktestSlices({
    now: "2026-12-15T00:00:00Z",
    forecasts: [
      // Made 1 March for a total of 4: the 4th enrolment is 2026-06-15, three and a half months later.
      { asOf: "2026-03-01T00:00:00Z", target: 4, interval: { kind: "prediction", low: 2, high: 9 } },
      // Made 1 June for 8: never reached; nine and a half months have passed, past the interval's end.
      { asOf: "2026-06-01T00:00:00Z", target: 8, interval: { kind: "prediction", low: 1, high: 4 } },
      // Made in November for 8: not reached, and the interval has not ended yet.
      { asOf: "2026-11-01T00:00:00Z", target: 8, interval: { kind: "prediction", low: 1, high: 9 } },
      { asOf: null, target: 4, interval: { kind: "prediction", low: 0, high: 99 } },
    ],
    enrollments: [
      { enrolledOn: "2026-02-10" }, { enrolledOn: "2026-03-20" }, { enrolledOn: "2026-04-05" },
      { enrolledOn: "2026-06-15" }, { enrolledOn: "2026-07-02" },
    ],
  });
  assert.equal(slices.length, 3, "a forecast with no timestamp cannot be scored and is dropped");
  assert.ok(Math.abs(/** @type {number} */ (slices[0].actual) - 3.5) < 0.1, `months from the forecast to the target: ${slices[0].actual}`);
  assert.equal(slices[1].actual, null);
  assert.ok(/** @type {number} */ (slices[1].elapsedMonths) > 4);
  assert.equal(slices[2].actual, null);
  const coverage = backtestAccrualCoverage({ slices });
  assert.equal(coverage.usable, 2);
  assert.equal(coverage.covered, 1, "the first slice contained its truth, the second had already missed");
  assert.equal(coverage.censored, 1, "the third can still land inside its interval and is not scored");
  assert.equal(coverage.rows.find((row) => row.censoredAt)?.covered, false);
});

test("C1 a subject with two assessments is one candidate, and it is the newest one", () => {
  const candidates = candidateReferrals({ studyId: "std", assessments: [
    { id: "mas-new", subjectKey: "S1", summary: "ineligible", asOf: "2026-09-28" },
    { id: "mas-old", subjectKey: "S1", summary: "eligible", asOf: "2026-08-01" },
    { id: "mas-a", subjectKey: "S2", summary: "eligible", asOf: "2026-09-28" },
    { id: "mas-b", subjectKey: "S2", summary: "pending", asOf: "2026-09-01" },
  ] });
  assert.deepEqual(candidates.map((entry) => [entry.subjectKey, entry.assessmentId, entry.state]), [["S2", "mas-a", "candidate"]]);
});

test("F1 a patient who withdrew after contact still counts as contacted", () => {
  const referrals = [
    { id: "r1", state: "enrolled" }, { id: "r2", state: "withdrawn" }, { id: "r3", state: "withdrawn" }, { id: "r4", state: "candidate" },
  ];
  const progress = new Map([["r1", "enrolled"], ["r2", "contacted"], ["r3", "screening"]]);
  const funnel = referralFunnel(referrals, progress);
  assert.equal(funnel.reachedContact, 3);
  assert.equal(funnel.reachedScreening, 2);
  assert.equal(funnel.contactRate, 3 / 4);
  assert.equal(funnel.screenRate, 2 / 3);
  assert.equal(funnel.enrollmentRate, 1 / 2);
  // Without the events only where they stand now is known, as it always was.
  assert.equal(referralFunnel(referrals).reachedContact, 1);
});

test("S1 a site that never stated its slots has no capacity claim, not a capacity of zero", () => {
  const now = Date.parse("2026-09-28T00:00:00Z");
  const status = siteProfileStatus({ id: "s", capacity: { slots: null }, verifiedAt: "2026-09-20T00:00:00Z" }, now);
  assert.equal(status.slotsAvailable, null);
  assert.equal(status.capacityClaimable, false);
  assert.equal(siteProfileStatus({ id: "s", capacity: { slots: 5, used: 2 }, verifiedAt: "2026-09-20T00:00:00Z" }, now).slotsAvailable, 3);
});

// ------------------------------------------------------------- AC-22

test("AC-22 an exit date and reason are recorded as given, and the in-trial fields stay marked invisible", () => {
  const episode = trialPeriodEpisode({
    studyId: "std-1", subjectKey: "S1",
    windowStart: "2026-03-01T00:00:00Z", exitDate: "2026-08-14", exitReason: "受试者要求退出",
    observations: [{ kind: "visit", at: "2026-05-02T00:00:00Z" }],
  });
  assert.equal(episode.exitDate, "2026-08-14");
  assert.equal(episode.exitReason, "受试者要求退出");
  assert.equal(episode.kind, "study_specific");
  assert.equal(episode.derived, false);
  for (const field of VCR_TRIAL_RESTRICTED_FIELDS) {
    assert.deepEqual(episode.restricted[field], { visible: false, reason: "restricted_in_trial" }, field);
  }
  assert.ok(VCR_TRIAL_RESTRICTED_FIELDS.includes("progression_date"));
  assert.ok(VCR_TRIAL_RESTRICTED_FIELDS.includes("randomization_arm"));
  assert.deepEqual([...VCR_EXIT_VERBATIM_FIELDS], ["exitDate", "exitReason"]);
  assert.deepEqual(followupFidelityFindings(episode, { exitDate: "2026-08-14", exitReason: "受试者要求退出" }), []);
});

test("AC-22 an exit record is never converted into a progression date, a last-dose date or an arm", () => {
  for (const field of ["progression_date", "last_dose_date", "randomization_arm"]) {
    const refusal = deriveFromExit({ field });
    assert.equal(refusal.ok, false);
    assert.equal(refusal.code, "vcr_exit_field_not_derivable");
    assert.equal(refusal.field, field);
    assert.match(refusal.message, /出组记录不能转换/);
    assert.equal(Object.hasOwn(refusal, "value"), false, "a refusal never carries a value to use anyway");
  }
  assert.ok(VCR_RECRUIT_REFUSALS.includes("vcr_exit_field_not_derivable"));
});

test("AC-22 a rewritten exit date and an unmarked restricted field are both reported, as advice", () => {
  const episode = trialPeriodEpisode({ studyId: "std-1", subjectKey: "S1", exitDate: "2026-08-14", exitReason: "疾病进展" });
  const rewritten = { ...episode, exitDate: "2026-08-01" };
  const findings = followupFidelityFindings(rewritten, { exitDate: "2026-08-14", exitReason: "疾病进展" });
  assert.deepEqual(findings.map((item) => item.code), ["vcr_exit_date_rewritten"]);
  assert.ok(findings.every((item) => item.severity === "advisory"), "the blocking budget is spent (principle 4)");

  const unmarked = { ...episode, restricted: {} };
  const codes = followupFidelityFindings(unmarked, {}).map((item) => item.code);
  assert.equal(codes.filter((code) => code === "vcr_restricted_field_not_marked").length, VCR_TRIAL_RESTRICTED_FIELDS.length);
});

test("AC-22 the post-exit window is a cohort about itself, and says so", () => {
  const episode = postExitEpisode({ studyId: "std-1", subjectKey: "S1", from: "2026-08-15T00:00:00Z" });
  assert.equal(episode.kind, "post_exit");
  assert.equal(episode.exitReason, null, "the exit belongs to the trial-period episode, not to this one");
  assert.deepEqual(episode.restricted, {});
  assert.match(episode.scope, /不代表未治疗的自然病程/);
  assert.match(episode.scope, /不代表原来入组的全体/);
  assert.deepEqual(followupFidelityFindings(episode, {}), [], "a post-exit episode owes no restriction marks");
});

test("AC-22 what partner data may and may not answer is a table in code, and an unlisted use is refused", () => {
  assert.equal(partnerDataUseAllowed("matching_evaluation").allowed, true);
  assert.equal(partnerDataUseAllowed("accrual_calibration").allowed, true);
  assert.equal(partnerDataUseAllowed("feasibility").allowed, true);
  assert.equal(partnerDataUseAllowed("post_exit_observation").allowed, true);
  assert.equal(partnerDataUseAllowed("trial_efficacy").allowed, false);
  assert.equal(partnerDataUseAllowed("external_control").allowed, false);
  assert.equal(partnerDataUseAllowed("anything_else").allowed, false, "an unlisted use defaults to refused");
  assert.equal(VCR_PARTNER_DATA_USES.filter((row) => row.allowed).length, 4);
  assert.ok(VCR_PARTNER_DATA_USES.every((row) => row.note.length > 0));
});
