// The recruitment side: the referral ledger and the contact gate in front of
// it, the site profile, the accrual forecast's inputs and its backtest, and
// follow-up episodes that keep an exit record an exit record.
//
// The case numbers are the plan's §12 acceptance ids; they are in the titles so
// the acceptance table can be generated by grepping for them.
import assert from "node:assert/strict";
import test from "node:test";

import {
  VCR_ACCRUAL_PRIOR_DEFAULT, VCR_EXIT_VERBATIM_FIELDS, VCR_PARTNER_DATA_USES, VCR_RECRUIT_REFUSALS,
  VCR_REFERRAL_TRANSITIONS, VCR_RISK_APPETITE_QUANTILES, VCR_SITE_VERIFICATION_STALE_DAYS,
  VCR_TRIAL_RESTRICTED_FIELDS, accrualBacktestSlices, accrualForecastScenario, accrualPosterior,
  backtestAccrualCoverage, candidateReferrals, decideContactApproval, decideReferralTransition,
  deriveFromExit, followupFidelityFindings, partnerDataUseAllowed, postExitEpisode, readAccrualForecast,
  referralFunnel, requestAccrualForecast, screenFailuresByCriterion, siteProfileStatus, trialPeriodEpisode,
  wilsonInterval,
} from "../src/vcrRecruit.mjs";
import { VCR_CONTACT_STATES, VCR_JOB_METHODS, VCR_REFERRAL_STATES, roleAllows } from "@evimed/domain";

const candidate = (over = {}) => ({ id: "ref-1", studyId: "std-1", subjectKey: "S1", state: "candidate", ...over });

// ------------------------------------------------------------- the ledger

test("the ledger's transitions are the plan's, and every state is reachable and accounted for", () => {
  assert.deepEqual(Object.keys(VCR_REFERRAL_TRANSITIONS).sort(), [...VCR_REFERRAL_STATES].sort(),
    "every referral state has a row, or a state exists that nobody can leave");
  const reachable = new Set(["candidate"]);
  let grew = true;
  while (grew) {
    grew = false;
    for (const [from, tos] of Object.entries(VCR_REFERRAL_TRANSITIONS)) {
      if (!reachable.has(from)) continue;
      for (const to of tos) if (!reachable.has(to)) { reachable.add(to); grew = true; }
    }
  }
  assert.deepEqual([...reachable].sort(), [...VCR_REFERRAL_STATES].sort(), "a state nothing reaches is a state nobody can record");
  assert.deepEqual(VCR_REFERRAL_TRANSITIONS.screen_failed, [], "a screen failure is terminal; a retry is a new referral");
});

test("a transition the ledger does not allow is refused by name, not silently ignored", () => {
  const skipped = decideReferralTransition({ referral: candidate(), to: "enrolled", role: "recruiter" });
  assert.equal(skipped.ok, false);
  assert.equal(skipped.code, "vcr_referral_transition_invalid");
  assert.match(skipped.message, /候选|candidate/);
  const nonsense = decideReferralTransition({ referral: candidate(), to: "teleported", role: "recruiter" });
  assert.equal(nonsense.code, "vcr_referral_state_unknown");
  for (const code of [skipped.code, nonsense.code]) assert.ok(VCR_RECRUIT_REFUSALS.includes(code), code);
});

// ------------------------------------------------------------- AC-18

test("AC-18 no referral may enter a contact state without a named per-person confirmation", () => {
  // The walk is over the vocabulary, not over a list written here: a fourth
  // contact state added to the domain is gated the day it is added.
  assert.ok(VCR_CONTACT_STATES.length >= 3);
  for (const to of VCR_CONTACT_STATES) {
    const from = Object.entries(VCR_REFERRAL_TRANSITIONS).find(([, tos]) => tos.includes(to))?.[0];
    assert.ok(from, `nothing reaches ${to}`);
    const refused = decideReferralTransition({ referral: candidate({ state: from }), to, role: "recruiter" });
    assert.equal(refused.ok, false, `${from} → ${to} must stop`);
    assert.equal(refused.code, "vcr_contact_not_approved");
    assert.match(refused.message, /逐人确认/);
    const allowed = decideReferralTransition({
      referral: candidate({ state: from, contactApprovedBy: "coordinator-li" }), to, role: "recruiter",
    });
    assert.equal(allowed.ok, true, `${from} → ${to} with a confirmation`);
  }
});

test("AC-18 a role that may not contact patients is refused before the approval is even looked at", () => {
  assert.equal(roleAllows("site", "contact_patients"), false);
  assert.equal(roleAllows("site", "write_referrals"), true);
  const refused = decideReferralTransition({
    referral: candidate({ state: "contactable", contactApprovedBy: "coordinator-li" }), to: "contacted", role: "site",
  });
  assert.equal(refused.code, "vcr_contact_role_forbidden");
  const viewer = decideReferralTransition({ referral: candidate(), to: "contactable", role: "viewer" });
  assert.equal(viewer.code, "vcr_referral_role_forbidden");
  for (const role of ["recruiter", "lead"]) {
    assert.equal(roleAllows(role, "contact_patients"), true, role);
  }
});

test("AC-18 contact confirmation is per person: a list is refused and an anonymous confirmation is refused", () => {
  assert.equal(decideContactApproval({ referralId: ["ref-1", "ref-2"], approvedBy: "coordinator-li", role: "recruiter" }).code,
    "vcr_contact_approval_not_per_person");
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "  ", role: "recruiter" }).code, "vcr_contact_not_approved");
  assert.equal(decideContactApproval({ referralId: "ref-1", approvedBy: "coordinator-li", role: "site" }).code, "vcr_contact_role_forbidden");
  const ok = decideContactApproval({ referralId: "ref-1", approvedBy: " coordinator-li ", role: "recruiter" });
  assert.deepEqual(ok, { ok: true, referralId: "ref-1", approvedBy: "coordinator-li" });
});

test("AC-18 candidates are generated as candidates: nothing that runs unattended enters a contact state", () => {
  const referrals = candidateReferrals({
    studyId: "std-1",
    assessments: [
      { id: "mas-1", subjectKey: "S1", summary: "eligible" },
      { id: "mas-2", subjectKey: "S2", summary: "insufficient_evidence" },
      { id: "mas-3", subjectKey: "S3", summary: "ineligible" },
      { id: "mas-4", subjectKey: "S4", summary: "pending" },
    ],
  });
  assert.deepEqual(referrals.map((item) => item.subjectKey), ["S1", "S2", "S4"]);
  for (const referral of referrals) {
    assert.equal(VCR_CONTACT_STATES.includes(referral.state), false, referral.subjectKey);
  }
  assert.equal(referrals.find((item) => item.subjectKey === "S2").state, "needs_evidence");
});

test("a candidate with unknown criteria may still be contacted, but the coordinator is told what is missing", () => {
  const decision = decideReferralTransition({
    referral: candidate({ eligibilitySummary: "insufficient_evidence" }), to: "contactable", role: "recruiter",
  });
  assert.equal(decision.ok, true, "an advisory is not a gate (principle 4)");
  assert.equal(decision.notices.length, 1);
  assert.match(decision.notices[0], /未知的入排条件/);
});

// ------------------------------------------------- screening and the funnel

test("a screen failure must name the criterion it failed, and an enrolment must carry its date", () => {
  const screening = candidate({ state: "screening" });
  assert.equal(decideReferralTransition({ referral: screening, to: "screen_failed", role: "recruiter" }).code,
    "vcr_screen_failure_needs_criterion");
  assert.equal(decideReferralTransition({
    referral: screening, to: "screen_failed", role: "recruiter", patch: { screenFailCriterionId: "crt-mi" },
  }).ok, true);
  assert.equal(decideReferralTransition({ referral: screening, to: "enrolled", role: "recruiter" }).code, "vcr_enrollment_needs_date");
  assert.equal(decideReferralTransition({
    referral: screening, to: "enrolled", role: "recruiter", patch: { enrolledOn: "2026-09-20" },
  }).ok, true);
});

test("screen failures hang on the criterion, and the ones that do not are counted rather than dropped", () => {
  const criteria = [
    { id: "crt-mi", ordinal: 2, kind: "exclusion", criterionType: "time_window", sourceText: "近 6 个月内心梗者除外" },
    { id: "crt-creat", ordinal: 4, kind: "inclusion", criterionType: "lab", sourceText: "血肌酐 ≤ 1.5 mg/dL" },
  ];
  const referrals = [
    { subjectKey: "S1", state: "screen_failed", screenFailCriterionId: "crt-mi" },
    { subjectKey: "S2", state: "screen_failed", screenFailCriterionId: "crt-mi" },
    { subjectKey: "S3", state: "screen_failed", screenFailCriterionId: "crt-creat" },
    { subjectKey: "S4", state: "screen_failed", screenFailCriterionId: null },
    { subjectKey: "S5", state: "enrolled" },
  ];
  const { rows, unattributed } = screenFailuresByCriterion(referrals, criteria);
  assert.equal(rows[0].criterionId, "crt-mi");
  assert.equal(rows[0].failures, 2);
  assert.equal(rows[0].sourceText, "近 6 个月内心梗者除外");
  assert.deepEqual(rows[0].subjectKeys, ["S1", "S2"]);
  assert.equal(rows[1].failures, 1);
  assert.equal(unattributed, 1, "a free-text screen failure is visible as a gap, not folded in");
});

test("the funnel shows every rate with the denominator it was divided by", () => {
  const funnel = referralFunnel([
    { state: "candidate" }, { state: "candidate" }, { state: "contactable" },
    { state: "contacted" }, { state: "referred" }, { state: "screening" },
    { state: "enrolled" }, { state: "screen_failed" },
  ]);
  assert.equal(funnel.total, 8);
  assert.equal(funnel.counts.candidate, 2);
  assert.equal(funnel.contactRate, 5 / 8);
  assert.equal(funnel.screenRate, 3 / 5);
  assert.equal(funnel.enrollmentRate, 1 / 3);
  assert.equal(funnel.screenFailureRate, 1 / 3);
  assert.equal(referralFunnel([]).contactRate, null, "an empty ledger has no rate, not a zero");
});

// --------------------------------------------------------- the site profile

test("a site claims a capacity only with a verification date behind it", () => {
  const now = Date.parse("2026-09-28T00:00:00Z");
  const fresh = siteProfileStatus({
    id: "ste-1", name: "某三甲医院", capacity: { slots: 12, used: 4 },
    competing: ["NCT0000001"], verifiedAt: "2026-09-01T00:00:00Z",
    capability: { unmet: ["中心药房 -20℃ 冰箱"] },
  }, now);
  assert.equal(fresh.slotsAvailable, 8);
  assert.equal(fresh.stale, false);
  assert.equal(fresh.capacityClaimable, true);
  assert.deepEqual(fresh.unmetRequirements, ["中心药房 -20℃ 冰箱"]);

  const old = siteProfileStatus({ id: "ste-2", capacity: { slots: 30 }, verifiedAt: "2026-01-01T00:00:00Z" }, now);
  assert.equal(old.stale, true);
  assert.equal(old.capacityClaimable, false, "a number nobody rechecked is not a claim");
  assert.ok(old.verificationAgeDays > VCR_SITE_VERIFICATION_STALE_DAYS);

  const never = siteProfileStatus({ id: "ste-3", capacity: { slots: 30 } }, now);
  assert.equal(never.verificationAgeDays, null);
  assert.equal(never.capacityClaimable, false);
});

// ------------------------------------------------------------- AC-37

test("AC-37 the Poisson–Gamma prior is updated from the site's own open months, not the study clock", () => {
  const fitted = accrualPosterior({ enrolled: 7, monthsOpen: 9 }, { alpha: 1, beta: 1 });
  assert.equal(fitted.alpha, 8);
  assert.equal(fitted.beta, 10);
  assert.equal(fitted.meanRatePerMonth, 0.8);
  assert.equal(fitted.source, "site_history");

  const unopened = accrualPosterior({ enrolled: 0, monthsOpen: 0 });
  assert.deepEqual(
    { alpha: unopened.alpha, beta: unopened.beta, source: unopened.source },
    { alpha: VCR_ACCRUAL_PRIOR_DEFAULT.alpha, beta: VCR_ACCRUAL_PRIOR_DEFAULT.beta, source: "prior_only" },
  );
  // A late site with two months open and two patients is fast, not slow: using
  // the study's own elapsed months would have made it look like 0.2/month.
  const late = accrualPosterior({ enrolled: 2, monthsOpen: 2 });
  assert.equal(late.meanRatePerMonth, 1);
});

test("AC-37 the forecast's inputs are the activation plan, one rate prior per site and the screening loss", () => {
  const scenario = accrualForecastScenario({
    studyId: "std-1", target: 120, asOf: "2026-09-28T00:00:00Z", screenFailureRate: 0.3, horizonMonths: 24,
    sites: [
      { id: "ste-1", name: "A", activatedOn: "2026-05-01", capacity: { slots: 40, activationPlannedOn: "2026-04-15" } },
      { id: "ste-2", name: "B", activatedOn: null, capacity: { slots: 20, activationPlannedOn: "2026-11-01" },
        accrualPrior: { alpha: 1, beta: 1, screenFailureRate: 0.5 } },
    ],
    siteHistories: { "ste-1": { enrolled: 12, monthsOpen: 4 } },
  });
  assert.equal(scenario.kind, "accrual");
  assert.equal(scenario.target, 120);
  assert.equal(scenario.intervalKind, "prediction");
  assert.equal(scenario.intervalLevel, 0.8);
  assert.equal(scenario.sites[0].alpha, 13);
  assert.equal(scenario.sites[0].beta, 5);
  assert.equal(scenario.sites[0].meanRatePerMonth, 2.6);
  assert.equal(scenario.sites[0].ratePriorSource, "site_history");
  assert.equal(scenario.sites[0].screenFailureRate, 0.3, "the study's rate unless the site has its own");
  assert.equal(scenario.sites[1].screenFailureRate, 0.5);
  assert.equal(scenario.sites[1].ratePriorSource, "prior_only");
  // Planned and actual activation stay apart: the gap between them is the thing
  // that makes a trial late.
  assert.equal(scenario.sites[0].activationPlannedOn, "2026-04-15");
  assert.equal(scenario.sites[0].activatedOn, "2026-05-01");
  assert.equal(scenario.sites[1].activatedOn, null);
});

test("AC-37 the forecast is queued on the deterministic engine through the injected job port", async () => {
  /** @type {any[]} */
  const queued = [];
  const jobs = { enqueue: async (job) => { queued.push(job); return { jobId: "job-1", state: "queued" }; } };
  const scenario = accrualForecastScenario({ studyId: "std-1", target: 60, asOf: "2026-09-28T00:00:00Z", sites: [] });
  const handle = await requestAccrualForecast({ jobs, studyId: "std-1", scenario, requestedBy: "u-1" });
  assert.deepEqual(handle, { jobId: "job-1", state: "queued" });
  assert.equal(queued.length, 1);
  assert.equal(queued[0].kind, "accrual_forecast");
  assert.equal(queued[0].studyId, "std-1");
  assert.equal(queued[0].scenario.target, 60);
  assert.equal(VCR_JOB_METHODS.accrual_forecast, "accrual.poisson_gamma", "the engine method this kind maps to");
  await assert.rejects(() => requestAccrualForecast({ jobs, studyId: "std-1", scenario: { kind: "design" } }), /accrual scenario/);
  await assert.rejects(() => requestAccrualForecast({ jobs: null, studyId: "std-1", scenario }), /jobs port/);
});

test("AC-37 an interval that does not name its kind is dropped rather than relabelled", () => {
  const read = readAccrualForecast({
    status: "succeeded",
    measures: [
      { name: "last_patient_in_months", value: 18.4, interval: { kind: "prediction", low: 15.1, high: 23.9 } },
      { name: "probability_by_2027_06", value: 0.62, interval: { kind: "monte_carlo", low: 0.60, high: 0.64 } },
      { name: "target_events_months", value: 26.0, interval: { low: 22, high: 31 } },
    ],
    diagnostics: { quantiles: { 0.2: 15.8, 0.5: 18.4, 0.8: 21.7 } },
  });
  assert.equal(read.lastPatientIn.value, 18.4);
  assert.equal(read.targetEventsReached, null, "an unnamed interval is not a prediction interval");
  assert.deepEqual(read.droppedUnnamedIntervals, ["target_events_months"]);
  assert.equal(read.probabilityByDate.length, 1);
  assert.deepEqual(Object.keys(read.commitments).sort(), ["aggressive", "balanced", "conservative"]);
  assert.equal(read.commitments.conservative.quantile, VCR_RISK_APPETITE_QUANTILES.conservative);
  assert.match(read.commitments.balanced.note, /不是预测更准/);
});

test("AC-37 the backtest reports the measured coverage of the 80% prediction intervals, with no pass mark", () => {
  const slice = (low, high, actual, kind = "prediction") => ({ asOf: "2026-01-01T00:00:00Z", interval: { kind, low, high }, actual });
  const report = backtestAccrualCoverage({
    slices: [
      slice(10, 20, 15), slice(10, 20, 19), slice(10, 20, 25), slice(30, 40, 35), slice(30, 40, 29),
      slice(1, 2, 1.5, "confidence"), { asOf: "2026-02-01T00:00:00Z", interval: null, actual: 3 },
    ],
  });
  assert.equal(report.slices, 7);
  assert.equal(report.usable, 5);
  assert.equal(report.unusable, 2, "a confidence interval and an incomplete slice are named, not counted");
  assert.equal(report.covered, 3);
  assert.equal(report.coverage, 3 / 5);
  assert.equal(report.level, 0.8);
  assert.equal(report.calibration, "over_confident");
  assert.ok(report.coverageInterval.low < 0.6 && report.coverageInterval.high > 0.6,
    "five slices settle almost nothing, and the interval says so");
  assert.match(report.note, /不是「准确度」/);
  assert.equal(Object.hasOwn(report, "passed"), false);
  assert.equal(backtestAccrualCoverage({ slices: [] }).coverage, null);
  const wide = backtestAccrualCoverage({ slices: [slice(0, 100, 5), slice(0, 100, 5), slice(0, 100, 5)] });
  assert.equal(wide.calibration, "conservative");
});

test("AC-37 Wilson bounds, not a bare fraction", () => {
  const perfect = wilsonInterval(10, 10);
  assert.ok(perfect.low > 0.7 && perfect.low < 0.75);
  assert.ok(perfect.high > 0.999, "ten out of ten still admits the top of the range");
  const half = wilsonInterval(5, 10);
  assert.ok(half.low < 0.5 && half.high > 0.5);
  assert.deepEqual(wilsonInterval(0, 0), { low: null, high: null });
});

test("AC-37 a backtest slice is only scored against enrolments that happened after the forecast was registered", () => {
  const slices = accrualBacktestSlices({
    forecasts: [
      { asOf: "2026-03-01T00:00:00Z", interval: { kind: "prediction", low: 2, high: 9 } },
      { asOf: "2026-06-01T00:00:00Z", interval: { kind: "prediction", low: 1, high: 4 } },
      { asOf: null, interval: { kind: "prediction", low: 0, high: 99 } },
    ],
    enrollments: [
      { enrolledOn: "2026-02-10" }, { enrolledOn: "2026-03-20" }, { enrolledOn: "2026-04-05" },
      { enrolledOn: "2026-06-15" }, { enrolledOn: "2026-07-02" }, { enrolledOn: "2026-12-01" },
    ],
    horizonMonths: 6,
  });
  assert.equal(slices.length, 2, "a forecast with no timestamp cannot be scored and is dropped");
  assert.equal(slices[0].actual, 4, "the February enrolment predates the March forecast");
  assert.equal(slices[1].actual, 2);
  const coverage = backtestAccrualCoverage({ slices });
  assert.equal(coverage.usable, 2);
  assert.equal(coverage.covered, 2);
});

// ------------------------------------------------------------- AC-22

test("AC-22 an exit date and reason are recorded as given, and the in-trial fields stay marked invisible", () => {
  const episode = trialPeriodEpisode({
    studyId: "std-1", subjectKey: "S1",
    windowStart: "2026-03-01T00:00:00Z", exitDate: "2026-08-14", exitReason: "受试者要求退出",
    observations: [{ kind: "visit", at: "2026-05-02T00:00:00Z" }],
  });
  assert.equal(episode.exitDate, "2026-08-14");
  assert.equal(episode.exitReason, "受试者要求退出");
  assert.equal(episode.kind, "study_specific");
  assert.equal(episode.derived, false);
  for (const field of VCR_TRIAL_RESTRICTED_FIELDS) {
    assert.deepEqual(episode.restricted[field], { visible: false, reason: "restricted_in_trial" }, field);
  }
  assert.ok(VCR_TRIAL_RESTRICTED_FIELDS.includes("progression_date"));
  assert.ok(VCR_TRIAL_RESTRICTED_FIELDS.includes("randomization_arm"));
  assert.deepEqual([...VCR_EXIT_VERBATIM_FIELDS], ["exitDate", "exitReason"]);
  assert.deepEqual(followupFidelityFindings(episode, { exitDate: "2026-08-14", exitReason: "受试者要求退出" }), []);
});

test("AC-22 an exit record is never converted into a progression date, a last-dose date or an arm", () => {
  for (const field of ["progression_date", "last_dose_date", "randomization_arm"]) {
    const refusal = deriveFromExit({ field });
    assert.equal(refusal.ok, false);
    assert.equal(refusal.code, "vcr_exit_field_not_derivable");
    assert.equal(refusal.field, field);
    assert.match(refusal.message, /出组记录不能转换/);
    assert.equal(Object.hasOwn(refusal, "value"), false, "a refusal never carries a value to use anyway");
  }
  assert.ok(VCR_RECRUIT_REFUSALS.includes("vcr_exit_field_not_derivable"));
});

test("AC-22 a rewritten exit date and an unmarked restricted field are both reported, as advice", () => {
  const episode = trialPeriodEpisode({ studyId: "std-1", subjectKey: "S1", exitDate: "2026-08-14", exitReason: "疾病进展" });
  const rewritten = { ...episode, exitDate: "2026-08-01" };
  const findings = followupFidelityFindings(rewritten, { exitDate: "2026-08-14", exitReason: "疾病进展" });
  assert.deepEqual(findings.map((item) => item.code), ["vcr_exit_date_rewritten"]);
  assert.ok(findings.every((item) => item.severity === "advisory"), "the blocking budget is spent (principle 4)");

  const unmarked = { ...episode, restricted: {} };
  const codes = followupFidelityFindings(unmarked, {}).map((item) => item.code);
  assert.equal(codes.filter((code) => code === "vcr_restricted_field_not_marked").length, VCR_TRIAL_RESTRICTED_FIELDS.length);
});

test("AC-22 the post-exit window is a cohort about itself, and says so", () => {
  const episode = postExitEpisode({ studyId: "std-1", subjectKey: "S1", from: "2026-08-15T00:00:00Z" });
  assert.equal(episode.kind, "post_exit");
  assert.equal(episode.exitReason, null, "the exit belongs to the trial-period episode, not to this one");
  assert.deepEqual(episode.restricted, {});
  assert.match(episode.scope, /不代表未治疗的自然病程/);
  assert.match(episode.scope, /不代表原来入组的全体/);
  assert.deepEqual(followupFidelityFindings(episode, {}), [], "a post-exit episode owes no restriction marks");
});

test("AC-22 what partner data may and may not answer is a table in code, and an unlisted use is refused", () => {
  assert.equal(partnerDataUseAllowed("matching_evaluation").allowed, true);
  assert.equal(partnerDataUseAllowed("accrual_calibration").allowed, true);
  assert.equal(partnerDataUseAllowed("feasibility").allowed, true);
  assert.equal(partnerDataUseAllowed("post_exit_observation").allowed, true);
  assert.equal(partnerDataUseAllowed("trial_efficacy").allowed, false);
  assert.equal(partnerDataUseAllowed("external_control").allowed, false);
  assert.equal(partnerDataUseAllowed("anything_else").allowed, false, "an unlisted use defaults to refused");
  assert.equal(VCR_PARTNER_DATA_USES.filter((row) => row.allowed).length, 4);
  assert.ok(VCR_PARTNER_DATA_USES.every((row) => row.note.length > 0));
});
