/**
 * Writes `presets/evimed-universal.patch.yml`, the form DSH 0.1.7 reads a
 * preset in, from `presets/evimed-universal/{preset.yml,agent.cordis.yml}`, the
 * form this repository edits it in.
 *
 * Up to 0.1.5 the kernel's `dsh-agent-presets` scanned preset *directories*
 * (`preset.yml` plus `agent.cordis.yml`) under configured roots. 0.1.7 deleted
 * that package: a preset is now an ordinary row of the host composition — one
 * `@deepseek-ai/dsh-agent-preset` declaration whose `config.plugins` is the
 * agent's child entry list — inserted by a bundle patch, and the registry
 * "neither scans directories nor accepts preset paths" (its README). So the
 * kernel-facing file is a patch, and it is generated rather than hand-kept
 * beside the source: every reader of the composition (the kernel-defaults
 * invariants, the composition-reference checker, the plugin-switch and
 * scoped-inject tests) keeps reading one file, and `test/presetPatch.test.mjs`
 * fails when the committed patch is not what this script writes from it.
 *
 * The body is the source's lines shifted under `plugins:`, comments included,
 * so the `!!js` expressions reach the kernel byte for byte as written.
 *
 * @module @evimed/dsh-socket/scripts/build-preset
 */
import { readFile, rename, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

export const PRESET_ID = 'evimed-universal'
export const PRESET_ROW_ID = `preset-${PRESET_ID}`

const presetDir = new URL(`../presets/${PRESET_ID}/`, import.meta.url)
export const PRESET_PATCH_URL = new URL(`../presets/${PRESET_ID}.patch.yml`, import.meta.url)

/** The two scalar fields `preset.yml` carries, read without a YAML parser. @param {string} text */
function presetMetadata(text) {
  const field = (/** @type {string} */ key) => new RegExp(`^${key}:\\s*(.+)$`, 'm').exec(text)?.[1]?.trim() ?? ''
  const name = field('name')
  if (name !== PRESET_ID) throw new Error(`preset.yml names ${JSON.stringify(name)}; the control plane asks for ${PRESET_ID}`)
  const order = Number(field('order') || 0)
  if (!Number.isInteger(order)) throw new Error('preset.yml order is not an integer')
  return { description: field('description'), order }
}

/** @param {string} value */
const quoted = (value) => `'${value.replace(/'/g, "''")}'`

/**
 * @param {{ presetYml: string, agentCordisYml: string }} source
 * @returns {string}
 */
export function renderPresetPatch({ presetYml, agentCordisYml }) {
  const { description, order } = presetMetadata(presetYml)
  const body = agentCordisYml.replace(/\n+$/, '').split('\n').map((line) => (line ? `          ${line}` : '')).join('\n')
  return [
    '# GENERATED by scripts/build-preset.mjs from presets/evimed-universal/{preset.yml,',
    '# agent.cordis.yml}. Edit those, then run `node scripts/build-preset.mjs`;',
    '# test/presetPatch.test.mjs fails when this file is not what they produce.',
    '#',
    '# The agent preset as DSH 0.1.7 declares one: a host row of',
    '# `@deepseek-ai/dsh-agent-preset` whose `config.plugins` is the child entry',
    '# list every session mounts. `config.id` is the identity sessions record and',
    '# the control plane asks for; the row id is what a patch addresses.',
    '- insert:',
    `    - id: ${PRESET_ROW_ID}`,
    "      name: '@deepseek-ai/dsh-agent-preset'",
    '      config:',
    `        id: ${PRESET_ID}`,
    '        name: EviMed',
    `        description: ${quoted(description)}`,
    `        order: ${order}`,
    '        plugins:',
    body,
    '',
  ].join('\n')
}

/** @returns {Promise<string>} */
export async function readPresetPatchSource() {
  const [presetYml, agentCordisYml] = await Promise.all([
    readFile(new URL('preset.yml', presetDir), 'utf8'),
    readFile(new URL('agent.cordis.yml', presetDir), 'utf8'),
  ])
  return renderPresetPatch({ presetYml, agentCordisYml })
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const text = await readPresetPatchSource()
  const staging = new URL(`../presets/.${PRESET_ID}.patch.${process.pid}.yml`, import.meta.url)
  await writeFile(staging, text)
  await rename(staging, PRESET_PATCH_URL)
}
