"""Built-in Chinese→MedDRA-PT ADR mapping table.

Values are lower-case MedDRA Preferred Terms as used by FAERS
(``patient.reaction.reactionmeddrapt``). openFDA non-exact search is
case-insensitive tokenization, so lower-case values query fine; the table
keeps MedDRA's own spelling (British forms such as "diarrhoea").

The table is deliberately curated, not exhaustive: an English term is looked
up in the harvested FAERS vocabulary (``vocabulary.py``), and anything the
rules cannot map goes to the confirmed model path in ``adr.py``. Every value
here must be a term of that vocabulary -- ``tests/test_reaction_vocabulary.py``
fails otherwise. Seven values used to be MedDRA-looking strings FAERS never
carries ("peripheral neuropathy" for the PT "Neuropathy peripheral",
"acute pancreatitis" for "Pancreatitis acute"), so an exact openFDA query on
them matched no report at all.
"""

from __future__ import annotations

#: Chinese ADR name (and common aliases) -> lower-case MedDRA PT.
ZH_TO_PT: dict[str, str] = {
    # musculoskeletal / the statin cluster
    "肌痛": "myalgia",
    "肌肉疼痛": "myalgia",
    "肌病": "myopathy",
    "横纹肌溶解": "rhabdomyolysis",
    "横纹肌溶解症": "rhabdomyolysis",
    "肌酸激酶升高": "blood creatine phosphokinase increased",
    "肌酸磷酸激酶升高": "blood creatine phosphokinase increased",
    "肌无力": "muscular weakness",
    "肌腱炎": "tendonitis",
    "肌腱断裂": "tendon rupture",
    "关节痛": "arthralgia",
    "背痛": "back pain",
    "骨坏死": "osteonecrosis",
    "颌骨坏死": "osteonecrosis of jaw",
    # hepatobiliary
    "肝损伤": "hepatotoxicity",
    "药物性肝损伤": "drug-induced liver injury",
    "肝功能异常": "hepatic function abnormal",
    "急性肝衰竭": "acute hepatic failure",
    "肝衰竭": "hepatic failure",
    "黄疸": "jaundice",
    "转氨酶升高": "transaminases increased",
    # renal
    "急性肾损伤": "acute kidney injury",
    "急性肾衰竭": "renal failure acute",
    "肾衰竭": "renal failure",
    "肾功能不全": "renal impairment",
    "血尿": "haematuria",
    "蛋白尿": "proteinuria",
    "膀胱炎": "cystitis",
    "间质性膀胱炎": "cystitis interstitial",
    "排尿困难": "dysuria",
    # respiratory
    "肺炎": "pneumonia",
    "间质性肺病": "interstitial lung disease",
    "肺纤维化": "pulmonary fibrosis",
    "咳嗽": "cough",
    "呼吸困难": "dyspnoea",
    "肺栓塞": "pulmonary embolism",
    "呼吸衰竭": "respiratory failure",
    # cardiac / vascular
    "心律失常": "arrhythmia",
    "心房颤动": "atrial fibrillation",
    "房颤": "atrial fibrillation",
    "室性心动过速": "ventricular tachycardia",
    "尖端扭转型室性心动过速": "torsade de pointes",
    "尖端扭转型室速": "torsade de pointes",
    "qt间期延长": "electrocardiogram qt prolonged",
    "qt延长": "electrocardiogram qt prolonged",
    "心肌梗死": "myocardial infarction",
    "心肌梗塞": "myocardial infarction",
    "心力衰竭": "cardiac failure",
    "心衰": "cardiac failure",
    "充血性心力衰竭": "cardiac failure congestive",
    "射血分数下降": "ejection fraction decreased",
    "射血分数降低": "ejection fraction decreased",
    "左室射血分数下降": "ejection fraction decreased",
    "左室射血分数降低": "ejection fraction decreased",
    "左心室射血分数下降": "ejection fraction decreased",
    "心动过缓": "bradycardia",
    "心动过速": "tachycardia",
    "心悸": "palpitations",
    "心室颤动": "ventricular fibrillation",
    "室颤": "ventricular fibrillation",
    "心肌炎": "myocarditis",
    "心肌病": "cardiomyopathy",
    "心包积液": "pericardial effusion",
    "房室传导阻滞": "atrioventricular block",
    "心脏骤停": "cardiac arrest",
    "心搏骤停": "cardiac arrest",
    "猝死": "sudden death",
    "心源性猝死": "sudden cardiac death",
    "晕厥": "syncope",
    "胸痛": "chest pain",
    "高血压": "hypertension",
    "低血压": "hypotension",
    "深静脉血栓": "deep vein thrombosis",
    "深静脉血栓形成": "deep vein thrombosis",
    "卒中": "cerebrovascular accident",
    "脑卒中": "cerebrovascular accident",
    # haematologic / bleeding
    "粒细胞缺乏": "agranulocytosis",
    "粒细胞缺乏症": "agranulocytosis",
    "中性粒细胞减少": "neutropenia",
    "血小板减少": "thrombocytopenia",
    "血小板减少症": "thrombocytopenia",
    "贫血": "anaemia",
    "再生障碍性贫血": "aplastic anaemia",
    "出血": "haemorrhage",
    "消化道出血": "gastrointestinal haemorrhage",
    "胃肠道出血": "gastrointestinal haemorrhage",
    "上消化道出血": "upper gastrointestinal haemorrhage",
    "下消化道出血": "lower gastrointestinal haemorrhage",
    "黑便": "melaena",
    "鼻衄": "epistaxis",
    "鼻出血": "epistaxis",
    "牙龈出血": "gingival bleeding",
    "瘀斑": "ecchymosis",
    # hypersensitivity / skin
    "过敏反应": "hypersensitivity",
    "过敏性休克": "anaphylactic shock",
    "过敏性反应": "anaphylactic reaction",
    "血管性水肿": "angioedema",
    "血管神经性水肿": "angioedema",
    "皮疹": "rash",
    "药疹": "drug eruption",
    "药物性皮疹": "drug eruption",
    "瘙痒": "pruritus",
    "荨麻疹": "urticaria",
    "史蒂文斯-约翰逊综合征": "stevens-johnson syndrome",
    "斯约综合征": "stevens-johnson syndrome",
    "中毒性表皮坏死松解症": "toxic epidermal necrolysis",
    "脱发": "alopecia",
    "多汗": "hyperhidrosis",
    "光敏反应": "photosensitivity reaction",
    # gastrointestinal
    "恶心": "nausea",
    "呕吐": "vomiting",
    "腹泻": "diarrhoea",
    "便秘": "constipation",
    "腹痛": "abdominal pain",
    "消化不良": "dyspepsia",
    "食欲下降": "decreased appetite",
    "食欲减退": "decreased appetite",
    "胰腺炎": "pancreatitis",
    "急性胰腺炎": "pancreatitis acute",
    "口干": "dry mouth",
    # metabolic / endocrine
    "低血糖": "hypoglycaemia",
    "高血糖": "hyperglycaemia",
    "糖尿病": "diabetes mellitus",
    "新发糖尿病": "diabetes mellitus",
    "高钾血症": "hyperkalaemia",
    "低钾血症": "hypokalaemia",
    "低钠血症": "hyponatraemia",
    "低镁血症": "hypomagnesaemia",
    "乳酸酸中毒": "lactic acidosis",
    "甲状腺功能减退": "hypothyroidism",
    "甲状腺功能亢进": "hyperthyroidism",
    "体重增加": "weight increased",
    "体重下降": "weight decreased",
    # neurologic / psychiatric
    "头痛": "headache",
    "头晕": "dizziness",
    "眩晕": "vertigo",
    "癫痫发作": "seizure",
    "惊厥": "convulsion",
    "意识模糊": "confusional state",
    "失眠": "insomnia",
    "嗜睡": "somnolence",
    "抑郁": "depression",
    "自杀意念": "suicidal ideation",
    "焦虑": "anxiety",
    "周围神经病变": "neuropathy peripheral",
    "周围神经病": "neuropathy peripheral",
    "记忆障碍": "memory impairment",
    "认知障碍": "cognitive disorder",
    "5-羟色胺综合征": "serotonin syndrome",
    "五羟色胺综合征": "serotonin syndrome",
    "恶性综合征": "neuroleptic malignant syndrome",
    "视神经炎": "optic neuritis",
    "听力下降": "hypoacusis",
    "听力损失": "deafness",
    "味觉障碍": "dysgeusia",
    # general
    "发热": "pyrexia",
    "乏力": "asthenia",
    "疲劳": "fatigue",
    "水肿": "oedema",
    "外周水肿": "oedema peripheral",
    "视力模糊": "vision blurred",
    "干眼": "dry eye",
    "输液反应": "infusion related reaction",
    "败血症": "sepsis",
    "感染性休克": "septic shock",
}

#: English aliases / colloquialisms -> lower-case MedDRA PT.
EN_ALIAS_TO_PT: dict[str, str] = {
    # Common American spellings and clinical synonyms for British-spelled
    # MedDRA PTs. Keep these deterministic so upstream search layers can use
    # ordinary English without relying on an LLM to repair terminology.
    "bleeding": "haemorrhage",
    "hemorrhage": "haemorrhage",
    "gastrointestinal bleeding": "gastrointestinal haemorrhage",
    "gi bleeding": "gastrointestinal haemorrhage",
    "digestive tract bleeding": "gastrointestinal haemorrhage",
    "gastrointestinal hemorrhage": "gastrointestinal haemorrhage",
    "gi hemorrhage": "gastrointestinal haemorrhage",
    "gi haemorrhage": "gastrointestinal haemorrhage",
    "hematuria": "haematuria",
    "anemia": "anaemia",
    "aplastic anemia": "aplastic anaemia",
    "dyspnea": "dyspnoea",
    "diarrhea": "diarrhoea",
    "edema": "oedema",
    "peripheral edema": "oedema peripheral",
    "hypoglycemia": "hypoglycaemia",
    "hyperglycemia": "hyperglycaemia",
    "hyperkalemia": "hyperkalaemia",
    "hypokalemia": "hypokalaemia",
    "hyponatremia": "hyponatraemia",
    "hypomagnesemia": "hypomagnesaemia",
    "heart attack": "myocardial infarction",
    "mi": "myocardial infarction",
    "rhabdo": "rhabdomyolysis",
    "ck elevation": "blood creatine phosphokinase increased",
    "cpk elevation": "blood creatine phosphokinase increased",
    "liver injury": "drug-induced liver injury",
    "dili": "drug-induced liver injury",
    "aki": "acute kidney injury",
    "kidney failure": "renal failure",
    "qt prolongation": "electrocardiogram qt prolonged",
    "long qt": "electrocardiogram qt prolonged",
    "afib": "atrial fibrillation",
    "af": "atrial fibrillation",
    "dvt": "deep vein thrombosis",
    "pe": "pulmonary embolism",
    "sjs": "stevens-johnson syndrome",
    "ten": "toxic epidermal necrolysis",
    "nms": "neuroleptic malignant syndrome",
    "low platelets": "thrombocytopenia",
    "muscle pain": "myalgia",
    "muscle weakness": "muscular weakness",
    "fever": "pyrexia",
    "hives": "urticaria",
    "itching": "pruritus",
    "stroke": "cerebrovascular accident",
    # Clinical names whose MedDRA PT reorders or renames them. Each value is a
    # FAERS term; the English words a clinician or a model writes are not.
    "heart failure": "cardiac failure",
    "congestive heart failure": "cardiac failure congestive",
    "chf": "cardiac failure congestive",
    "qt prolonged": "electrocardiogram qt prolonged",
    "prolonged qt": "electrocardiogram qt prolonged",
    "qtc prolongation": "electrocardiogram qt prolonged",
    "qt interval prolongation": "electrocardiogram qt prolonged",
    "decreased ejection fraction": "ejection fraction decreased",
    "reduced ejection fraction": "ejection fraction decreased",
    "lvef decreased": "ejection fraction decreased",
    "lvef decrease": "ejection fraction decreased",
    "acute pancreatitis": "pancreatitis acute",
    "acute renal failure": "renal failure acute",
    "peripheral neuropathy": "neuropathy peripheral",
    "peripheral oedema": "oedema peripheral",
    "tendinitis": "tendonitis",
    "cognitive impairment": "cognitive disorder",
    "upper gi bleeding": "upper gastrointestinal haemorrhage",
    "upper gastrointestinal bleeding": "upper gastrointestinal haemorrhage",
    "lower gastrointestinal bleeding": "lower gastrointestinal haemorrhage",
    "ild": "interstitial lung disease",
    "vf": "ventricular fibrillation",
    "vt": "ventricular tachycardia",
}


def all_known_pts() -> set[str]:
    """Every MedDRA PT this table can emit (values of both maps)."""
    return set(ZH_TO_PT.values()) | set(EN_ALIAS_TO_PT.values())
