/**
 * The profile patch the control plane writes before a runtime starts.
 *
 * Hidden knowledge: the split between what ships in the bundle and what the
 * deployment decides. The bundle carries the rows that are the same everywhere;
 * every row that names a path, an address, a token variable or a limit is
 * generated here, per project, per start. That split is what lets one tarball
 * plug into the hosted container and into a laptop without a line changing.
 *
 * Three rules govern the output.
 *
 * 1. **Literal values only.** A generated patch never uses `!!js`: a generated
 *    file that evaluates code at load is a generated file that can be made to
 *    evaluate someone else's code (§14 rule 25).
 * 2. **Every row carries an explicit id.** A row without one is read as a
 *    delete plus an insert on every config read, which remounts it.
 * 3. **No real key.** The provider key never enters the container. `apiKeyEnv`
 *    names a *reference*, resolved per request from a 0600 credentials file the
 *    control plane rewrites in place every few minutes — so a token refresh is
 *    not a restart.
 *
 * The module is pure: it renders text. Writing it is the caller's job, which
 * keeps the generator testable without a filesystem.
 *
 * @module dshProfilePatch
 */

import { MCP_SERVER_NAME } from "@evimed/domain";

/** The reference name the kernel resolves the workload token through. */
export const WORKLOAD_TOKEN_REF = "EVIMED_WORKLOAD_TOKEN";

/** The one composition. */
export const EVIMED_PRESET = "evimed-universal";

/** The plugin that speaks MCP on our behalf. It ships inside the kernel's own
 *  install, which is why an inserted row may name it: bare specifiers resolve
 *  against the loader's directory, and that is the one tree they reach. */
export const MCP_CLIENT_PLUGIN = "@deepseek-ai/dsh-mcp-client";

/**
 * @typedef {object} ProfilePatchInput
 * @property {string} modelGatewayUrl        absolute URL of /internal/model/v1
 * @property {string} model                  the certified model id
 * @property {number} contextWindow
 * @property {string} sessionsDir            absolute path inside the container
 * @property {string} mcpServerPath          absolute path to the MCP server entrypoint
 * @property {Record<string, string>} mcpEnvironment
 * @property {string} presetRoot             absolute path to the read-only preset root (kept for the
 *   record and the literal check; the kernel reads its own root, see below)
 * @property {string} capabilitiesDir
 * @property {string} capabilitySkillsDir
 * @property {string} capsuleMethodsDir
 * @property {string} capsuleGatewayUrl
 * @property {string} workloadTokenFile
 * @property {string} bundleVersion
 * @property {string} dshVersion
 * @property {{ deliveryAttemptLimit: number, maxParallelChildren: number, maxSteps: number, maxTokens: number, evidenceStaleMinutes: number, screeningBatchSize: number }} limits
 * @property {{ hosted: boolean, askUser: boolean, review: boolean, capsule: boolean, requiredEnforcement: 'full'|'partial' }} flags
 */

/**
 * Renders the patch.
 *
 * @param {ProfilePatchInput} input
 * @returns {string}
 */
export function renderProfilePatch(input) {
  assertLiteral(input.modelGatewayUrl, "modelGatewayUrl");
  assertLiteral(input.sessionsDir, "sessionsDir");
  assertLiteral(input.mcpServerPath, "mcpServerPath");
  assertLiteral(input.presetRoot, "presetRoot");

  const rows = [
    "# Generated by the control plane on every runtime start. Do not edit.",
    "#",
    "# It holds exactly the rows that differ between deployments: the gateway the",
    "# kernel talks to, the MCP command and its environment, the read-only roots,",
    "# and the limits the control plane owns. Everything else ships in the bundle.",
    "",
    "# The kernel never holds a real provider key. `baseURL` is our own gateway,",
    "# which authenticates a short-lived workload token and exchanges it for the",
    "# real credential server-side; `apiKeyEnv` names a reference resolved per",
    "# request from $DSH_HOME/.credentials.yaml, so a token refresh is a file",
    "# rewrite rather than a restart.",
    "- id: llm-deepseek",
    "  config:",
    `    baseURL: ${yamlScalar(input.modelGatewayUrl)}`,
    `    apiKeyEnv: ${yamlScalar(WORKLOAD_TOKEN_REF)}`,
    "    thinking: enabled",
    "    reasoningEffort: high",
    "    models:",
    `      - id: ${yamlScalar(input.model)}`,
    `        contextWindow: ${Number(input.contextWindow) || 1000000}`,
    "",
    "- id: agent-default-model",
    "  config:",
    "    provider: deepseek-official",
    `    model: ${yamlScalar(input.model)}`,
    "",
    "# Session logs live on the project's own data volume, so they are backed up,",
    "# exported and deleted with the project.",
    "- id: session-persistence-jsonl",
    "  config:",
    `    root: ${yamlScalar(input.sessionsDir)}`,
    "",
    "# Cross-session full-text search stays in memory: the index would be a second",
    "# copy of session content on disk, and we do not read it.",
    "- id: session-query-sqlite",
    "  config:",
    "    path: ':memory:'",
    "",
    "# Telemetry has no redaction rules and its full mode ships message bodies off",
    "# the box. Disabled here as well as by environment variable.",
    "- id: session-telemetry-otel",
    "  disabled: true",
    "",
    "# The preset ships with the bundle as a system-trusted root, so a copy a user",
    "# made into their own root cannot shadow it: the first root wins a name",
    "# collision, and system roots come first.",
    "- id: agent-presets",
    "  config:",
    // No `roots` here. The kernel replaces this row's `roots` with its own
    // shipped preset directory on every boot — `composeProfile` pushes a final
    // overlay that keeps the rest of the row and overwrites that one key — so a
    // root named here is discarded, and the only visible symptom is a session
    // that cannot find the preset while the row looks configured. The image
    // installs the preset into the kernel's own root instead; see the
    // `DSH_PRESET_ROOT` step in deploy/runtime-dsh/Dockerfile.
    "    default: " + yamlScalar(EVIMED_PRESET),
    "",
    "# The research tools. The MCP process runs outside the kernel's sandbox by",
    "# design (its command is trusted executable code), so it holds the workload",
    "# token and nothing else.",
    "- insert:",
    "    - id: mcp-evimed",
    // An inserted row must name the plugin to load. `id` alone identifies an
    // existing row for configuration; on an insert there is no existing row, so
    // a nameless one reaches the loader as `undefined` and fails with "Cannot
    // read properties of undefined (reading 'startsWith')" — which names
    // neither the row nor the omission.
    `      name: ${yamlScalar(MCP_CLIENT_PLUGIN)}`,
    "      config:",
    // The transport is a discriminator on a flat object, not a nested one:
    // `transport: stdio` selects a shape whose `command`, `args` and `env` sit
    // beside `serverName`. Nesting them under `transport:` produced a schema
    // rejection that took down the whole plugin tree — and with
    // `failOnStartupError: true` that is the intended severity, since a runtime
    // without the research tools cannot do the work it would accept.
    "        transport: stdio",
    `        serverName: ${yamlScalar(MCP_SERVER_NAME)}`,
    "        failOnStartupError: true",
    "        toolCallTimeoutMs: 180000",
    "        command: python3",
    "        args:",
    `          - ${yamlScalar(input.mcpServerPath)}`,
    "        env:",
    ...environmentRows(input.mcpEnvironment, input.workloadTokenFile),
    "",
    ...presetRows(input),
  ];
  return `${rows.join("\n")}\n`;
}

/**
 * Rows this patch may configure at all.
 *
 * Only two of our plugins are mounted in the host composition — the bundle's
 * patch inserts them — and a profile's `cordis.patch.yml` can reach exactly
 * those. The six agent-face plugins are mounted in agent scope from the
 * preset's own `agent.cordis.yml`, so naming them here does not override them:
 * DSH reports an unmatched target on stderr and drops the row, and the plugins
 * then run on their schema defaults while the deployment believes it configured
 * them. Their values travel as container environment instead, which the preset
 * rows read with `!!js` — see {@link runtimeEnvironment}.
 *
 * @param {ProfilePatchInput} input
 * @returns {string[]}
 */
function presetRows(input) {
  return [
    "# The two plugins the bundle mounts in the host composition. Every other",
    "# setting of ours travels as container environment, because a profile patch",
    "# cannot reach a row that a preset mounts.",
    "- id: evimed-seam-probe",
    "  config:",
    `    requiredEnforcement: ${yamlScalar(input.flags.requiredEnforcement)}`,
    `    dshVersion: ${yamlScalar(input.dshVersion)}`,
    "",
    "",
    "# Inside a container whose only writable place is the workspace nothing",
    "# needs approval; the only things that ask are attempts to leave the",
    "# sandbox, and an unattended run should refuse those rather than hang.",
    "#",
    "# The row is `approval` and its field is `policy`, both read from a running",
    "# host's own --dump-config. An earlier version of this file addressed a",
    "# `permission-presets` row with a `presets` list, which does not exist: the",
    "# patch was reported as an unmatched target on stderr and dropped, leaving",
    "# an unattended runtime on the stock policy that asks and then waits.",
    "- id: approval",
    "  config:",
    `    policy: ${yamlScalar(input.flags.hosted ? "never" : "ask")}`,
  ];
}

/**
 * The environment the container must carry for the preset's rows to resolve.
 *
 * Every key here is read by a `!!js` expression in
 * `presets/evimed-universal/agent.cordis.yml`. The two files are a pair: a name
 * added on one side and not the other leaves a plugin on its schema default,
 * silently, which is the failure this whole split exists to make visible. A
 * test asserts every name this returns appears in the preset.
 *
 * The parameter is the settings half of {@link ProfilePatchInput} rather than
 * the whole of it: a launch plan holds these and has no gateway to validate, so
 * asking for the full input would make building an environment depend on
 * something it never reads.
 *
 * @typedef {Pick<ProfilePatchInput, 'capabilitiesDir'|'capabilitySkillsDir'|'capsuleMethodsDir'|'capsuleGatewayUrl'|'workloadTokenFile'|'bundleVersion'|'flags'|'limits'>} RuntimeEnvironmentInput
 *
 * @param {RuntimeEnvironmentInput} input
 * @returns {Record<string, string>}
 */
export function runtimeEnvironment(input) {
  return {
    EVIMED_CAPABILITIES_DIR: input.capabilitiesDir,
    EVIMED_CAPABILITY_SKILLS_DIR: input.capabilitySkillsDir,
    EVIMED_CAPSULE_METHODS_DIR: input.capsuleMethodsDir,
    EVIMED_CAPSULE_GATEWAY_URL: input.capsuleGatewayUrl,
    EVIMED_WORKLOAD_TOKEN_FILE: input.workloadTokenFile,
    EVIMED_BUNDLE_VERSION: input.bundleVersion,
    EVIMED_ASK_USER: input.flags.askUser ? "1" : "0",
    EVIMED_CAPSULE_ACTIVE: input.flags.capsule ? "1" : "0",
    EVIMED_REVIEW_ENABLED: input.flags.review ? "1" : "0",
    // A nonsense limit falls back to the schema's own default rather than being
    // written through: a plugin reading `maxParallelChildren: -1` would honour
    // it, and a misconfiguration should not be able to stop delegation.
    EVIMED_DELIVERY_ATTEMPT_LIMIT: String(integer(input.limits.deliveryAttemptLimit, 3)),
    EVIMED_MAX_PARALLEL_CHILDREN: String(integer(input.limits.maxParallelChildren, 30)),
    EVIMED_MAX_STEPS: String(integer(input.limits.maxSteps, 200)),
    EVIMED_MAX_TOKENS: String(integer(input.limits.maxTokens, 400_000)),
    EVIMED_EVIDENCE_STALE_MINUTES: String(integer(input.limits.evidenceStaleMinutes, 10)),
    EVIMED_SCREENING_BATCH_SIZE: String(integer(input.limits.screeningBatchSize, 50)),
  };
}

/**
 * @param {Record<string, string>} environment
 * @param {string} workloadTokenFile
 * @returns {string[]}
 */
function environmentRows(environment, workloadTokenFile) {
  const merged = { ...environment, EVIMED_WORKLOAD_TOKEN_FILE: workloadTokenFile };
  return Object.entries(merged)
    .filter(([, value]) => value != null && String(value) !== "")
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => {
      assertLiteral(String(value), `mcpEnvironment.${key}`);
      return `          ${key}: ${yamlScalar(String(value))}`;
    });
}

/**
 * The credentials file the kernel resolves `apiKeyEnv` references from.
 *
 * It is rewritten in place — atomically, every refresh interval — rather than
 * being injected as an environment variable, because a process environment is
 * fixed at exec time and a short-lived token that cannot be refreshed without a
 * restart is a token that will expire mid-run.
 *
 * @param {{ token: string }} input
 * @returns {string}
 */
export function renderCredentialsFile({ token }) {
  assertLiteral(token, "workload token");
  return [
    "# Generated by the control plane. Rewritten in place on every refresh.",
    "# Mode 0600. This is a short-lived workload token, not a provider key: the",
    "# provider key never enters this container.",
    // `version: 1` is not decoration. Without it the provider reads the file as
    // the pre-release flat layout and refuses to load — "uses the pre-release
    // flat layout. Add `version: 1` and nest the existing 1 entry under
    // `refs:`" — which fails the whole plugin tree, so the container exits
    // during boot rather than starting without credentials.
    "version: 1",
    "refs:",
    `  ${WORKLOAD_TOKEN_REF}: ${yamlScalar(token)}`,
    "",
  ].join("\n");
}

/**
 * Quotes a scalar so a value can never become YAML structure. Single quotes
 * with doubled inner quotes is YAML's own literal form and needs no escape
 * table.
 * @param {string} value @returns {string}
 */
export function yamlScalar(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** @param {unknown} value @param {number} fallback @returns {number} */
function integer(value, fallback) {
  const number = Number(value);
  return Number.isSafeInteger(number) && number >= 0 ? number : fallback;
}

/**
 * A generated file must not be able to carry structure the generator did not
 * intend. A newline in a value would end the scalar and start a new row.
 * @param {string} value @param {string} field
 * @returns {void}
 */
function assertLiteral(value, field) {
  const text = String(value ?? "");
  if (/[\r\n\0]/.test(text)) {
    throw new Error(`evimed: ${field} must not contain control characters (generated YAML would be reshaped by it)`);
  }
}
