/**
 * The profile patch the control plane writes before a runtime starts.
 *
 * Hidden knowledge: the split between what ships in the bundle and what the
 * deployment decides. The bundle carries the rows that are the same everywhere;
 * every row that names a path, an address, a token variable or a limit is
 * generated here, per project, per start. That split is what lets one tarball
 * plug into the hosted container and into a laptop without a line changing.
 *
 * Three rules govern the output.
 *
 * 1. **Literal values only.** A generated patch never uses `!!js`: a generated
 *    file that evaluates code at load is a generated file that can be made to
 *    evaluate someone else's code (§14 rule 25).
 * 2. **Every row carries an explicit id.** A row without one is read as a
 *    delete plus an insert on every config read, which remounts it.
 * 3. **No real key.** The provider key never enters the container. `apiKeyEnv`
 *    names a *reference*, resolved per request from a 0600 credentials file the
 *    control plane rewrites in place every few minutes — so a token refresh is
 *    not a restart.
 *
 * The module is pure: it renders text. Writing it is the caller's job, which
 * keeps the generator testable without a filesystem.
 *
 * @module dshProfilePatch
 */

import { MCP_SERVER_NAME } from "@evimed/domain";

/** The reference name the kernel resolves the workload token through. */
export const WORKLOAD_TOKEN_REF = "EVIMED_WORKLOAD_TOKEN";

/** The one composition. */
export const EVIMED_PRESET = "evimed-universal";

/** The plugin that speaks MCP on our behalf. It ships inside the kernel's own
 *  install, which is why an inserted row may name it: bare specifiers resolve
 *  against the loader's directory, and that is the one tree they reach. */
import { BROWSER_SESSION_CREDENTIAL_KEY } from "./dshBrowserAuth.mjs";

export const MCP_CLIENT_PLUGIN = "@deepseek-ai/dsh-mcp-client";

/** Namespace for the sidecar's model-facing tool names: the model sees
 *  `mcp__tooluniverse__execute_tool`. Distinct from `MCP_SERVER_NAME` because
 *  a duplicate server name fails the later plugin instance at load. */
export const TOOL_UNIVERSE_SERVER_NAME = "tooluniverse";

/** The permission preset a hosted deployment runs under: confined *and*
 *  unattended, which is a pair the kernel does not ship. */
export const HOSTED_PERMISSION_PRESET = "evimed-hosted";

/**
 * @typedef {object} ProfilePatchInput
 * @property {string} modelGatewayUrl        absolute URL of /internal/model/v1
 * @property {string} model                  the certified model id
 * @property {number} contextWindow
 * @property {string} sessionsDir            absolute path inside the container
 * @property {string} mcpServerPath          absolute path to the MCP server entrypoint
 * @property {Record<string, string>} mcpEnvironment
 * @property {string} [toolUniverseUrl]   MCP endpoint of the ToolUniverse sidecar; omitted
 *   when the deployment does not run one, and then no row is emitted at all
 * @property {string} presetRoot             absolute path to the read-only preset root the image
 *   ships; named in the agent-presets row's `roots` since alpha.5 made configured roots work
 * @property {string} presetSkillsDir        absolute path to the preset's shipped skill roots
 * @property {string} capabilitiesDir
 * @property {string} capabilitySkillsDir
 * @property {string} capsuleMethodsDir
 * @property {string} capsuleGatewayUrl
 * @property {string} workloadTokenFile
 * @property {string} bundleVersion
 * @property {string} dshVersion
 * @property {{ deliveryAttemptLimit: number, maxParallelChildren: number, maxSteps: number, maxTokens: number, evidenceStaleMinutes: number, screeningBatchSize: number }} limits
 * @property {{ hosted: boolean, askUser: boolean, review: boolean, capsule: boolean, requiredEnforcement: 'full'|'partial' }} flags
 */

/**
 * Renders the patch.
 *
 * @param {ProfilePatchInput} input
 * @returns {string}
 */
export function renderProfilePatch(input) {
  assertLiteral(input.modelGatewayUrl, "modelGatewayUrl");
  assertLiteral(input.sessionsDir, "sessionsDir");
  assertLiteral(input.mcpServerPath, "mcpServerPath");
  assertLiteral(input.presetRoot, "presetRoot");
  assertLiteral(input.presetSkillsDir, "presetSkillsDir");

  const rows = [
    "# Generated by the control plane on every runtime start. Do not edit.",
    "#",
    "# It holds exactly the rows that differ between deployments: the gateway the",
    "# kernel talks to, the MCP command and its environment, the read-only roots,",
    "# and the limits the control plane owns. Everything else ships in the bundle.",
    "",
    "# The kernel never holds a real provider key. `baseURL` is our own gateway,",
    "# which authenticates a short-lived workload token and exchanges it for the",
    "# real credential server-side; `apiKeyEnv` names a reference resolved per",
    "# request from $DSH_HOME/.credentials.yaml, so a token refresh is a file",
    "# rewrite rather than a restart.",
    "- id: llm-deepseek",
    "  config:",
    `    baseURL: ${yamlScalar(input.modelGatewayUrl)}`,
    `    apiKeyEnv: ${yamlScalar(WORKLOAD_TOKEN_REF)}`,
    "    thinking: enabled",
    "    reasoningEffort: high",
    "    models:",
    `      - id: ${yamlScalar(input.model)}`,
    `        contextWindow: ${Number(input.contextWindow) || 1000000}`,
    "",
    "- id: agent-default-model",
    "  config:",
    "    provider: deepseek-official",
    `    model: ${yamlScalar(input.model)}`,
    "",
    "# Session logs live on the project's own data volume, so they are backed up,",
    "# exported and deleted with the project.",
    "- id: session-persistence-jsonl",
    "  config:",
    `    root: ${yamlScalar(input.sessionsDir)}`,
    "",
    "# Cross-session full-text search stays in memory: the index would be a second",
    "# copy of session content on disk, and we do not read it.",
    "- id: session-query-sqlite",
    "  config:",
    "    path: ':memory:'",
    "",
    "# Telemetry has no redaction rules and its full mode ships message bodies off",
    "# the box. Disabled here as well as by environment variable.",
    "- id: session-telemetry-otel",
    "  disabled: true",
    "",
    "# The preset ships with the image in a root this deployment owns.",
    "#",
    "# Naming a root here was useless at 0.1.2-alpha.3: `composeProfile` pushed a",
    "# final overlay that overwrote this one key on every boot, so a configured",
    "# root vanished while the row still looked configured — and the image copied",
    "# the preset into the kernel's own directory to work around it. alpha.5",
    "# documents the opposite behaviour: the shipped root is *prepended* before",
    "# every configured root rather than replacing the list. So the root is named",
    "# again, and the image stopped writing into its own installation.",
    "#",
    "# `trust: system` is what lets a user's own copy under `<dshHome>/.agent-presets`",
    "# fail to shadow it; the shipped root still wins an id collision ahead of both,",
    "# which is why the preset id is ours and not a name upstream might ship.",
    "- id: agent-presets",
    "  config:",
    "    roots:",
    "      - path: " + yamlScalar(input.presetRoot ?? "/opt/evimed/dsh/presets"),
    "        trust: system",
    "    default: " + yamlScalar(EVIMED_PRESET),
    "",
    "# The research tools. The MCP process runs outside the kernel's sandbox by",
    "# design (its command is trusted executable code), so it holds the workload",
    "# token and nothing else.",
    "- insert:",
    "    - id: mcp-evimed",
    // An inserted row must name the plugin to load. `id` alone identifies an
    // existing row for configuration; on an insert there is no existing row, so
    // a nameless one reaches the loader as `undefined` and fails with "Cannot
    // read properties of undefined (reading 'startsWith')" — which names
    // neither the row nor the omission.
    `      name: ${yamlScalar(MCP_CLIENT_PLUGIN)}`,
    "      config:",
    // The transport is a discriminator on a flat object, not a nested one:
    // `transport: stdio` selects a shape whose `command`, `args` and `env` sit
    // beside `serverName`. Nesting them under `transport:` produced a schema
    // rejection that took down the whole plugin tree — and with
    // `failOnStartupError: true` that is the intended severity, since a runtime
    // without the research tools cannot do the work it would accept.
    "        transport: stdio",
    `        serverName: ${yamlScalar(MCP_SERVER_NAME)}`,
    "        failOnStartupError: true",
    "        toolCallTimeoutMs: 180000",
    "        command: python3",
    "        args:",
    `          - ${yamlScalar(input.mcpServerPath)}`,
    "        env:",
    ...environmentRows(input.mcpEnvironment, input.workloadTokenFile),
    "",
    ...toolUniverseRows(input),
    ...presetRows(input),
    ...hostedBrowserPanelRows(input),
  ];
  return `${rows.join("\n")}\n`;
}

/**
 * The panels the kernel's browser application must not show a hosted user.
 *
 * On a laptop the person reading a settings panel owns the machine. Hosted,
 * they own one project inside somebody else's deployment, and the runtime's
 * home directory is a writable volume — so a change made in one of these
 * panels is a durable change to the deployment, not a preference. Three of
 * them are worse than confusing: models, because the release receipt certifies
 * the model that actually ran; presets, because switching one swaps the
 * composition every delivery gate assumes; the directory picker, because it
 * reaches outside the project.
 *
 * This is the visible half only. Hiding a panel hides a button, and the page
 * is JavaScript that can call anything — `@evimed/domain`'s runtime-UI surface
 * is what actually refuses the calls, and it is not derived from this list
 * because the two answer different questions ("should a person see this" and
 * "may this deployment be changed from a browser").
 *
 * Only leaves are disabled. `ui-settings` is the shell nine other rows inject,
 * and `ui-workspace` is injected by the sidebar, the conversation and the
 * chat: disabling either takes the application down at boot, which is the
 * opposite of hiding a panel. The settings shell therefore stays and opens
 * empty.
 *
 * @param {ProfilePatchInput} input
 * @returns {string[]}
 */
function hostedBrowserPanelRows(input) {
  if (!input.flags?.hosted) return [];
  return [
    "",
    "# Panels the hosted browser application does not show; see",
    "# apps/server/src/dshProfilePatch.mjs for why each one.",
    ...HOSTED_DISABLED_BROWSER_PANELS.flatMap((id) => [`- id: ${id}`, "  disabled: true"]),
  ];
}

/**
 * The row ids of those panels, as the composition names them.
 *
 * Listed here rather than inline so the test that checks them against the
 * image's recorded composition reads the same list the patch writes — a row id
 * that upstream renames must fail that test rather than silently stop
 * disabling anything.
 */
export const HOSTED_DISABLED_BROWSER_PANELS = Object.freeze([
  "ui-settings-general",
  "ui-settings-models",
  "ui-settings-plugin-inventory",
  "ui-settings-plugins",
  "ui-model-selection",
  // The composition names this row `ui-permission`, not
  // `ui-permission-presets` after its package. Written from the package name it
  // addressed nothing, and the check that reads the recorded composition is
  // what said so -- the same class of miss as the `permission-presets` row the
  // patch addressed with a key that did not exist for weeks.
  "ui-permission",
  "ui-agent-preset",
  "ui-message-feedback",
  "ui-goal",
  "ui-cordis",
  "ui-brand-official",
]);

/**
 * The browser's directory picker is deliberately absent from that list.
 *
 * It is loaded by the client (`dsh-client-ui-directory-picker-browse` appears
 * in the page's boot manifest) but the image's composition has no row for it:
 * the only picker row there is the host-side `directory-picker`. Disabling a
 * row id that does not exist would have looked exactly like disabling one that
 * does. What actually stops it is the method deny list -- `directoryPicker/*`
 * is refused whether or not a button is drawn.
 */

/**
 * The ToolUniverse sidecar, when the deployment runs one.
 *
 * Reached over HTTP rather than spawned, and that is the whole point: its 2,700
 * tools call their upstreams directly from their own process, which is exactly
 * what this runtime container is built not to do. Run as a sidecar it holds its
 * own credentials and its own egress, and the container keeps holding neither.
 *
 * `failOnStartupError` is false here and true for `mcp-evimed`, because the
 * severities differ: a run cannot do its work without the research tools, and
 * can without these. A sidecar that is down must degrade the run, not refuse it.
 *
 * Compact mode is the sidecar's own flag, not ours -- it exposes five discovery
 * tools instead of 2,700 and reaches the rest through `execute_tool`. Without
 * it a tool list larger than most context windows arrives before the question
 * does.
 *
 * @param {ProfilePatchInput} input
 * @returns {string[]}
 */
function toolUniverseRows(input) {
  const url = String(input.toolUniverseUrl ?? "").trim();
  if (!url) return [];
  assertLiteral(url, "toolUniverseUrl");
  return [
    "# The ToolUniverse sidecar: an HTTP MCP server that holds its own keys and",
    "# its own egress, so this container continues to hold neither.",
    "- insert:",
    "    - id: mcp-tooluniverse",
    `      name: ${yamlScalar(MCP_CLIENT_PLUGIN)}`,
    "      config:",
    "        transport: streamable-http",
    `        serverName: ${yamlScalar(TOOL_UNIVERSE_SERVER_NAME)}`,
    // A sidecar that is down degrades the run; it must not refuse it.
    "        failOnStartupError: false",
    "        toolCallTimeoutMs: 180000",
    `        url: ${yamlScalar(url)}`,
    "",
    "",
  ];
}

/**
 * Rows this patch may configure at all.
 *
 * Only two of our plugins are mounted in the host composition — the bundle's
 * patch inserts them — and a profile's `cordis.patch.yml` can reach exactly
 * those. The six agent-face plugins are mounted in agent scope from the
 * preset's own `agent.cordis.yml`, so naming them here does not override them:
 * DSH reports an unmatched target on stderr and drops the row, and the plugins
 * then run on their schema defaults while the deployment believes it configured
 * them. Their values travel as container environment instead, which the preset
 * rows read with `!!js` — see {@link runtimeEnvironment}.
 *
 * @param {ProfilePatchInput} input
 * @returns {string[]}
 */
function presetRows(input) {
  return [
    "# The two plugins the bundle mounts in the host composition. Every other",
    "# setting of ours travels as container environment, because a profile patch",
    "# cannot reach a row that a preset mounts.",
    "- id: evimed-seam-probe",
    "  config:",
    `    requiredEnforcement: ${yamlScalar(input.flags.requiredEnforcement)}`,
    `    dshVersion: ${yamlScalar(input.dshVersion)}`,
    "",
    "",
    "# Inside a container whose only writable place is the workspace nothing",
    "# needs approval; the only things that ask are attempts to leave the",
    "# sandbox, and an unattended run should refuse those rather than hang.",
    "#",
    "# The row is `approval` and its field is `policy`, both read from a running",
    "# host's own --dump-config. An earlier version of this file addressed a",
    "# `permission-presets` row with a `presets` list, which does not exist: the",
    "# patch was reported as an unmatched target on stderr and dropped, leaving",
    "# an unattended runtime on the stock policy that asks and then waits.",
    "- id: approval",
    "  config:",
    `    policy: ${yamlScalar(input.flags.hosted ? "never" : "ask")}`,
    "",
    "# The pair above has to be a NAMED preset, or nothing starts.",
    "#",
    "# `dsh-permission-presets` derives the default preset from the composed",
    "# sandbox mode and approval policy, and refuses to load when the pair",
    "# matches none of them: \"composed sandbox and approval defaults match no",
    "# preset; configure defaultPreset explicitly\". Its three shipped presets",
    "# pair a confined sandbox with `ask` and an unconfined one with `never` —",
    "# and a hosted run wants neither. It wants `workspace-write` with `never`,",
    "# because inside the sandbox nothing needs approval and the only things",
    "# that ask are attempts to leave it, which an unattended run should refuse.",
    "#",
    "# The table is replaced wholesale rather than extended, so the three shipped",
    "# rows are restated here; dropping one would remove a preset a user could",
    "# otherwise select.",
    "- id: permission",
    "  config:",
    "    presets:",
    "      read-only:",
    "        sandbox: read-only",
    "        approval: ask",
    "      workspace-write:",
    "        sandbox: workspace-write",
    "        approval: ask",
    "      danger-full-access:",
    "        sandbox: danger-full-access",
    "        approval: never",
    ...(input.flags.hosted
      ? [
          `      ${HOSTED_PERMISSION_PRESET}:`,
          "        sandbox: workspace-write",
          "        approval: never",
          `        name: ${yamlScalar(HOSTED_PERMISSION_PRESET)}`,
          "        description: 'Confined to the workspace, and refuses anything that asks to leave it.'",
        ]
      : []),
    `    defaultPreset: ${yamlScalar(input.flags.hosted ? HOSTED_PERMISSION_PRESET : "workspace-write")}`,
  ];
}

/**
 * The environment the container must carry for the preset's rows to resolve.
 *
 * Every key here is read by a `!!js` expression in
 * `presets/evimed-universal/agent.cordis.yml`. The two files are a pair: a name
 * added on one side and not the other leaves a plugin on its schema default,
 * silently, which is the failure this whole split exists to make visible. A
 * test asserts every name this returns appears in the preset.
 *
 * The parameter is the settings half of {@link ProfilePatchInput} rather than
 * the whole of it: a launch plan holds these and has no gateway to validate, so
 * asking for the full input would make building an environment depend on
 * something it never reads.
 *
 * @typedef {Pick<ProfilePatchInput, 'presetSkillsDir'|'capabilitiesDir'|'capabilitySkillsDir'|'capsuleMethodsDir'|'capsuleGatewayUrl'|'workloadTokenFile'|'bundleVersion'|'flags'|'limits'>} RuntimeEnvironmentInput
 *
 * @param {RuntimeEnvironmentInput} input
 * @returns {Record<string, string>}
 */
export function runtimeEnvironment(input) {
  return {
    // Absolute, because the skill loader resolves its roots with `path.resolve`
    // — a relative root lands under `process.cwd()`, which in a runtime
    // container is `/workspace`. The preset carried `./skills/core` and three
    // siblings, so every root pointed into the user's own upload directory:
    // nothing shipped was found, and an uploaded `skills/core/x/SKILL.md`
    // would have been read as an instruction. The row above it says default
    // root discovery is off for exactly that reason.
    EVIMED_PRESET_SKILLS_DIR: input.presetSkillsDir,
    EVIMED_CAPABILITIES_DIR: input.capabilitiesDir,
    EVIMED_CAPABILITY_SKILLS_DIR: input.capabilitySkillsDir,
    EVIMED_CAPSULE_METHODS_DIR: input.capsuleMethodsDir,
    EVIMED_CAPSULE_GATEWAY_URL: input.capsuleGatewayUrl,
    EVIMED_WORKLOAD_TOKEN_FILE: input.workloadTokenFile,
    EVIMED_BUNDLE_VERSION: input.bundleVersion,
    EVIMED_ASK_USER: input.flags.askUser ? "1" : "0",
    EVIMED_CAPSULE_ACTIVE: input.flags.capsule ? "1" : "0",
    EVIMED_REVIEW_ENABLED: input.flags.review ? "1" : "0",
    // A nonsense limit falls back to the schema's own default rather than being
    // written through: a plugin reading `maxParallelChildren: -1` would honour
    // it, and a misconfiguration should not be able to stop delegation.
    EVIMED_DELIVERY_ATTEMPT_LIMIT: String(integer(input.limits.deliveryAttemptLimit, 3)),
    EVIMED_MAX_PARALLEL_CHILDREN: String(integer(input.limits.maxParallelChildren, 30)),
    EVIMED_MAX_STEPS: String(integer(input.limits.maxSteps, 200)),
    EVIMED_MAX_TOKENS: String(integer(input.limits.maxTokens, 400_000)),
    EVIMED_EVIDENCE_STALE_MINUTES: String(integer(input.limits.evidenceStaleMinutes, 10)),
    EVIMED_SCREENING_BATCH_SIZE: String(integer(input.limits.screeningBatchSize, 50)),
  };
}

/**
 * @param {Record<string, string>} environment
 * @param {string} workloadTokenFile
 * @returns {string[]}
 */
function environmentRows(environment, workloadTokenFile) {
  const merged = { ...environment, EVIMED_WORKLOAD_TOKEN_FILE: workloadTokenFile };
  return Object.entries(merged)
    .filter(([, value]) => value != null && String(value) !== "")
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => {
      assertLiteral(String(value), `mcpEnvironment.${key}`);
      return `          ${key}: ${yamlScalar(String(value))}`;
    });
}

/**
 * The credentials file the kernel resolves `apiKeyEnv` references from.
 *
 * It is rewritten in place — atomically, every refresh interval — rather than
 * being injected as an environment variable, because a process environment is
 * fixed at exec time and a short-lived token that cannot be refreshed without a
 * restart is a token that will expire mid-run.
 *
 * The browser-session secret rides in the same file for the same reason: the
 * kernel reads its cookie key from here, so writing it anywhere else would mean
 * two credential stores with two lifetimes.
 *
 * @param {{ token: string, browserSessionSecret?: string|null }} input
 * @returns {string}
 */
export function renderCredentialsFile({ token, browserSessionSecret = null }) {
  assertLiteral(token, "workload token");
  if (browserSessionSecret != null) assertLiteral(browserSessionSecret, "browser-session secret");
  return [
    "# Generated by the control plane. Rewritten in place on every refresh.",
    "# Mode 0600. This is a short-lived workload token, not a provider key: the",
    "# provider key never enters this container.",
    // `version: 1` is not decoration. Without it the provider reads the file as
    // the pre-release flat layout and refuses to load — "uses the pre-release
    // flat layout. Add `version: 1` and nest the existing 1 entry under
    // `refs:`" — which fails the whole plugin tree, so the container exits
    // during boot rather than starting without credentials.
    "version: 1",
    // The kernel's own browser-session signing secret, seeded rather than
    // generated by the kernel.
    //
    // 0.1.2 authenticates every `/api` request, including on loopback. The
    // kernel's own route to a credential is a launch token printed on stdout,
    // which would mean scraping a container's log for a secret and racing its
    // boot. The cookie it accepts is an HMAC keyed by exactly this record, so
    // writing the key here lets the control plane mint the cookie before the
    // container exists — deterministic, and never printed anywhere.
    ...(browserSessionSecret == null
      ? []
      : [
        "records:",
        `  ${BROWSER_SESSION_CREDENTIAL_KEY}:`,
        "    kind: grant",
        "    payload:",
        "      version: 1",
        `      secret: ${yamlScalar(browserSessionSecret)}`,
      ]),
    "refs:",
    `  ${WORKLOAD_TOKEN_REF}: ${yamlScalar(token)}`,
    "",
  ].join("\n");
}

/**
 * Quotes a scalar so a value can never become YAML structure. Single quotes
 * with doubled inner quotes is YAML's own literal form and needs no escape
 * table.
 * @param {string} value @returns {string}
 */
export function yamlScalar(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** @param {unknown} value @param {number} fallback @returns {number} */
function integer(value, fallback) {
  const number = Number(value);
  return Number.isSafeInteger(number) && number >= 0 ? number : fallback;
}

/**
 * A generated file must not be able to carry structure the generator did not
 * intend. A newline in a value would end the scalar and start a new row.
 * @param {string} value @param {string} field
 * @returns {void}
 */
function assertLiteral(value, field) {
  const text = String(value ?? "");
  if (/[\r\n\0]/.test(text)) {
    throw new Error(`evimed: ${field} must not contain control characters (generated YAML would be reshaped by it)`);
  }
}
