// The public evidence pages' stylesheet, generated from the design-token package (flywheel F08, 2026-10-06).
//
// The pages are server-rendered without the React bundle, so they cannot read `index.css`; and a hand-written copy of the product's
// colours would drift from it the first time a token moved. This module reads the same table the web app's generated CSS reads
// (`COLOR_ROLES`, `TYPE_SCALE`, `SPACE`, `CONTAINERS`, `RADII`, `BREAKPOINTS`, `FONT_STACKS`) and writes a small sheet: no colour in it
// is written by hand, no web font is requested (the stack names faces the reader's system already has), no image is needed, and the
// dark scheme follows the reader's system setting. Under 640px (`BREAKPOINTS.sm`) the layout is one column.
//
// The sheet is served at `<base>/assets/site.css` (`/evidence/assets/site.css` unless the deployment serves the pages elsewhere), so the
// pages' Content-Security-Policy admits it by path (`style-src 'self'`) and no page carries an inline style.

import { createHash } from "node:crypto";
import { BREAKPOINTS, CONTAINERS, FONT_STACKS_EN, FONT_STACKS, RADII, SPACE, TYPE_SCALE, colorRole, rem, remLineHeight } from "@evimed/design-tokens";
import { evidencePublicPath } from "./evidencePublicPaths.mjs";

/** The roles the pages use, each a CSS variable of the same name. */
const ROLES = [
  "bg", "surface", "surface-1", "surface-2", "border-hairline", "border-light", "text", "text-2", "text-3", "accent", "accent-fg", "accent-soft", "accent-strong",
  "ok", "ok-soft", "info", "info-soft", "warn", "warn-soft", "warn-strong", "danger", "danger-soft", "danger-strong", "link", "verify-ok", "verify-pending", "highlight",
];

/** @param {"light" | "dark"} scheme */
const variables = (scheme) => ROLES.map((role) => `  --${role}: ${colorRole(role, scheme)};`).join("\n");

/** One rung of the type scale as a font declaration. @param {keyof typeof TYPE_SCALE} name */
const rung = (name) => `font-size: ${rem(TYPE_SCALE[name].size)}; line-height: ${remLineHeight(TYPE_SCALE[name].lineHeight)};`;

const gap = (/** @type {number} */ step) => rem(SPACE.scale[step]);

function build() {
  return `/* The public evidence pages. Generated by evidencePublicStyle.mjs from @evimed/design-tokens; do not edit by hand. */
:root {
  color-scheme: light dark;
${variables("light")}
  --font-sans: ${FONT_STACKS_EN.sans};
  --font-mono: ${FONT_STACKS.mono};
}
@media (prefers-color-scheme: dark) {
  :root {
${variables("dark").replace(/^ {2}/gm, "    ")}
  }
}
*, *::before, *::after { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; }
body {
  margin: 0; background: var(--bg); color: var(--text); font-family: var(--font-sans);
  ${rung("body")}
}
a { color: var(--link); text-underline-offset: 0.18em; }
a:hover { color: var(--accent-strong); }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
.site-header { background: var(--surface); border-bottom: 1px solid var(--border-hairline); }
.site-header .inner, .site-footer .inner, main {
  max-width: ${rem(CONTAINERS.page)}; margin: 0 auto; padding-left: ${rem(SPACE.pageGutter)}; padding-right: ${rem(SPACE.pageGutter)};
}
.site-header .inner { display: flex; flex-wrap: wrap; align-items: baseline; gap: ${gap(1)} ${gap(5)}; padding-top: ${gap(2)}; padding-bottom: ${gap(2)}; }
.site-header .brand { ${rung("heading")} font-weight: 600; color: var(--text); text-decoration: none; }
.site-header nav { display: flex; flex-wrap: wrap; gap: ${gap(0)} ${gap(4)}; ${rung("ui")} }
.site-header nav a { color: var(--text-2); text-decoration: none; }
.site-header nav a[aria-current="page"] { color: var(--accent-strong); font-weight: 600; }
main { padding-top: ${gap(5)}; padding-bottom: ${gap(7)}; }
main.read { max-width: ${rem(CONTAINERS.read + SPACE.pageGutter * 2)}; }
h1 { ${rung("title")} font-weight: 600; margin: 0 0 ${gap(2)}; }
h2 { ${rung("heading")} font-weight: 600; margin: ${gap(6)} 0 ${gap(2)}; }
h3 { ${rung("section")} font-weight: 600; margin: ${gap(5)} 0 ${gap(1)}; }
p { margin: 0 0 ${gap(3)}; }
ul, ol { margin: 0 0 ${gap(3)}; padding-left: ${gap(5)}; }
li { margin-bottom: ${gap(0)}; }
.meta, .muted { ${rung("caption")} color: var(--text-3); }
.lede { color: var(--text-2); }
.producer {
  ${rung("ui")} background: var(--surface-1); border: 1px solid var(--border-hairline); border-radius: ${rem(RADII.card)};
  padding: ${gap(2)} ${gap(3)}; margin: 0 0 ${gap(4)};
}
.producer strong { font-weight: 600; }
.badge {
  display: inline-block; ${rung("meta")} font-weight: 500; padding: 0 ${gap(1)}; border-radius: ${rem(RADII.tag)};
  background: var(--surface-2); color: var(--text-2); vertical-align: baseline;
}
.badge.ai { background: var(--info-soft); color: var(--info); }
.badge.warn { background: var(--warn-soft); color: var(--warn-strong); }
.badge.ok { background: var(--ok-soft); color: var(--ok); }
.badge.danger { background: var(--danger-soft); color: var(--danger-strong); }
.notice { border-radius: ${rem(RADII.card)}; padding: ${gap(2)} ${gap(3)}; margin: 0 0 ${gap(4)}; ${rung("ui")} }
.notice.warn { background: var(--warn-soft); color: var(--warn-strong); }
.notice.danger { background: var(--danger-soft); color: var(--danger-strong); }
.notice.info { background: var(--accent-soft); color: var(--accent-strong); }
.mark-ok { color: var(--verify-ok); font-weight: 600; }
.mark-warn { color: var(--verify-pending); font-weight: 600; }
.grid { display: grid; gap: ${rem(SPACE.gridGap)}; grid-template-columns: repeat(auto-fill, minmax(${rem(280)}, 1fr)); margin: 0 0 ${gap(4)}; padding: 0; list-style: none; }
.tile {
  background: var(--surface); border: 1px solid var(--border-hairline); border-radius: ${rem(RADII.card)}; padding: ${rem(SPACE.cardPadding)};
}
.tile h3 { ${rung("section")} margin: 0 0 ${gap(1)}; }
.tile p { ${rung("ui")} margin: 0 0 ${gap(1)}; }
.list { list-style: none; padding: 0; margin: 0 0 ${gap(4)}; }
.list > li { background: var(--surface); border: 1px solid var(--border-hairline); border-radius: ${rem(RADII.card)}; padding: ${gap(3)} ${rem(SPACE.cardPadding)}; margin-bottom: ${rem(SPACE.gridGap)}; }
.list h3 { margin: 0 0 ${gap(1)}; ${rung("section")} }
.list p { margin: 0 0 ${gap(1)}; ${rung("ui")} }
.claim { border-left: 3px solid var(--border-light); padding: ${gap(0)} 0 ${gap(0)} ${gap(3)}; margin: 0 0 ${gap(3)}; }
.claim.verified { border-left-color: var(--verify-ok); }
.claim.unverified { border-left-color: var(--verify-pending); }
.claim p { margin: 0 0 ${gap(0)}; }
blockquote { margin: ${gap(1)} 0; padding: ${gap(1)} ${gap(3)}; background: var(--surface-1); border-radius: ${rem(RADII.control)}; ${rung("ui")} color: var(--text-2); }
.table-wrap { overflow-x: auto; margin: 0 0 ${gap(4)}; }
table { border-collapse: collapse; width: 100%; ${rung("compact")} }
th, td { text-align: left; vertical-align: top; padding: ${gap(1)} ${gap(2)}; border-bottom: 1px solid var(--border-hairline); }
th { background: var(--surface-1); font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.factbox { background: var(--surface); border: 1px solid var(--border-light); border-radius: ${rem(RADII.card)}; padding: ${rem(SPACE.cardPadding)}; margin: 0 0 ${gap(4)}; }
.factbox h3 { margin-top: 0; }
details { margin: 0 0 ${gap(3)}; }
summary { cursor: pointer; color: var(--accent-strong); }
dl.facts { display: grid; grid-template-columns: max-content 1fr; gap: ${gap(0)} ${gap(4)}; margin: 0 0 ${gap(4)}; ${rung("ui")} }
dl.facts dt { color: var(--text-3); }
dl.facts dd { margin: 0; }
.cta { background: var(--accent-soft); border-radius: ${rem(RADII.card)}; padding: ${gap(4)}; margin: ${gap(6)} 0 0; }
.cta h2 { margin-top: 0; }
.button {
  display: inline-block; ${rung("ui")} font-weight: 500; background: var(--accent); color: var(--accent-fg); padding: ${gap(1)} ${gap(4)};
  border-radius: ${rem(RADII.control)}; text-decoration: none;
}
.button:hover { background: var(--accent-strong); color: var(--accent-fg); }
.pager { display: flex; gap: ${gap(4)}; margin: ${gap(4)} 0; ${rung("ui")} }
.site-footer { border-top: 1px solid var(--border-hairline); color: var(--text-3); ${rung("caption")} padding: ${gap(4)} 0; }
@media (max-width: ${BREAKPOINTS.sm - 1}px) {
  .site-header .inner, .site-footer .inner, main { padding-left: ${rem(SPACE.cardPadding)}; padding-right: ${rem(SPACE.cardPadding)}; }
  .grid { grid-template-columns: 1fr; }
  dl.facts { grid-template-columns: 1fr; }
  dl.facts dd { margin-bottom: ${gap(1)}; }
  h1 { ${rung("heading")} }
}
@media print { .site-header, .site-footer, .cta { display: none; } }
`;
}

let cached = /** @type {{ css: string, etag: string } | null} */ (null);

/** The stylesheet and its entity tag (the same bytes always give the same tag, so a release that changes a token changes the tag). */
export function evidencePublicStylesheet() {
  if (!cached) {
    const css = build();
    cached = { css, etag: `"${createHash("sha256").update(css).digest("hex").slice(0, 32)}"` };
  }
  return cached;
}

/** Where the sheet is served: the pages' stylesheet link and the router's own path. */
export const evidencePublicStylesheetPath = () => evidencePublicPath("/assets/site.css");
