/**
 * A fake agent kernel that speaks the real wire protocol.
 *
 * Hidden knowledge: what a kernel looks like from the control plane's side.
 * The point of it is not to simulate an agent — it is to let the entire server
 * test suite exercise the *adapter*, the ledger, the delivery decision and the
 * event stream against the protocol they will meet in production, without a
 * container, a model, or a network.
 *
 * That the previous kernel already had one of these is why swapping kernels was
 * tractable at all: the runtime layer had been proven to hold more than one
 * implementation before it had to.
 *
 * It answers `POST /api/<method>` with the four-quadrant RPC envelope and
 * streams `/api/events.mux` and `/api/events.host`, and it produces a session
 * event log — turn, step, user message, tool call, tool result, assistant
 * message, turn end — rather than a message list, because that is what the
 * adapter has to normalize.
 *
 * @module mockDshRuntime
 */

import { createHash } from "node:crypto";
import { createServer } from "node:http";
import fs from "node:fs/promises";
import path from "node:path";

/**
 * @param {import("node:http").IncomingMessage} req
 * @returns {Promise<Record<string, any>>}
 */
async function readJsonBody(req) {
  /** @type {Buffer[]} */
  const chunks = [];
  let bytes = 0;
  for await (const chunk of req) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
    bytes += buffer.length;
    if (bytes > 4 * 1024 * 1024) return {};
    chunks.push(buffer);
  }
  if (!bytes) return {};
  try {
    const value = JSON.parse(Buffer.concat(chunks, bytes).toString("utf8"));
    return value && typeof value === "object" && !Array.isArray(value) ? value : {};
  } catch {
    return {};
  }
}

/**
 * Starts the fake kernel.
 * @returns {Promise<{ url: string, close: () => Promise<void> }>}
 */
export function startMockDshRuntime() {
  /** @type {Map<string, { id: string, cwd: string, agentPreset: string, events: Record<string, any>[], seq: number, running: boolean }>} */
  const sessions = new Map();
  /** @type {Set<import("node:http").ServerResponse>} */
  const muxClients = new Set();
  /** @type {Set<import("node:http").ServerResponse>} */
  const hostClients = new Set();
  let counter = 0;

  /** @param {Set<import("node:http").ServerResponse>} clients @param {Record<string, any>} frame */
  const broadcast = (clients, frame) => {
    // The envelope a live kernel sends, `method` included: it mirrors the inner
    // frame's type, and a mock that omitted it let a decoder that only read the
    // envelope look correct.
    const envelope = { type: "server-request", rpcId: `push_${++counter}`, method: frame.type, payload: frame };
    for (const client of clients) {
      // isolated: a dead socket must not stop the other watchers.
      try {
        client.write(webSocketTextFrame(JSON.stringify(envelope)));
      } catch {
        clients.delete(client);
      }
    }
  };

  /**
   * @param {{ id: string, events: Record<string, any>[], seq: number }} session
   * @param {string} type
   * @param {Record<string, any>} data
   */
  const append = (session, type, data) => {
    const event = { type, seq: session.seq++, time: Date.now(), data };
    session.events.push(event);
    broadcast(muxClients, { type: "session/event", sessionId: session.id, event });
    return event;
  };

  /** @param {string} rpcId @param {any} value */
  const ok = (rpcId, value) => ({ type: "server-response", rpcId, result: { ok: true, value } });
  /** @param {string} rpcId @param {string} code @param {string} message */
  const fail = (rpcId, code, message) => ({ type: "server-response", rpcId, result: { ok: false, error: { code, message, details: {} } } });

  /**
   * Runs one turn: writes the artifact, logs the tool calls the ledger looks
   * for, and closes the turn. Synchronous on purpose — a test that has to wait
   * for a fake is a test that is flaky about something that never happens in
   * production.
   * @param {any} session @param {string} text
   */
  const runTurn = async (session, text) => {
    session.running = true;
    broadcast(hostClients, { type: "host/session-status", sessionId: session.id, running: true });
    const turn = 1;
    append(session, "turn/start", { turn });
    append(session, "user/message", { turn, step: 1, source: { kind: "user" }, content: [{ type: "text", text }] });
    append(session, "step/start", { turn, step: 1 });

    if (session.cwd) {
      // isolated: a fake that cannot write must still complete its turn, or a
      // read-only test directory turns into a protocol failure.
      try {
        await fs.mkdir(session.cwd, { recursive: true });
        await fs.writeFile(
          path.join(session.cwd, "mock-agent-artifact.md"),
          "# Mock agent artifact\n\nGenerated by the hosted mock runtime.\n",
          "utf8",
        );
      } catch { /* isolated: evimed_mock_kernel_write_failures_total */ }
    }

    append(session, "tool/call", { turn, step: 1, callId: "call-write", name: "write", arguments: JSON.stringify({ path: "mock-agent-artifact.md" }) });
    append(session, "tool/result", {
      turn,
      step: 1,
      message: { callId: "call-write", name: "write", content: [{ type: "text", text: "Wrote mock-agent-artifact.md" }] },
    });

    const answer = "EviMed 测试运行时已生成 mock-agent-artifact.md；生产环境将由服务端托管的科研智能体执行任务。";
    append(session, "assistant/message", {
      turn,
      step: 1,
      message: { role: "assistant", content: [{ type: "text", text: answer }] },
      usage: { promptCacheHitTokens: 100, promptCacheMissTokens: 20, completionTokens: 30 },
    });
    append(session, "step/end", { turn, step: 1 });
    append(session, "turn/end", { turn, reason: { kind: "completed" } });
    session.running = false;
    broadcast(hostClients, { type: "host/session-status", sessionId: session.id, running: false });
  };

  // The downlink is a WebSocket. Only what the downlink needs is implemented:
  // the handshake, and unmasked server-to-client text frames. Nothing reads
  // client-to-server frames on this channel, so nothing unmasks them.
  const attachDownlink = (server) => {
    server.on("upgrade", (req, socket) => {
      const url = new URL(req.url ?? "/", "http://runtime.local");
      const key = String(req.headers["sec-websocket-key"] ?? "");
      const isDownlink = url.pathname === "/api/events.mux" || url.pathname === "/api/events.host";
      if (!isDownlink || !key) {
        socket.end("HTTP/1.1 400 Bad Request\r\n\r\n");
        return;
      }
      const accept = createHash("sha1").update(`${key}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`).digest("base64");
      socket.write(
        "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n" +
        `Sec-WebSocket-Accept: ${accept}\r\n\r\n`,
      );
      const clients = url.pathname === "/api/events.mux" ? muxClients : hostClients;
      clients.add(socket);
      if (url.pathname === "/api/events.mux") {
        for (const session of sessions.values()) {
          broadcast(new Set([socket]), { type: "session/subscribed", sessionId: session.id, lastSeq: session.seq - 1 });
        }
      }
      socket.on("close", () => clients.delete(socket));
      socket.on("error", () => clients.delete(socket));
    });
  };

  const server = createServer(async (req, res) => {
    const url = new URL(req.url ?? "/", "http://runtime.local");
    const pathname = url.pathname;

    if (req.method === "GET" && (pathname === "/api/events.mux" || pathname === "/api/events.host")) {
      // Exactly what a live kernel answers a plain GET here. The mock used to
      // serve `text/event-stream`, which is a protocol the kernel does not
      // speak: anyone writing a downlink client against the mock would have
      // written an SSE reader and found out in production.
      res.writeHead(426, { "Content-Type": "text/plain;charset=UTF-8", Connection: "Upgrade", Upgrade: "websocket" });
      res.end("upgrade required");
      return;
    }

    if (req.method === "POST" && pathname.startsWith("/api/")) {
      const method = pathname.slice("/api/".length);
      const envelope = await readJsonBody(req);
      const rpcId = String(envelope.rpcId ?? `rpc_${++counter}`);
      const payload = envelope.payload && typeof envelope.payload === "object" ? envelope.payload : {};
      res.writeHead(200, { "Content-Type": "application/json" });

      if (method === "host.describe") {
        res.end(JSON.stringify(ok(rpcId, { name: "mock-dsh", version: "0.1.1-rc.2", methods: [...MOCK_METHODS] })));
        return;
      }
      if (method === "session.create") {
        const id = String(payload.sessionId ?? `web_mock_${++counter}`);
        const existing = sessions.get(id);
        if (existing && existing.cwd !== String(payload.cwd ?? existing.cwd)) {
          res.end(JSON.stringify(fail(rpcId, "session-conflict", "session id already exists with a different cwd")));
          return;
        }
        if (!existing) {
          sessions.set(id, { id, cwd: String(payload.cwd ?? ""), agentPreset: String(payload.agentPreset ?? "evimed-universal"), events: [], seq: 0, running: false });
          broadcast(hostClients, { type: "host/session-added", sessionId: id, blank: true, cwd: String(payload.cwd ?? ""), agentPreset: String(payload.agentPreset ?? "evimed-universal") });
        }
        res.end(JSON.stringify(ok(rpcId, { sessionId: id, agentPreset: sessions.get(id).agentPreset })));
        return;
      }
      const session = sessions.get(String(payload.sessionId ?? ""));
      if (["session.prompt", "session.cancel", "session.history", "session.fork", "subagent.list", "subagent.history"].includes(method) && !session) {
        res.end(JSON.stringify(fail(rpcId, "session-not-found", "no such session")));
        return;
      }
      if (method === "session.prompt") {
        const text = (Array.isArray(payload.content) ? payload.content : [])
          .filter((part) => part?.type === "text")
          .map((part) => String(part.text ?? ""))
          .join("\n") || "web prompt";
        res.end(JSON.stringify(ok(rpcId, { accepted: true })));
        await runTurn(session, text);
        return;
      }
      if (method === "session.cancel") {
        if (session.running) append(session, "turn/end", { turn: 1, reason: { kind: "aborted", reason: { kind: "user" } } });
        session.running = false;
        res.end(JSON.stringify(ok(rpcId, { accepted: true })));
        return;
      }
      if (method === "session.history") {
        const before = Number(payload.beforeSeq);
        const events = Number.isFinite(before) ? session.events.filter((event) => event.seq < before) : session.events;
        res.end(JSON.stringify(ok(rpcId, { events: events.map((event) => ({ event })), hasMore: false })));
        return;
      }
      if (method === "session.fork") {
        const id = `web_mock_${++counter}`;
        sessions.set(id, { id, cwd: session.cwd, agentPreset: session.agentPreset, events: [...session.events], seq: session.seq, running: false });
        res.end(JSON.stringify(ok(rpcId, { sessionId: id })));
        return;
      }
      if (method === "session.list") {
        res.end(JSON.stringify(ok(rpcId, {
          items: [...sessions.values()].map((entry) => ({ sessionId: entry.id, updatedAt: Date.now(), running: entry.running, blank: entry.events.length === 0, cwd: entry.cwd, agentPreset: entry.agentPreset })),
        })));
        return;
      }
      if (method === "subagent.list") {
        res.end(JSON.stringify(ok(rpcId, { items: [] })));
        return;
      }
      if (method === "subagent.history") {
        res.end(JSON.stringify(ok(rpcId, { events: [], hasMore: false })));
        return;
      }
      if (method === "skill.list") {
        res.end(JSON.stringify(ok(rpcId, { skills: [] })));
        return;
      }
      if (method === "agentPreset.list") {
        res.end(JSON.stringify(ok(rpcId, { presets: [{ name: "evimed-universal", description: "EviMed unified composition" }] })));
        return;
      }
      // A method the control plane should never have sent. Answering with a
      // real error rather than a 404 keeps a mistake in the allow-list visible
      // as a protocol error rather than as a transport one.
      res.end(JSON.stringify(fail(rpcId, "bad-request", `mock kernel does not serve ${method}`)));
      return;
    }

    // The non-protocol routes the proxy hardening tests exercise. They are the
    // same fixtures the previous kernel's fake carried, because what they test
    // is our proxy, not the kernel.
    if (req.method === "GET" && pathname === "/echo") {
      res.writeHead(200, {
        "Content-Type": "application/json",
        "Set-Cookie": "runtime_cookie=secret",
        "WWW-Authenticate": "Basic realm=\"runtime\"",
        "Proxy-Authenticate": "Basic realm=\"runtime\"",
        "Connection": "keep-alive, x-runtime-hop",
        "X-Runtime-Hop": "drop-me",
      });
      res.end(JSON.stringify({
        query: Object.fromEntries(url.searchParams.entries()),
        headers: {
          authorization: req.headers.authorization ?? null,
          cookie: req.headers.cookie ?? null,
          acceptEncoding: req.headers["accept-encoding"] ?? null,
        },
      }));
      return;
    }
    if (req.method === "GET" && pathname === "/redirect") {
      const runtimeOrigin = `http://${req.headers.host ?? "runtime.local"}`;
      res.writeHead(302, {
        Location: `${runtimeOrigin}/echo?directory=/etc&auth_token=secret&keep=1`,
        "Set-Cookie": "runtime_redirect=secret",
        "WWW-Authenticate": "Basic realm=\"runtime\"",
      });
      res.end();
      return;
    }
    if (req.method === "GET" && pathname === "/slow-body") {
      const delayMs = Math.max(0, Math.min(Number(url.searchParams.get("delay") ?? 200), 2_000));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.flushHeaders?.();
      setTimeout(() => {
        if (!res.destroyed) res.end(JSON.stringify({ ok: true }));
      }, delayMs);
      return;
    }
    if (req.method === "GET" && pathname === "/large-response") {
      const bytes = Math.max(0, Math.min(Number(url.searchParams.get("bytes") ?? 1024), 1024 * 1024));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ data: "x".repeat(bytes) }));
      return;
    }

    res.writeHead(404, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "mock kernel route not found" }));
  });

  return new Promise((resolve, reject) => {
    server.once("error", reject);
    attachDownlink(server);
    server.listen(0, "127.0.0.1", () => {
      const address = /** @type {import("node:net").AddressInfo} */ (server.address());
      resolve({
        url: `http://127.0.0.1:${address.port}`,
        close: () => new Promise((done) => {
          for (const client of [...muxClients, ...hostClients]) client.end();
          muxClients.clear();
          hostClients.clear();
          server.close(() => done(undefined));
          server.closeAllConnections?.();
        }),
      });
    });
  });
}

/** The methods this fake serves, so a test can assert the allow-list is covered. */
export const MOCK_METHODS = Object.freeze([
  "host.describe",
  "session.create",
  "session.prompt",
  "session.cancel",
  "session.history",
  "session.fork",
  "session.list",
  "subagent.list",
  "subagent.history",
  "skill.list",
  "agentPreset.list",
]);

/**
 * One unmasked server-to-client text frame.
 *
 * Written out rather than pulled in: a dependency for sixteen lines of framing
 * would be a dependency in the control plane's test path, and the three length
 * forms below are the whole of what the downlink needs.
 *
 * @param {string} text
 * @returns {Buffer}
 */
function webSocketTextFrame(text) {
  const body = Buffer.from(text, "utf8");
  /** @type {Buffer} */
  let header;
  if (body.length < 126) {
    header = Buffer.from([0x81, body.length]);
  } else if (body.length < 65_536) {
    header = Buffer.alloc(4);
    header[0] = 0x81;
    header[1] = 126;
    header.writeUInt16BE(body.length, 2);
  } else {
    header = Buffer.alloc(10);
    header[0] = 0x81;
    header[1] = 127;
    header.writeBigUInt64BE(BigInt(body.length), 2);
  }
  return Buffer.concat([header, body]);
}
