import { createServer } from "node:http";
import fs from "node:fs/promises";
import path from "node:path";

async function readPromptBody(req) {
  const chunks = [];
  let bytes = 0;
  for await (const chunk of req) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
    bytes += buffer.length;
    if (bytes > 1024 * 1024) return {};
    chunks.push(buffer);
  }
  if (bytes === 0) return {};
  try {
    const value = JSON.parse(Buffer.concat(chunks, bytes).toString("utf8"));
    return value && typeof value === "object" && !Array.isArray(value) ? value : {};
  } catch {
    return {};
  }
}

export function startMockOpenCodeRuntime() {
  const clients = new Set();
  const sessions = new Map();
  const sessionStatuses = new Map();
  let counter = 0;
  let messageCounter = 0;

  const send = (res, obj) => res.write(`data: ${JSON.stringify(obj)}\n\n`);
  const broadcast = (obj) => clients.forEach((res) => send(res, obj));

  const server = createServer(async (req, res) => {
    const url = new URL(req.url ?? "/", "http://runtime.local");
    const pathname = url.pathname;
    if (req.method === "GET" && pathname === "/event") {
      res.writeHead(200, {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      });
      send(res, { type: "server.connected", properties: {} });
      clients.add(res);
      req.on("close", () => clients.delete(res));
      return;
    }
    if (req.method === "POST" && pathname === "/session") {
      const id = `web_mock_${++counter}`;
      sessions.set(id, {
        id,
        title: "科研会话",
        slug: id,
        messages: [],
      });
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ id, title: "科研会话", slug: id }));
      return;
    }
    if (req.method === "GET" && pathname === "/experimental/session") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify([...sessions.values()].map(({ messages, ...s }) => s)));
      return;
    }
    if (req.method === "GET" && pathname === "/session") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify([...sessions.values()].map(({ messages, ...s }) => s)));
      return;
    }
    if (req.method === "GET" && pathname === "/session/status") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(Object.fromEntries(sessionStatuses)));
      return;
    }
    const msgMatch = pathname.match(/^\/session\/([^/]+)\/message$/);
    if (req.method === "GET" && msgMatch) {
      const session = sessions.get(decodeURIComponent(msgMatch[1]));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(session?.messages ?? []));
      return;
    }
    const promptMatch = pathname.match(/^\/session\/([^/]+)\/(prompt_async|command|shell)$/);
    if (req.method === "POST" && promptMatch) {
      const sessionId = decodeURIComponent(promptMatch[1]);
      const session = sessions.get(sessionId);
      sessionStatuses.set(sessionId, { type: "busy" });
      const promptBody = await readPromptBody(req);
      const workspace = url.searchParams.get("directory");
      if (workspace && promptMatch[2] !== "shell") {
        await fs.mkdir(workspace, { recursive: true });
        await fs.writeFile(
          path.join(workspace, "mock-agent-artifact.md"),
          "# Mock agent artifact\n\nGenerated by the hosted mock runtime.\n",
          "utf8",
        );
      }
      const text = promptMatch[2] === "shell"
        ? "Mock shell command completed."
        : "EviMed 测试运行时已生成 mock-agent-artifact.md；生产环境将由服务端托管的科研智能体执行任务。";
      const partId = `p_${Date.now()}`;
      broadcast({
        type: "message.part.updated",
        properties: { part: { sessionID: sessionId, id: partId, type: "text", text } },
      });
      broadcast({ type: "session.idle", properties: { sessionID: sessionId } });
      if (session) {
        const userParts = Array.isArray(promptBody.parts)
          ? promptBody.parts
          : [{ type: "text", text: "web prompt" }];
        session.messages.push(
          {
            info: {
              id: `msg_${++messageCounter}`,
              role: "user",
              agent: typeof promptBody.agent === "string" ? promptBody.agent : null,
            },
            parts: userParts,
          },
          {
            info: { id: `msg_${++messageCounter}`, role: "assistant", time: { created: Date.now(), completed: Date.now() } },
            parts: [
              // EviMed-managed agents are generated with a "load every required
              // skill" instruction, so the mock mirrors the real runtime by
              // recording a successful skill load for the dispatched agent.
              ...(typeof promptBody.agent === "string" && promptBody.agent.startsWith("evimed-") ? [{
                type: "tool",
                tool: "skill",
                state: {
                  status: "completed",
                  input: { name: promptBody.agent.slice("evimed-".length) },
                  output: "Skill loaded.",
                },
              }] : []),
              ...(promptMatch[2] !== "shell" ? [{
                type: "tool",
                tool: "write",
                state: {
                  status: "completed",
                  input: { filePath: "mock-agent-artifact.md" },
                  output: "Wrote mock-agent-artifact.md",
                },
              }] : []),
              { type: "text", text },
            ],
          },
        );
      }
      sessionStatuses.delete(sessionId);
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ info: { role: "assistant" }, parts: [] }));
      return;
    }
    if (req.method === "GET" && pathname === "/config") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ model: null }));
      return;
    }
    if (req.method === "GET" && pathname === "/echo") {
      res.writeHead(200, {
        "Content-Type": "application/json",
        "Set-Cookie": "runtime_cookie=secret",
        "WWW-Authenticate": "Basic realm=\"runtime\"",
        "Proxy-Authenticate": "Basic realm=\"runtime\"",
        "Connection": "keep-alive, x-runtime-hop",
        "X-Runtime-Hop": "drop-me",
      });
      res.end(JSON.stringify({
        query: Object.fromEntries(url.searchParams.entries()),
        headers: {
          authorization: req.headers.authorization ?? null,
          cookie: req.headers.cookie ?? null,
          acceptEncoding: req.headers["accept-encoding"] ?? null,
        },
      }));
      return;
    }
    if (req.method === "GET" && pathname === "/redirect") {
      const runtimeOrigin = `http://${req.headers.host ?? "runtime.local"}`;
      res.writeHead(302, {
        "Location": `${runtimeOrigin}/echo?directory=/etc&auth_token=secret&keep=1`,
        "Set-Cookie": "runtime_redirect=secret",
        "WWW-Authenticate": "Basic realm=\"runtime\"",
      });
      res.end();
      return;
    }
    if (req.method === "GET" && pathname === "/slow-body") {
      const delayMs = Math.max(0, Math.min(Number(url.searchParams.get("delay") ?? 200), 2_000));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.flushHeaders?.();
      setTimeout(() => {
        if (!res.destroyed) res.end(JSON.stringify({ ok: true }));
      }, delayMs);
      return;
    }
    if (req.method === "GET" && pathname === "/large-response") {
      const bytes = Math.max(0, Math.min(Number(url.searchParams.get("bytes") ?? 1024), 1024 * 1024));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ data: "x".repeat(bytes) }));
      return;
    }
    if (req.method === "GET" && pathname === "/provider") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ all: [], connected: [] }));
      return;
    }
    if (req.method === "GET" && pathname === "/config/providers") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ providers: [] }));
      return;
    }
    if (req.method === "GET" && (pathname === "/agent" || pathname === "/api/agent")) {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify([{ name: "build", description: "Mock web agent", mode: "primary" }]));
      return;
    }
    if (req.method === "GET" && pathname.startsWith("/api/skill")) {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ data: [] }));
      return;
    }
    if (req.method === "GET" && pathname === "/command") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify([]));
      return;
    }
    if (req.method === "DELETE" && /^\/session\/[^/]+$/.test(pathname)) {
      const sessionId = decodeURIComponent(pathname.split("/")[2]);
      sessions.delete(sessionId);
      sessionStatuses.delete(sessionId);
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end("true");
      return;
    }
    if (req.method === "POST" && /^\/session\/[^/]+\/abort$/.test(pathname)) {
      sessionStatuses.delete(decodeURIComponent(pathname.split("/")[2]));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end("true");
      return;
    }
    res.writeHead(404, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "mock runtime route not found" }));
  });

  return new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      resolve({
        url: `http://127.0.0.1:${address.port}`,
        close: () => new Promise((done) => {
          for (const res of clients) res.end();
          clients.clear();
          server.close(done);
          server.closeAllConnections?.();
        }),
      });
    });
  });
}
